README.md
postgrest.cabal
src/PgQuery.hs
test/Feature/QuerySpec.hs

Do not add WHERE clause if only param is order

---

src/PgQuery.hs
test/Feature/QuerySpec.hs

I'm a bit baffled nobody noticed this before :P
Anyhow, without it order does not work.
Thanks,
Cheers

order does not work

---

circle.yml
postgrest.cabal
src/Config.hs
src/Main.hs
test/SpecHelper.hs
test/Unit/ConfigSpec.hs

fixes #130
Not quite finished. Needs to handle errors on parsing int options without throwing read exceptions.

Improved usage/error message when required args missing

---

README.md

You can read more about using ng-admin with postgREST here http://marmelab.com/blog/2015/03/23/using-ng-admin-with-postgrest.html

Add link to GUI demo

---

src/PostgREST/Main.hs

So I didn't know if the Main.hs would be the appropriate place but I figured that the earlier we bail out the better.

Verifies PostgreSQL version is supported (+9.2) before spawning server

---

src/PostgREST/Config.hs
src/PostgREST/Main.hs

This eliminates magic constant from Main.hs and improves docs.

Moves minimum pg version to config

---

.gitignore
CHANGELOG.md
src/PostgREST/App.hs
src/PostgREST/Auth.hs
test/Feature/AuthSpec.hs
test/fixtures/schema.sql

Squash of #291
@begriffs Missed the force push, will get that next time :blush:

Tolerate missing role in user creation

---

CHANGELOG.md
README.md
debian/postgrest.init.d
src/PostgREST/App.hs
src/PostgREST/Config.hs
test/Feature/StructureSpec.hs
test/SpecHelper.hs
test/Unit/PgQuerySpec.hx
test/Unit/PgStructureSpec.hx
test/fixtures/schema.sql

Use git from the command line they said. It builds character they said.
Anyway, I reverted the changes to `app.json` as I assume that controls your production Heroku environment, so I'll let you change that when the time comes depending on if you need to or not.

Remove versioning feature

---

src/PostgREST/PgStructure.hs

Changed the query to work on pg 9.3

Fix for #321

---

src/PostgREST/Auth.hs
src/PostgREST/PgStructure.hs
stack.yaml

This removes the need to use hspec in extra-deps and I believe it fits our development pace better :D

Changes stack resolver to nightly.

---

CHANGELOG.md
src/PostgREST/Parsers.hs
test/Feature/QuerySpec.hs

@begriffs Please merge this into master then if possible merge it to v3 so that v3 is the latest and greatest

Fix for #334

---

debian/postgrest.default
src/PostgREST/Middleware.hs

Small bug fix introduced by the last JWT PR

---

src/PostgREST/App.hs
src/PostgREST/QueryBuilder.hs
src/PostgREST/Types.hs

This should help a bit with understanding what's going on in App.hs
No code changed, just some type synonyms to better explain the parameters.
(should be merged after #369)

Add type synonyms to to beter explain things that used to be Text (2)

---

schema-templates/basic-auth.sql
schema-templates/blog.sql

Example sql for to make a blog.

Schema templates

---

src/PostgREST/App.hs
src/PostgREST/Error.hs
src/PostgREST/Main.hs
src/PostgREST/Middleware.hs
test/SpecHelper.hs

Adds a helper function for us to easily make uniform json errors.

Small error refactor

---

src/PostgREST/App.hs
src/PostgREST/DbStructure.hs
src/PostgREST/Middleware.hs
src/PostgREST/RequestIntent.hs
test/Feature/InsertSpec.hs

Currently code compiles and 5 test failing.
4 of the failing tests are related to RPC calls (maybe you can figure it out faster)
1 of the failing test is when you send a csv with the number of columns in the header not matching the other rows.
The csv parser should return a parser error in such a case

Get the refactored code to compile and pass tests

---

postgrest.cabal
src/PostgREST/ApiRequest.hs
src/PostgREST/App.hs
src/PostgREST/Middleware.hs
src/PostgREST/Parsers.hs
src/PostgREST/QueryBuilder.hs
src/PostgREST/Types.hs

I refactored the types.
Looks a bit better to me but had to split Query data type in two because otherwise it would have a few incomplete pattern matches in functions.
In some places i added "undefined" for patterns that should not normally happen. Maybe someone has a better idea, but at least it signals it's a "bad" branch that should not be reached

Type refactoring (ApiRequest/DbRequest)

---

src/PostgREST/App.hs
src/PostgREST/QueryBuilder.hs

Reduces querybuilder interface

---

CHANGELOG.md
postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/Auth.hs
src/PostgREST/Config.hs
src/PostgREST/DbStructure.hs
src/PostgREST/Main.hs
src/PostgREST/Middleware.hs
src/PostgREST/Parsers.hs
src/PostgREST/QueryBuilder.hs
src/PostgREST/RequestIntent.hs
src/PostgREST/Types.hs
test/Feature/InsertSpec.hs
test/Feature/QuerySpec.hs
test/SpecHelper.hs

This PR separates various concerns into their own modules. It defines a clean interface between modules. I'd like to use the type system better, get logic out of overkill monads, use understandable names, and document heavily.
This is a work in progress.

Disentangle code

---

CHANGELOG.md
src/PostgREST/ApiRequest.hs
src/PostgREST/QueryBuilder.hs
test/Feature/QuerySpec.hs

bugfix + Disambiguate range selection when plurality=singular

---

CHANGELOG.md
postgrest.cabal

bcrypt is no longer a required dependency

---

docs/install/server.md

Waiting for https://github.com/Homebrew/homebrew/pull/46773 to be merged to ensure that our formula upgrade techniques work.

Add brew install instructions back

---

src/PostgREST/QueryBuilder.hs
test/Feature/InsertSpec.hs

This may solve #458.
**I'm submitting this PR as a quick way of getting all the tests to run - not sure if it's correct yet!**

pgFmtLit: Change condition for using E"..." syntax

---

circle.yml
postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/Auth.hs
src/PostgREST/Config.hs
src/PostgREST/DbStructure.hs
src/PostgREST/Error.hs
src/PostgREST/Main.hs
src/PostgREST/Middleware.hs
src/PostgREST/QueryBuilder.hs
src/PostgREST/RangeQuery.hs
src/PostgREST/Types.hs
stack.yaml
test/Feature/AuthSpec.hs
test/Feature/CorsSpec.hs
test/Feature/DeleteSpec.hs
test/Feature/InsertSpec.hs
test/Feature/QueryLimitedSpec.hs
test/Feature/QuerySpec.hs
test/Feature/RangeSpec.hs
test/Feature/StructureSpec.hs
test/Main.hs
test/SpecHelper.hs

Let the code review begin! There are elements of code style and of broken functionality that need help.
Note that this compiles but that all client requests fail with the error message, "another command is already in progress."

Upgrade to Hasql 19

---

test/Feature/InsertSpec.hs

Minor proofreading in InsertSpec

---

src/PostgREST/ApiRequest.hs
src/PostgREST/App.hs
test/Feature/QuerySpec.hs

Ensure payload parse errors are not suppressed

---

CHANGELOG.md
postgrest.cabal

Fixes #445 
I suspect this will also fix the random deadlocks that @motiz88 experienced.

Do not block threads on libpq ffi

---

CHANGELOG.md
postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/Config.hs
src/PostgREST/Error.hs
src/PostgREST/Main.hs
src/PostgREST/Middleware.hs
src/PostgREST/QueryBuilder.hs
stack.yaml
test/Feature/AuthSpec.hs
test/Feature/ConcurrentSpec.hs
test/Feature/CorsSpec.hs
test/Feature/DeleteSpec.hs
test/Feature/InsertSpec.hs
test/Feature/QueryLimitedSpec.hs
test/Feature/QuerySpec.hs
test/Feature/RangeSpec.hs
test/Feature/StructureSpec.hs
test/Main.hs
test/SpecHelper.hs

Cherry-picked @diogob's commits from PR #496 and added a test of concurrent requests. Sadly the test is still failing.

Reduces pool resource locking (2)

---

circle.yml
postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/Main.hs
stack.yaml
test/Main.hs

Test that binary builds, not just that suite passes

---

docs/api/writing.md
docs/examples/external_auth.md
docs/examples/users.md

Remove a few red squiggly lines :)

Spelling fixes in documentation

---

CHANGELOG.md
postgrest.cabal
src/PostgREST/Auth.hs
src/PostgREST/Middleware.hs
test/Feature/AuthSpec.hs
test/fixtures/schema.sql

Allow SQL functions to generate registered JWT claims

---

CHANGELOG.md
src/PostgREST/QueryBuilder.hs
test/Feature/QuerySpec.hs
test/fixtures/privileges.sql
test/fixtures/schema.sql

Prevent duplicate call to stored procs

---

docs/examples/users.md
schema-templates/blog.sql

As noted in https://github.com/begriffs/postgrest/pull/450#issuecomment-196131112 and https://github.com/begriffs/postgrest/pull/525#issuecomment-196132605
Obsoletes #525

Remove remaining uuid-ossp references

---

CHANGELOG.md
src/PostgREST/ApiRequest.hs
test/Feature/QuerySpec.hs

Consolidating the commits from #530 and avoiding merging master and then merging back again.

Do not do table count when plurality=singular

---

CHANGELOG.md
app.json
postgrest.cabal

Testing 0.3.1.1 on CI as I build it on each platform.

Bump version

---

docs/examples/users.md

Suggestion by @diogob in #347.

Avoid slow PL/pgSQL exception handling in example

---

CHANGELOG.md
src/PostgREST/ApiRequest.hs
src/PostgREST/App.hs
src/PostgREST/Middleware.hs

This is a refactored version of #551

Use read-only transaction mode for read requests

---

CHANGELOG.md
src/PostgREST/App.hs
test/Feature/InsertSpec.hs

Do not include Content-Type header for empty body

---

CHANGELOG.md
src/PostgREST/QueryBuilder.hs
test/Feature/InsertSpec.hs
test/fixtures/data.sql

Use table defaults for empty object insert

---

circle.yml
postgrest.cabal
src/PostgREST/Parsers.hs
stack.yaml

Fixes #612 
@ilovezfs can you please check if this builds on Homebrew with GHC 8?

Use newer deps for GHC 8 compatibility

---

CHANGELOG.md
src/PostgREST/Error.hs
test/Feature/QuerySpec.hs

Translate raise_exception to http 400

---

CHANGELOG.md
main/Main.hs
postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/Config.hs
src/PostgREST/OpenAPI.hs
src/PostgREST/Types.hs
stack.yaml
test/Feature/ProxySpec.hs
test/Feature/StructureSpec.hs
test/Main.hs
test/SpecHelper.hs

Proxy command line option over manually specified host, port

Add proxy awareness for OpenAPI spec generation

---

src/PostgREST/QueryBuilder.hs
test/Feature/QuerySpec.hs
test/fixtures/privileges.sql
test/fixtures/schema.sql

Use table alias unlikely to conflict with a column name

---

CHANGELOG.md
src/PostgREST/Parsers.hs
src/PostgREST/QueryBuilder.hs
src/PostgREST/Types.hs
test/Feature/QuerySpec.hs

Allow using nulls order without explicit order direction, fix #552

---

CHANGELOG.md
src/PostgREST/Parsers.hs
src/PostgREST/QueryBuilder.hs
src/PostgREST/Types.hs
test/Feature/QuerySpec.hs
test/fixtures/data.sql

Fixes #644. If all is ok I can help with adding this change to the docs.

Add ability to order by jsonb keys, fix #644

---

postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/DbRequestBuilder.hs
src/PostgREST/QueryBuilder.hs

I noticed similar signatures and intention in these functions.

Move DbRequest building functions to new module

---

README.md
app.json

The new buildpack in https://github.com/begriffs/postgrest-heroku/pull/13 wants new environment variables to match the config file entries.

Fix deploy to heroku button for v0.4

---

CHANGELOG.md
src/PostgREST/App.hs
src/PostgREST/QueryBuilder.hs
test/Feature/AuthSpec.hs
test/Feature/QuerySpec.hs
test/SpecHelper.hs

Allow CSV responses from RPC

---

CONTRIBUTING.md
README.md

Fix broken link to 'building from source' in CONTRIBUTING

---

CHANGELOG.md
src/PostgREST/Parsers.hs
src/PostgREST/QueryBuilder.hs
src/PostgREST/Types.hs
test/Feature/AndOrParamsSpec.hs

Allow more than two conditions in a single and/or

---

CHANGELOG.md
src/PostgREST/Config.hs

Interpolate boolean env vars from conf file

---

CHANGELOG.md
src/PostgREST/OpenAPI.hs
test/Feature/StructureSpec.hs
test/fixtures/schema.sql

For #930 
I don't know haskell, so be gentle :)

OpenAPI: Split table comment into summary and description

---

CHANGELOG.md
src/PostgREST/QueryBuilder.hs
src/PostgREST/Types.hs
test/Feature/AndOrParamsSpec.hs
test/Feature/QuerySpec.hs
test/fixtures/data.sql
test/fixtures/privileges.sql
test/fixtures/schema.sql

Add support for range operators

---

postgrest.cabal

It builds and works fine here.

Allow optparse-applicative 0.14

---

postgrest.cabal

Fixes https://github.com/begriffs/postgrest/issues/965.

Constrain jose to < 0.6

---

main/Main.hs
postgrest.cabal
src/PostgREST/Auth.hs
src/PostgREST/Config.hs
stack.yaml
test/SpecHelper.hs

To match the version available in stack LTS-9.x.

Update jose to 0.6

---

src/PostgREST/DbStructure.hs

This gives a significant speedup at startup when you have a lot of tables in DB.

allColumns query narrowed down to current postgrest schema

---

CHANGELOG.md
src/PostgREST/DbStructure.hs
src/PostgREST/Types.hs
test/Feature/QuerySpec.hs
test/fixtures/data.sql
test/fixtures/privileges.sql
test/fixtures/schema.sql

Fix Parent Relation when having many views

---

main/Main.hs
postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/Auth.hs
src/PostgREST/Config.hs
src/PostgREST/Middleware.hs
src/PostgREST/Parsers.hs
src/PostgREST/Types.hs
stack.yaml
test/Main.hs
test/SpecHelper.hs
test/io-tests.sh
test/io-tests/configs/role-claim-key.config

Closes #906.
Also added the time cache optimization thanks to https://github.com/frasertweedale/hs-jose/issues/53.

Add role-claim-key config value

---

postgrest.cabal

Fixes https://github.com/PostgREST/postgrest/issues/1110.

postgrest.cabal: fix constraints on protolude and hasql-transaction

---

CHANGELOG.md
src/PostgREST/QueryBuilder.hs
test/Feature/UpsertSpec.hs
test/fixtures/data.sql
test/fixtures/privileges.sql
test/fixtures/schema.sql

Fixes #1113, we missed this test case in #1048.

Fix UPSERT bug on camelCase PK column

---

CHANGELOG.md
src/PostgREST/Auth.hs
test/io-tests.sh
test/io-tests/configs/simple.config

Fixes #1139.
A test case in bash is pending.

Fix JWTIssuedAtFuture for valid iat claim

---

CHANGELOG.md
main/Main.hs
src/PostgREST/Config.hs
src/PostgREST/DbStructure.hs
src/PostgREST/Middleware.hs
src/PostgREST/QueryBuilder.hs
test/Main.hs
test/io-tests.sh
test/io-tests/configs/app-settings.config

Fix #1141, app.settings resetting on pool timeout

---

README.md
appveyor.yml
postgrest.cabal

Fixing some cabal issues. With the version pinning now plain `cabal install && cabal build` works.

Cabal additions

---

CHANGELOG.md
app.json
appveyor.yml
postgrest.cabal
test/memory-tests.sh

Changes for bumping to the new version.

Bump to 5.1.0

---

postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/DbStructure.hs
src/PostgREST/Error.hs
src/PostgREST/QueryBuilder.hs
stack.yaml

Rebase the work on https://github.com/PostgREST/postgrest/pull/1136 and pin versions on stack file.

Upgrade hasql

---

CHANGELOG.md
main/Main.hs
postgrest.cabal
src/PostgREST/ApiRequest.hs
src/PostgREST/App.hs
src/PostgREST/Auth.hs
src/PostgREST/DbRequestBuilder.hs
src/PostgREST/DbStructure.hs
src/PostgREST/Middleware.hs
src/PostgREST/OpenAPI.hs
src/PostgREST/Parsers.hs
src/PostgREST/QueryBuilder.hs
src/PostgREST/RangeQuery.hs
test/Feature/AsymmetricJwtSpec.hs
test/Feature/BinaryJwtSecretSpec.hs
test/Feature/ConcurrentSpec.hs
test/Feature/CorsSpec.hs
test/Feature/NoJwtSpec.hs
test/Feature/PgVersion95Spec.hs
test/Feature/PgVersion96Spec.hs
test/Feature/ProxySpec.hs
test/Feature/QueryLimitedSpec.hs
test/Feature/QuerySpec.hs
test/Feature/RpcSpec.hs
test/Feature/StructureSpec.hs
test/Main.hs
test/SpecHelper.hs
test/fixtures/schema.sql

Fix #1181, correct qualify of function argument type

---

CHANGELOG.md
main/Main.hs
test/io-tests.sh
test/io-tests/configs/dburi-from-file.config
test/io-tests/dburis/uri.noeol
test/io-tests/dburis/uri.txt

This PR is expected to solve issue [#1203](https://github.com/PostgREST/postgrest/issues/1203).

Read db-uri configuration from a separate file.

---

CHANGELOG.md
src/PostgREST/Parsers.hs
test/Feature/QuerySpec.hs
test/fixtures/data.sql
test/fixtures/privileges.sql
test/fixtures/schema.sql

Fix using columns with spaces, allow quoting columns

---

CHANGELOG.md
src/PostgREST/DbRequestBuilder.hs
src/PostgREST/DbStructure.hs
src/PostgREST/Error.hs
src/PostgREST/Middleware.hs
src/PostgREST/OpenAPI.hs
src/PostgREST/Parsers.hs
src/PostgREST/QueryBuilder.hs
src/PostgREST/RangeQuery.hs
src/PostgREST/Types.hs
test/Feature/QuerySpec.hs
test/fixtures/data.sql
test/fixtures/privileges.sql
test/fixtures/schema.sql

Fixes #1221.
Moved the the self join logic from QueryBuilder to DbRequestBuilder.

Fix self join and refactor

---

CHANGELOG.md
src/PostgREST/ApiRequest.hs
src/PostgREST/App.hs
src/PostgREST/DbRequestBuilder.hs
src/PostgREST/Parsers.hs
src/PostgREST/Types.hs
test/Feature/InsertSpec.hs
test/Feature/RpcSpec.hs
test/Main.hs

Fixes #1273.
Also some refactoring to aid with relational inserts implementation.

RPC shouldn't ignore unknown args by default

---

Makefile

Created a makefile with some of the most common and tongue-twisting commands for developing purposes.
Style is commented as of now, as using it, will change all source files.

Add makefile with common commands

---

.circleci/config.yml
CHANGELOG.md
main/Main.hs
postgrest.cabal
src/PostgREST/Config.hs
test/SpecHelper.hs
test/io-tests.sh
test/io-tests/configs/unix-socket.config

Targeting #1186 
Hello, I have corrected the issues from my previous pull request and had to make some changes to make it merge-able after the styling changes
The only thing that is missing is a test in io-test.sh, which I am trying to work on. If anyone is able to give me some pointers on how the bash tests are organized that would be very helpful.

Add server-unix-socket option to enable trafic to postgrest server via unix socket

---

CHANGELOG.md
src/PostgREST/ApiRequest.hs
src/PostgREST/App.hs
src/PostgREST/Error.hs
src/PostgREST/Types.hs
test/Feature/QuerySpec.hs
test/Feature/RpcSpec.hs
test/fixtures/schema.sql

One more feature before the release. This one fixes #1308.

Accept `text/plain` and `text/html` for raw output

---

stack.yaml

See also https://github.com/haskell/cabal/issues/4739.

Work around macos case sensitivity issue

---

.circleci/config.yml
src/PostgREST/Types.hs
test/Feature/RpcSpec.hs

See https://www.postgresql.org/docs/release/11.4/.

Update json rpc argument tests for bugfix in PostgreSQL 11.4

---

src/PostgREST/Types.hs
test/Feature/RpcSpec.hs

This removes the test for buggy behaviour, it seems not useful
anymore.

Fix json test versioning for postgresql 10.9 bugfix

---

postgrest.cabal
stack.yaml
test/Feature/AuthSpec.hs

compare https://github.com/frasertweedale/hs-jose/issues/83

bump jose dependency to 0.8.1, to fix windows trouble

---

CHANGELOG.md
src/PostgREST/Config.hs

Change raw-media-types to accept a string of comma separated MIME types

---

src/PostgREST/Error.hs
test/Feature/QuerySpec.hs
test/Feature/RpcSpec.hs

I was confused by the wording of the error and I hope this improves it.
@steve-chavez would the extraction of error messages to a resource file be welcomed? 
It would make it unnecessary for simple changes like this to make also changes on existing tests

Reword error message for BinaryFieldError

---

CHANGELOG.md
app.json
postgrest.cabal

Let's do a PATCH release now that we got some bugs cleared. We should be stable for v6 now.

Release 6.0.2

---

.circleci/config.yml
.github/CONTRIBUTING.md
Makefile

Helps with forgetting to run the styler/linter before doing a PR.

Recommend doing make check pre-commit

---

CHANGELOG.md
src/PostgREST/DbStructure.hs
test/Feature/QuerySpec.hs
test/Feature/StructureSpec.hs
test/fixtures/data.sql
test/fixtures/privileges.sql
test/fixtures/schema.sql

Continuing the work on #1361. Should fix #1360

Fix unique foreign key in view

---

.circleci/config.yml
test/docker-compose.yml

Just to make sure everything is working with postgres 12 as well.

add postgres-12 tests to circleci

---

postgrest.cabal
src/PostgREST/OpenAPI.hs
stack.yaml
stack.yaml.lock
test/Feature/InsertSpec.hs

This is on top of #1484. Compare https://github.com/PostgREST/postgrest/issues/1474#issuecomment-614193568

Update stack.yaml to lts-15.8 (GHC 8.8.3)

---

stack.yaml

Fixes the issue noted in https://github.com/PostgREST/postgrest/pull/1493

Disable nix pure by default in stack.yaml

---

.circleci/config.yml
nix/overlays/haskell-packages/protolude.nix

This should be faster, more consistent (as the same scripts can be used for local development) and hopefully less random than the stack-based integration :-)

Hook the Nix styling scripts into CI

---

.circleci/config.yml
test/Main.hs
test/QueryCost.hs
test/SpecHelper.hs
test/create_test_db
test/fixtures/jsonschema.sql
test/fixtures/jwt.sql
test/fixtures/load.sql
test/with_tmp_db

More consistent loading of the test fixtures

---

CHANGELOG.md
Makefile
src/PostgREST/ApiRequest.hs
src/PostgREST/App.hs
src/PostgREST/Config.hs
src/PostgREST/Error.hs
src/PostgREST/Types.hs
test/Feature/MultipleSchemaSpec.hs
test/Feature/UpsertSpec.hs

Some fixes for a new patch release.

Fixes for v7.0.1

---

.cirrus.yml
appveyor.yml

- Change appveyor Windows image to see if it could workaround https://github.com/PostgREST/postgrest/issues/1373.
- Added a FreeBSD CI http://cirrus-ci.com/. (work in progress)

CI additions/fixes

---

test/Feature/RawOutputTypesSpec.hs
test/Feature/SingularSpec.hs

While debugging something that ultimately turned out to be a bug in my app, I added some test-cases. They already pass, but I guess it makes sense to add those tests cases for `DELETE` and `PATCH`, because one already exists for `POST` as well.
Also fixed another one, probably just a copy-paste mistake.

add test cases for singular minimal

---

postgrest.cabal

Builds fine and all tests pass here.

Allow hspec-wai/hspec-wai-json 0.11

---

.circleci/config.yml
default.nix
nix/nixpkgs-version.nix
nix/overlays/postgresql-default.nix
nix/patches/nixpkgs-revert-ghc-bootstrap.patch
src/PostgREST/Types.hs
test/Feature/InsertSpec.hs
test/docker-compose.yml

- upgrade nixpkgs to current master
- link against libpq from Postgres 13 by default
- integrate tests against Postgres 13
- Fix tests for a changed error message in Postgres 13

Upgrade nixpkgs and add Postgres 13 support

---

.travis.yml

see https://github.com/PostgREST/postgrest/pull/1619#discussion_r504721267

fix travis build timeout swallowing error code

---

CHANGELOG.md

See https://github.com/PostgREST/postgrest/pull/1603#discussion_r505848059

correct issue numbers in changelog

---

src/PostgREST/ApiRequest.hs
test/Feature/RpcSpec.hs
test/fixtures/schema.sql

Based on the branch in #1636.
See https://github.com/PostgREST/postgrest/pull/1636#discussion_r513634107

Fix variadic mixed repeated args

---

src/PostgREST/Config.hs

Related to https://github.com/PostgREST/postgrest-docs/pull/367.

Cleanup postgrest --help

---

src/PostgREST/Config.hs

See https://github.com/PostgREST/postgrest/pull/1667#discussion_r528830815.
At some point the distinction between the two settings / bools has to be made. Instead of creating another type for this setting, passing this into Api.hs and then destructuring it there, I decided to do the destructuring immediately at the source, when parsing the config file. Everything else is untouched, the internal config object still has `configTxRollbackAll` and `configTxAllowOverride`.
What do you think - is that fine?

Refactor tx-... config options to single tx-end option

---

shell.nix

TIL bash autocompletion. Fixes one item of #1671

Add autocompletion for postgrest-watch

---

.circleci/config.yml
nix/devtools.nix
nix/tests.nix

Add a CI check that spec tests can be run twice against the same db.
Also added io tests to postgrest-check

Add check for spec tests idempotence

---

test/io-tests/test_io.py

This should fix https://github.com/PostgREST/postgrest/pull/1682#issuecomment-744110866

fix: catch ReadTimeout in IO tests

---

test/Feature/InsertSpec.hs
test/fixtures/privileges.sql
test/fixtures/schema.sql

Noticed another concurrency issue with our spec tests, now that we are running them in parallel. Happened in #1694, putting up a separate PR to keep things simple.
Will just wait for CI before merging.

Fix spec test concurrency issue related to commit on simple_pk

---

main/Main.hs

I worked with `--dump-schema` during development and had an error in the dbStructure queries. Before those changes I only got a pattern matching error, now the hasql error is shown on stdout. Formatting could probably be improved a little bit, because the query string is displayed with `\n` instead of newlines, but it's much better than before.

Add basic error handling to --dump-schema

---

.gitignore
nix/devtools.nix

Current output:
This could be a useful tool to maintain the module structure.

Add a script to generate a graph of Haskell imports

---

default.nix
nix/devtools.nix
nix/overlays/checked-shell-script/checked-shell-script.nix
nix/tests.nix
nix/withtmpdb.nix

Took the first commit out of #1609. Working on putting my take at the loadtest in a branch, so that refactor will serve me well, too. Then realized I'll need a temporary directory again - and refactored that into `checkedShellScript`, too.
Fixes #1807 properly - I guess. @monacoremo you might want to try whether that works reliably for you.

Improve `checkedShellScript`

---

src/PostgREST/Request/ApiRequest.hs
test/Feature/RpcSpec.hs
test/fixtures/schema.sql

fix: Fix requests for overloaded functions from html forms to no longer hang

---

src/PostgREST/Error.hs
test/Feature/EmbedDisambiguationSpec.hs
test/Feature/QuerySpec.hs

Implements the enhacement mentioned in #1845

feat: Add a hint and clarification to the no relationship found error

---

CHANGELOG.md
app.json
postgrest.cabal

Closes #1779.
- Correct/organize the CHANGELOG
- Bumps to v8.0.0

Bumps to v8.0.0

---

nix/overlays/checked-shell-script/checked-shell-script.nix
nix/tools/memory.nix
nix/tools/tests.nix
nix/tools/withTools.nix

Just two commits taken out of #1829.

Small improvements to nix env

---

postgrest.cabal

Builds fine and all tests are passing here, with the new versions.

Allow newer base, hspec, and retry

---

postgrest.cabal

pre-release: Bump to v9.0.0-a1

---

test/Feature/RpcSpec.hs

A small fix for this test. The `limit` in the query wasn't doing anything due to the `?` operator.

Fix the limit proc results test

---

CHANGELOG.md
src/PostgREST/App.hs
src/PostgREST/CLI.hs
src/PostgREST/Config.hs
src/PostgREST/Query/QueryBuilder.hs
src/PostgREST/Request/DbRequestBuilder.hs
test/Feature/EmbedInnerJoinSpec.hs
test/Main.hs
test/SpecHelper.hs
test/io-tests/configs/expected/aliases.config
test/io-tests/configs/expected/boolean-numeric.config
test/io-tests/configs/expected/boolean-string.config
test/io-tests/configs/expected/defaults.config
test/io-tests/configs/expected/no-defaults-with-db-other-authenticator.config
test/io-tests/configs/expected/no-defaults-with-db.config
test/io-tests/configs/expected/no-defaults.config
test/io-tests/configs/expected/types.config
test/io-tests/configs/no-defaults.config
test/io-tests/test_io.py

As agreed on https://github.com/PostgREST/postgrest/issues/1783#issuecomment-962516607.

Remove the db-embed-default-join config

---

test/Feature/RpcSpec.hs
test/fixtures/schema.sql

test: Add test to confirm ASSERT will return 500 Internal Server Error

---

src/PostgREST/Query/QueryBuilder.hs
test/Feature/EmbedInnerJoinSpec.hs

Correct count when using `!inner` resource embedding

---

CHANGELOG.md
app.json
postgrest.cabal

We're still not PostgreSQL 14 compatible on docker latest, I think it's time to do a new stable release.
@wolfgangwalther @monacoremo @laurenceisla WDYT?

Bump to v9

---

src/PostgREST/Version.hs

fix: Link to latest docs in pre-release

---

CHANGELOG.md
src/PostgREST/Request/Parsers.hs
test/Feature/QuerySpec.hs

fix: `is` not working with upper/mixed case values

---

postgrest.cabal
test/coverage.overlay

Trying a test commit because somehow codecov failed on https://github.com/PostgREST/postgrest/commit/a134d8a493e572e32d30f0c21e51b6f467ab24fb.

update cabal description

---

CHANGELOG.md
postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/Auth.hs
src/PostgREST/Cors.hs
src/PostgREST/Logger.hs
src/PostgREST/Middleware.hs
src/PostgREST/Request/ApiRequest.hs
test/coverage.overlay
test/io/fixtures.sql
test/io/test_io.py

See discussion in #1988.
TODO:

Add current user to the request log

---

CHANGELOG.md
src/PostgREST/Config/Database.hs
test/io/configs/expected/no-defaults-with-db.config
test/io/db_config.sql

fix: Read database configuration properly when = is present in value

---

CHANGELOG.md
src/PostgREST/Error.hs
src/PostgREST/Request/DbRequestBuilder.hs
src/PostgREST/Request/Types.hs
test/spec/Feature/QuerySpec.hs

Fix embedded filter silently getting ignored

---

nix/tools/release/default.nix

As proposed in https://github.com/PostgREST/postgrest/issues/2006#issuecomment-1007661689.
I just created a new pre-release with this tool.
The output was the following:
```
nix-shell% postgrest-release
Current version is 9.0.0.20220107.
1) 9.0.0.20220130
2) 9.0.1
3) 9.1.0
4) 10.0.0
Please select the new version: 1
Selected 9.0.0.20220130 ...
Updating postgrest.cabal ...
Committing ...
[...]
Tagging ...
To push both the branch and the new tag, the following will be run:
git push --atomic upstream main v9.0.0.20220130
Proceed? (y/N) y
[...]
To github.com:PostgREST/postgrest.git
58f76f3d..c894b543  main -> main
* [new tag]           v9.0.0.20220130 -> v9.0.0.20220130
```
This can be used for both regular releases and pre-releases.

nix: Add postgrest-release tool

---

CHANGELOG.md

Fixes incorrectly placed feature for PostgREST errors from v9.0.0 to Upcoming in the CHANGELOG

Fix incorrect placed feature in CHANGELOG

---

src/PostgREST/DbStructure.hs

Right now `allM2ORels` is including relationships to partitions. We decided to eliminate partitions from the schema cache in https://github.com/PostgREST/postgrest/pull/2022.
The current codebase doesn't consider these relationships because they get filtered by `findCol`:
https://github.com/PostgREST/postgrest/blob/7f1507b9fbc792d58e5200a7c3288968e368005f/src/PostgREST/DbStructure.hs#L643-L649
When `Relationship` doesn't hold `Column` anymore(needed as commented on https://github.com/PostgREST/postgrest/pull/2250) these partitions' relationships will be included in the schema cache and cause test failures.

refactor: ignore partitions in allM2ORels

---

CHANGELOG.md
src/PostgREST/App.hs
src/PostgREST/Query/Statements.hs
test/spec/Feature/Query/QuerySpec.hs
test/spec/fixtures/privileges.sql
test/spec/fixtures/schema.sql

Allow returning XML from single-column queries

---

.github/workflows/ci.yaml

Fix Windows build using Stack in CI

---

src/PostgREST/DbStructure.hs
src/PostgREST/DbStructure/Relationship.hs
src/PostgREST/OpenAPI.hs
src/PostgREST/Request/DbRequestBuilder.hs
test/spec/Feature/OpenApi/RootSpec.hs
test/spec/Feature/Query/EmbedDisambiguationSpec.hs
test/spec/fixtures/data.sql
test/spec/fixtures/privileges.sql
test/spec/fixtures/schema.sql

* Adds a test case for self-relationships on views(taken from https://github.com/PostgREST/postgrest/pull/2272#issuecomment-1120389553)
* Cherry picks https://github.com/PostgREST/postgrest/pull/2272/commits/c7660b3841d487bee863c74af778ab614f6e3503

Refactor how self relationships are done

---

CHANGELOG.md
postgrest.cabal

Closes https://github.com/PostgREST/postgrest/issues/2294, closes https://github.com/PostgREST/postgrest/issues/1076

fix: disable parallel GC for perf on high-core CPU

---

nix/tools/withTools.nix

This allows running the load test against main even if the dependencies change.

nix: build postgrest with nix in loadtest (fixes #2308)

---

CHANGELOG.md
src/PostgREST/Middleware.hs
src/PostgREST/Query/SqlFragment.hs
test/doc/Main.hs
test/io/test_io.py
test/spec/Feature/ExtraSearchPathSpec.hs
test/spec/Feature/Query/MultipleSchemaSpec.hs
test/spec/SpecHelper.hs
test/spec/fixtures/data.sql
test/spec/fixtures/privileges.sql
test/spec/fixtures/schema.sql

Allow uppercase, spaces and other special characters in schema names

---

CHANGELOG.md
src/PostgREST/Query/Statements.hs
src/PostgREST/Request/Preferences.hs
test/spec/Feature/Query/InsertSpec.hs

Return Location header only when using Prefer: return=header-only

---

CHANGELOG.md
src/PostgREST/Query/QueryBuilder.hs
test/spec/Feature/Query/EmbedInnerJoinSpec.hs
test/spec/fixtures/data.sql
test/spec/fixtures/privileges.sql
test/spec/fixtures/schema.sql

Fix top level filter count to not depend on the order in the query string

---

CHANGELOG.md
src/PostgREST/App.hs
test/io/test_io.py

Closes https://github.com/PostgREST/postgrest/issues/2376.

fix: no empty transaction on OPTIONS request

---

CHANGELOG.md
src/PostgREST/App.hs
src/PostgREST/Request/ApiRequest.hs
test/io/test_io.py
test/spec/Feature/OptionsSpec.hs
test/spec/Feature/Query/RpcSpec.hs

Partly addresses https://github.com/PostgREST/postgrest/issues/1826

feat: support OPTIONS on RPC and root path

---

CHANGELOG.md
src/PostgREST/App.hs
src/PostgREST/MediaType.hs
src/PostgREST/Query/Statements.hs
src/PostgREST/Request/ApiRequest.hs
test/spec/Feature/Query/PlanSpec.hs

Continues https://github.com/PostgREST/postgrest/pull/2368

Add "for" param for the vnd.pgrst.plan media type

---

test/io/test_io.py

This primarily adds a test to prove #2401.

Add test for #2401

---

CHANGELOG.md
src/PostgREST/MediaType.hs
test/spec/Feature/Query/PlanSpec.hs

Discussed here: https://github.com/PostgREST/postgrest-docs/pull/563#discussion_r948172141

Make text the default format for the execution plan

---

src/PostgREST/DbStructure.hs

* remove unnecessary lateral usage
* use alias for pg_constraint

refactor: clean allM2ORels query

---

CHANGELOG.md

Move feature to bugfix in the changelog

---

src/PostgREST/Request/QueryParams.hs

Correct typos in QueryParams.hs

---

src/PostgREST/DbStructure.hs
test/spec/Feature/Query/MultipleSchemaSpec.hs
test/spec/fixtures/data.sql
test/spec/fixtures/privileges.sql
test/spec/fixtures/schema.sql

Fix embedding with computed relationships not working with schema names with special characters

---

src/PostgREST/App.hs
src/PostgREST/Error.hs
src/PostgREST/Request/ApiRequest.hs
src/PostgREST/Request/Types.hs
test/spec/Feature/Query/RangeSpec.hs

Add error message when Prefer: count=exact is used and offset is out of bounds

---

nix/tools/docker/README.md

Taken from the discussion here: https://github.com/PostgREST/postgrest/discussions/2381#discussioncomment-3194815

nix: Add hint how to derive docker image

---

postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/Middleware.hs
src/PostgREST/Query.hs
src/PostgREST/Query/SqlFragment.hs

Adds a Query.hs module picking up the work on https://github.com/PostgREST/postgrest/pull/1831.

refactor: add Query.hs module

---

postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/Error.hs
src/PostgREST/Query.hs
src/PostgREST/Query/SqlFragment.hs
src/PostgREST/Request/ApiRequest.hs
src/PostgREST/Request/QueryParams.hs
src/PostgREST/Request/ReadQuery.hs
src/PostgREST/Request/Types.hs
src/PostgREST/Response.hs
src/PostgREST/Response/OpenAPI.hs

Addressing the comment on https://github.com/PostgREST/postgrest/pull/1831#discussion_r624211620

refactor: move binaryField to ApiRequest

---

postgrest.cabal

Builds fine and all tests pass.

Allow jose 0.10

---

postgrest.cabal

Builds fine and all tests pass.

Allow vector 0.13

---

postgrest.cabal

Builds fine and all tests pass.

Allow aeson 2.1

---

CHANGELOG.md
src/PostgREST/ApiRequest/Types.hs
src/PostgREST/Plan.hs
src/PostgREST/Plan/ReadPlan.hs
src/PostgREST/Query/QueryBuilder.hs
src/PostgREST/Query/SqlFragment.hs
test/spec/Feature/Query/ComputedRelsSpec.hs
test/spec/fixtures/privileges.sql
test/spec/fixtures/schema.sql

Closes https://github.com/PostgREST/postgrest/issues/2455.

Fix embedding the same table multiple times

---

CHANGELOG.md
src/PostgREST/Plan.hs
src/PostgREST/Plan/ReadPlan.hs
src/PostgREST/Query/QueryBuilder.hs
test/spec/Feature/Query/ComputedRelsSpec.hs
test/spec/fixtures/schema.sql

fix: embedding computed with normal relationship

---

CHANGELOG.md
src/PostgREST/ApiRequest.hs
src/PostgREST/Plan.hs
src/PostgREST/RangeQuery.hs
test/spec/Feature/Query/QueryLimitedSpec.hs

Partially addresses #2558
~~Remove panic from `rangeOffset` function~~ . Left this one for later since it may take more time to fix.

fix: Fatal error when requesting limit=0 and db-max-rows is set

---

CHANGELOG.md
src/PostgREST/Error.hs
src/PostgREST/Plan.hs
src/PostgREST/Plan/ReadPlan.hs
src/PostgREST/SchemaCache/Relationship.hs
test/spec/Feature/Query/RpcSpec.hs
test/spec/fixtures/schema.sql

Closes https://github.com/PostgREST/postgrest/issues/2565

fix: bad M2M embed on RPC

---

CHANGELOG.md
test/spec/Feature/Query/EmbedDisambiguationSpec.hs
test/spec/Feature/Query/SpreadQueriesSpec.hs
test/spec/fixtures/data.sql
test/spec/fixtures/schema.sql

- Closes #1907 
- Closes #2566

Add new tests for spread embeds 

---

CHANGELOG.md
src/PostgREST/ApiRequest/QueryParams.hs
test/spec/Feature/Query/EmbedDisambiguationSpec.hs
test/spec/Feature/Query/SpreadQueriesSpec.hs

As mentioned on https://github.com/PostgREST/postgrest/pull/2564#issuecomment-1336056558

correct spread embed to '...'

---

src/PostgREST/Plan.hs
test/spec/Feature/Query/RelatedQueriesSpec.hs

Closes https://github.com/PostgREST/postgrest/issues/2588

correct bad null filter restriction

---

CHANGELOG.md
src/PostgREST/Response/OpenAPI.hs
src/PostgREST/SchemaCache.hs
test/spec/Feature/OpenApi/OpenApiSpec.hs
test/spec/fixtures/schema.sql

Add items when a paramater is array on OpenAPI output

---

CHANGELOG.md
src/PostgREST/Response/OpenAPI.hs
test/spec/Feature/OpenApi/OpenApiSpec.hs

Add upsert headers for POST requests to the OpenAPI output

---

src/PostgREST/Response/OpenAPI.hs
test/spec/Feature/OpenApi/OpenApiSpec.hs
test/spec/fixtures/schema.sql

fix: FK pointing to VIEW instead of TABLE in OpenAPI output

---

CHANGELOG.md
src/PostgREST/Workers.hs
test/io/fixtures.sql
test/io/test_io.py

Fixes https://github.com/PostgREST/postgrest/issues/2620

fix: NOTIFY pgrst not reoading the catalog cache

---

CHANGELOG.md

Prepare CHANGELOG for release.

Update CHANGELOG to include release 10.1.2

---

CHANGELOG.md
src/PostgREST/Response/OpenAPI.hs
test/spec/Feature/OpenApi/OpenApiSpec.hs

Closes #1222 (and maybe #1151?)

Add 'get' to the path item for functions

---

.github/workflows/ci.yaml
nix/tools/release/default.nix
src/PostgREST/ApiRequest.hs

Fixes latest fail https://github.com/PostgREST/postgrest/actions/runs/4137938488/jobs/7153732683.

fix CI and small refactor

---

nix/tools/withTools.nix

Fix according to https://github.com/PostgREST/postgrest/pull/2666#discussion_r1110979555

nix: fix PGTZ on postgrest-with-* commands

---

src/PostgREST/ApiRequest.hs
src/PostgREST/App.hs
src/PostgREST/Plan.hs
src/PostgREST/Plan/CallPlan.hs
src/PostgREST/Query.hs

Refactor needed for https://github.com/PostgREST/postgrest/pull/1582. Solves what's commented on https://github.com/PostgREST/postgrest/issues/1804#issuecomment-1267591660.

refactor: remove SchemaCache from ApiRequest

---

src/PostgREST/Query.hs

The previous use of [`Hasql.Transaction.sql`](https://hackage.haskell.org/package/hasql-transaction-1.0.1.2/docs/Hasql-Transaction.html#v:sql) means that the pre-request statement can't be prepared, regardless of configuration setting.
This change makes it so that it can be prepared.
I'm a bit unsure whether this is actually an improvement -- the pre-request statement is just a parameter-less `SELECT pre_req_func()`, so we'd only be saving the parsing of that server-side.
Load test results seem to indicate a slight improvement, but they're not really conclusive: Locally, I see a request rate of ~380 with plain `postgrest-loadtest`, ~370 with `PGRST_DB_PRE_REQUEST=call_me_prereq postgrest-loadtest` on the `main` branch, and ~375 with this change. (`call_me_prereq` is from this commit: …

perf (?): make pre-request preparable

---

.github/scripts/arm/build.sh

Closes #2675 
Changes working on a test repository that connects to the ARM server: https://github.com/laurence-isla/github-actions-test/actions/runs/4504899339/jobs/7929954628

ci: Update ARM build script to use GHC 9.2.4

---

CHANGELOG.md
src/PostgREST/ApiRequest/Preferences.hs
src/PostgREST/Plan.hs
src/PostgREST/Plan/CallPlan.hs
src/PostgREST/Query.hs
src/PostgREST/Query/QueryBuilder.hs
src/PostgREST/Query/SqlFragment.hs
src/PostgREST/Query/Statements.hs
src/PostgREST/SchemaCache.hs
src/PostgREST/SchemaCache/Proc.hs
test/spec/Feature/Query/PlanSpec.hs
test/spec/Feature/Query/RpcSpec.hs

Needed for https://github.com/PostgREST/postgrest/pull/1582
* [drop: Prefer: params=multiple-objects on RPC](https://github.com/PostgREST/postgrest/commit/87c0f08c9240723b9f2a79550127dcbede5634e3)
* [refactor: remove Maybe from RetType for Proc type](https://github.com/PostgREST/postgrest/commit/db25387df03b78a6c30f958ec5ba1ab8d308c392)
* [refactor: wrap proc logic in asJsonF](https://github.com/PostgREST/postgrest/commit/077d7e863c304bef2014e74dfe4c66b460b8d582)

refactor: wrap function logic in asJsonF

---

.github/workflows/ci.yaml
CHANGELOG.md
src/PostgREST/CLI.hs
src/PostgREST/Config.hs
src/PostgREST/Config/Database.hs
src/PostgREST/Query.hs
src/PostgREST/SchemaCache.hs
src/PostgREST/Workers.hs
test/io/fixtures.sql
test/io/test_io.py
test/spec/Main.hs
test/spec/SpecHelper.hs

- Closes https://github.com/PostgREST/postgrest/issues/2561 
- Closes https://github.com/PostgREST/postgrest/issues/249

feat: configurable role settings

---

CHANGELOG.md
test/spec/Feature/Query/UpdateSpec.hs

Already fixed, only adds tests and CHANGELOG as mentioned in: https://github.com/PostgREST/postgrest/pull/2618#issuecomment-1465708388

fix: PATCH requests not recognizing embedded filters

---

src/PostgREST/ApiRequest.hs
src/PostgREST/MediaType.hs
src/PostgREST/Plan.hs
src/PostgREST/Query/SqlFragment.hs
src/PostgREST/Query/Statements.hs
test/spec/Feature/Query/PlanSpec.hs

Adding a refactor from #2825 here.

refactor: stricter plan media type

---

CHANGELOG.md
postgrest.cabal
src/PostgREST/Plan.hs
src/PostgREST/Plan/MutatePlan.hs
src/PostgREST/Plan/ReadPlan.hs
src/PostgREST/Plan/Types.hs
src/PostgREST/Query/QueryBuilder.hs
src/PostgREST/Query/SqlFragment.hs
src/PostgREST/SchemaCache.hs
src/PostgREST/SchemaCache/Representations.hs
test/spec/Feature/Query/ComputedRelsSpec.hs
test/spec/Feature/Query/InsertSpec.hs
test/spec/Feature/Query/QuerySpec.hs
test/spec/Feature/Query/UpdateSpec.hs
test/spec/Main.hs
test/spec/fixtures/data.sql
test/spec/fixtures/schema.sql

Continuing the great work at https://github.com/PostgREST/postgrest/pull/2523.

feat: domain representations

---

.github/scripts/arm/docker-env/Dockerfile

ci: fix ARM docker containers not stopping immediately

---

src/PostgREST/ApiRequest/QueryParams.hs
src/PostgREST/ApiRequest/Types.hs
src/PostgREST/Plan.hs
src/PostgREST/SchemaCache/Routine.hs
test/doc/Main.hs

test: doctest for addNullEmbedFilters

---

src/PostgREST/AppState.hs
test/io/postgrest.py
test/io/test_io.py

Show PostgREST version in the logs

---

CHANGELOG.md
src/PostgREST/SchemaCache.hs
test/spec/Feature/Query/InsertSpec.hs
test/spec/Feature/Query/UpdateSpec.hs
test/spec/fixtures/data.sql
test/spec/fixtures/schema.sql

Closes #2861 and closes https://github.com/PostgREST/postgrest/issues/1586

fix: character and bit columns with length not inserting/updating properly

---

nix/README.md

Fixes issue #2870.
Note: Didn't update CHANGELOG.md as this is not a important change to the project.

Update Nix development and build guide (README.md)

---

CHANGELOG.md
src/PostgREST/Query/QueryBuilder.hs
test/spec/Feature/Query/RpcSpec.hs
test/spec/fixtures/schema.sql

fix: error when a function returns RECORD or SETOF RECORD

---

CHANGELOG.md
src/PostgREST/Config/Database.hs
test/io/fixtures.sql
test/io/test_io.py

Closes https://github.com/PostgREST/postgrest/issues/2896

fix: impersonated role applying superuser settings

---

CHANGELOG.md
src/PostgREST/MediaType.hs
test/spec/Feature/Query/NullsStrip.hs

Completes #2894. 
This should close #1601.

fix: application/vnd.pgrst.array not accepted as a valid mediatype

---

nix/nixpkgs-version.nix

Reverts PostgREST/postgrest#2891

Revert "Update nixpkgs to 2023-08-04"

---

CHANGELOG.md
src/PostgREST/Response.hs

fix: duplicate headers in response

---

CHANGELOG.md
src/PostgREST/Error.hs
test/spec/Feature/Query/RpcSpec.hs
test/spec/fixtures/schema.sql

This should fix #2492.
@steve-chavez The code needs some refactoring. But before that, please review this new interface and suggest improvements.

feat: allow full response control when raising exceptions

---

CHANGELOG.md
src/PostgREST/RangeQuery.hs
test/spec/Feature/Query/RangeSpec.hs

fix: range request with first position same as length return status 206

---

CHANGELOG.md
src/PostgREST/Config/Database.hs

fix: unnecessary set default_transaction_isolation

---

CHANGELOG.md
src/PostgREST/Plan.hs
test/spec/Feature/Query/JsonOperatorSpec.hs
test/spec/fixtures/schema.sql

fix: arrow filter on RPC returning TABLE+composite

---

default.nix

Grabbed the diff from https://github.com/PostgREST/postgrest/issues/2973#issuecomment-1738977056
Closes #2973

ci: fix MacOS CI

---

src/PostgREST/App.hs
src/PostgREST/Response.hs

refactor: complete purifying Response module

---

src/PostgREST/ApiRequest/Types.hs
src/PostgREST/Error.hs
src/PostgREST/Query.hs
src/PostgREST/Response.hs
test/spec/Feature/Query/RpcSpec.hs

Small refactor to help with:
https://github.com/PostgREST/postgrest/issues/2901

refactor: DRY application/json on Error.hs

---

CHANGELOG.md
src/PostgREST/RangeQuery.hs
test/spec/Feature/Query/RangeSpec.hs

fix: range request with 0 rows and 0 offset return status 416

---

src/PostgREST/Error.hs

refactor: DRY and enforce error format

---

test/spec/Feature/Query/PlanSpec.hs
test/spec/SpecHelper.hs

test: add tests for batch upserts

---

CHANGELOG.md
src/PostgREST/Query/Statements.hs
src/PostgREST/SchemaCache/Routine.hs
test/spec/Feature/Query/PlanSpec.hs
test/spec/Feature/Query/RpcSpec.hs

Small win in plan cost as shown in the tests.

fix: unnecessary count() on RPC returning single

---

test/spec/Feature/Query/PlanSpec.hs

Fixes typos in batch upsert tests added in #3005.

test: fix typos in batch upsert tests

---

test/spec/Feature/Query/QuerySpec.hs
test/spec/fixtures/schema.sql

This was brought on https://github.com/PostgREST/postgrest/discussions/3035#discussioncomment-7453100. Adding a test to ensure it doesn't break.

test: query the empty string

---

CHANGELOG.md
src/PostgREST/Admin.hs
src/PostgREST/App.hs
src/PostgREST/AppState.hs
src/PostgREST/CLI.hs
src/PostgREST/Config.hs
src/PostgREST/Error.hs
test/io/test_io.py

feat: Log all internal database errors to stderr

---

CHANGELOG.md
src/PostgREST/SchemaCache.hs
test/memory/memory-tests.sh
test/spec/Feature/Query/MultipleSchemaSpec.hs
test/spec/fixtures/schema.sql

Closes https://github.com/PostgREST/postgrest/issues/3124

fix: aggregates not working for all schemas

---

CHANGELOG.md
src/PostgREST/Query/Statements.hs
test/spec/Feature/Query/CustomMediaSpec.hs
test/spec/fixtures/schema.sql

Closes https://github.com/PostgREST/postgrest/issues/3126

fix: empty row on handler function 

---

CHANGELOG.md
src/PostgREST/ApiRequest/Preferences.hs

Related to https://github.com/PostgREST/postgrest-docs/pull/733

deprecate: params=single-object preference

---

nix/tools/withTools.nix

stock curl doesn't make it easy to make many parallel requests to a single endpoint. The endpoint has to be repeated N times.
```
curl --parallel https://example.com https://example.com ..
```
Adding a config file is also possible but that makes it even more cumbersome.
This provides a wrapper for parallel curl. It's useful for testing scenarios like pool timeouts.
```
parallel-curl N https://example.com <other_args>
```

nix: add parallel-curl wrapper

---

.github/actions/setup-nix/action.yaml

ci: upgrade nix-cache-action to 5.0.1

---

CHANGELOG.md
src/PostgREST/Admin.hs
test/io/test_io.py

feat: dump schema cache through admin API

---

CHANGELOG.md
src/PostgREST/AppState.hs
test/io/big_schema.sql
test/io/test_big_schema.py

Fixes https://github.com/PostgREST/postgrest/issues/3327

fix: slow responses on schema cache reload

---

src/PostgREST/ApiRequest.hs
src/PostgREST/App.hs
src/PostgREST/Plan.hs
src/PostgREST/Query.hs
src/PostgREST/Response.hs

refactor: dry timings calculation for openapi

---

CHANGELOG.md
src/PostgREST/Response/OpenAPI.hs
test/spec/Feature/OpenApi/OpenApiSpec.hs

fix: OpenAPI now tags a FK correctly on O2O relationships

---

CHANGELOG.md
src/PostgREST/ApiRequest/Types.hs
src/PostgREST/Error.hs
test/spec/Feature/Query/RpcSpec.hs

feat: PGRST121 error messages now show the failed MESSAGE or DETAIL

---

test/io/postgrest.py

Related to https://github.com/PostgREST/postgrest/issues/3424#issuecomment-2086408801

test: flush stdout so readline doesn't hang

---

CHANGELOG.md

Update CHANGELOG after release v12.0.3. See #3443

changelog: update to 12.0.3

---

docs/conf.py
test/io/test_io.py

Patreon is always failing now as seen on https://github.com/PostgREST/postgrest/actions/runs/9144964087/job/25143395727

Fix linkcheck, extra info for io tests failure

---

CHANGELOG.md
docs/explanations/architecture.rst
postgrest.cabal
src/PostgREST/App.hs
src/PostgREST/AppState.hs
src/PostgREST/Auth.hs
src/PostgREST/Listener.hs

Linkcheck failure should be cleared after merging this PR

changelog: add architecture doc

---

docs/references/api/resource_embedding.rst
docs/references/api/tables_views.rst

docs: use "curl --get" for better readability when necessary

---

src/PostgREST/AppState.hs
src/PostgREST/Listener.hs

Brings back the the signaling/waiting between the connection pool and the Listener.
This behavior was on the previous release, but was removed on https://github.com/PostgREST/postgrest/commit/3cf565614d6529b4f691699b254fd3a680dfcda0. See https://github.com/PostgREST/postgrest/issues/3569#issuecomment-2146336484. 
Prevents the GSSAPI error shown on https://github.com/PostgREST/postgrest/issues/3569

prevent GSSAPI error between Listener and pool

---

docs/references/api/tables_views.rst

docs: wrap in double quotes the filters with reserved characters inside logical operators

---

docs/explanations/architecture.rst
docs/references/configuration.rst
docs/references/listener.rst
docs/references/observability.rst
docs/references/schema_cache.rst

Missing docs added in https://github.com/PostgREST/postgrest/pull/3582

Missing docs for v12.2.0

---

docs/references/listener.rst

Addresses https://github.com/PostgREST/postgrest/pull/3582#discussion_r1637270162.

docs: fix example of listener failure on read replicas

---

CHANGELOG.md
src/PostgREST/Plan.hs
test/spec/Feature/Query/QuerySpec.hs

fix: nested empty embeds no longer return empty values and are correctly omitted

---

README.md
docker-hub-readme.md
docs/index.rst
docs/tutorials/tut0.rst

We'll now use github discussions for support.

chore: remove links to gitter

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Migrates to new github issues templates. Also adds a feature request template.

chore: update github issue templates

---

docs/references/auth.rst

docs: add missing jwt claims and clock skew

---

src/PostgREST/App.hs
src/PostgREST/Logger.hs
src/PostgREST/Query.hs

refactor: remove IO from the Query.hs module

---

postgrest.cabal
src/PostgREST/AppState.hs
src/PostgREST/Auth.hs
src/PostgREST/Auth/JwtCache.hs
test/spec/Main.hs

refactor: move jwt caching logic to `Auth/JwtCache.hs`

---

CHANGELOG.md
src/PostgREST/Logger.hs
src/PostgREST/Observation.hs
test/io/test_io.py

feat: Log PoolRequest and PoolRequestFullfilled observations

---

src/PostgREST/Auth.hs
src/PostgREST/Error.hs

Refactor for #3600. It would be easier adding new JWT errors with this refactor.

refactor: group jwt errors

---

src/PostgREST/ApiRequest.hs
src/PostgREST/App.hs

Decouple module `SchemaCache.hs` and `ApiRequest.hs`.

refactor: decouple module SchemaCache and ApiRequest

---

test/io/test_io.py

`jwt-cache` and `server-timing` tests cleanup.

test: jwt and server-timing tests cleanup

---

docs/references/errors.rst

docs: add missing max-affected violation error

---

docs/references/observability.rst

docs: mention log-level setting in the logs section

---

src/PostgREST/Error.hs

Our current `ErrorCode` type wasn't giving us a full picture of how many different types of errors we are handling. This PR makes this explicit by including the error code type for all types of errors.
This is a small change but makes our code consistent and removes ambiguity. It also ensures that all errors use `toJsonPgrstError` to create the error json.

refactor: add pg error and custom error to ErrorCode

---

src/PostgREST/Error.hs

The old error design didn't allow us to reuse error `code`, `message` etc. With this refactor, these parts of the error body can be reused for other potential features. We need this for #3955.
Edit: With this change, proxy-status header would be simply:
```haskell
[("Proxy-Status", "PostgREST; error=" <> code err)]
```

refactor: create error body with ErrorBody typeclass

---

docs/references/api/resource_representation.rst

docs: add note that ordering of columns is not enforced

---

src/PostgREST/Error.hs
src/PostgREST/Plan.hs
src/PostgREST/Response.hs

As mentioned in [#3987 (comment)](https://github.com/PostgREST/postgrest/pull/3987#discussion_r2025379164).

refactor: separate SchemaCacheError from ApiRequestError

---

src/PostgREST/MediaType.hs
test/spec/Feature/Query/CustomMediaSpec.hs

Solves regression introduced in #4005.

fix: Fix regression that replaces an unknown media type with */*

---

CHANGELOG.md
src/PostgREST/AppState.hs
src/PostgREST/Auth.hs

Backport of https://github.com/PostgREST/postgrest/pull/3889

v12 fix: purge JWT cache asynchronously in a separate thread

---

CHANGELOG.md
src/PostgREST/MediaType.hs
test/spec/Feature/Query/CustomMediaSpec.hs

fix: regression with parameter charset=utf-8 in mediatype

---

CHANGELOG.md
src/PostgREST/MediaType.hs
test/spec/Feature/Query/CustomMediaSpec.hs

v12: fix: regression with parameter charset=utf-8 in mediatype

---

CHANGELOG.md
docs/references/observability.rst
src/PostgREST/Error.hs
src/PostgREST/Response.hs
test/io/test_io.py
test/spec/Feature/Auth/AuthSpec.hs
test/spec/Feature/OpenApi/DisabledOpenApiSpec.hs
test/spec/Feature/OpenApi/IgnorePrivOpenApiSpec.hs
test/spec/Feature/OpenApi/OpenApiSpec.hs
test/spec/Feature/OptionsSpec.hs
test/spec/Feature/Query/CustomMediaSpec.hs
test/spec/Feature/Query/DeleteSpec.hs
test/spec/Feature/Query/EmbedDisambiguationSpec.hs
test/spec/Feature/Query/ErrorSpec.hs
test/spec/Feature/Query/InsertSpec.hs
test/spec/Feature/Query/PlanSpec.hs
test/spec/Feature/Query/QuerySpec.hs
test/spec/Feature/Query/RangeSpec.hs
test/spec/Feature/Query/RpcSpec.hs
test/spec/Feature/Query/UpdateSpec.hs
test/spec/Feature/RollbackSpec.hs
test/spec/Feature/RpcPreRequestGucsSpec.hs
test/spec/SpecHelper.hs

feat: add content-length header

---

CHANGELOG.md
src/PostgREST/Plan.hs
src/PostgREST/Plan/CallPlan.hs
src/PostgREST/Query/QueryBuilder.hs
test/spec/Feature/Query/RpcSpec.hs

fix: filter on unselected columns in a table-valued function

---

docs/integrations/jwt_gen.rst
docs/postgrest.dict

docs: add example to generate JWTs using openssl

---

docs/references/auth.rst
docs/references/configuration.rst
postgrest.cabal
src/PostgREST/Auth.hs
test/spec/Feature/Auth/AudienceJwtSecretSpec.hs
test/spec/Feature/Auth/AuthSpec.hs
test/spec/Main.hs
test/spec/SpecHelper.hs

Fixes regression and adds missing tests.

fix: not handling array values in `aud` claim correctly

---

CHANGELOG.md
src/PostgREST/Error.hs
test/io/fixtures.yaml
test/io/test_io.py

fix: jwt error return status 400 for invalid role

---

test/spec/Feature/Query/ErrorSpec.hs
test/spec/Feature/Query/RpcSpec.hs
test/spec/fixtures/schema.sql

Regression test for fix done on #4070.

test: add test for duplicate entries in pg_description with same OID

---

docs/references/api/preferences.rst
test/spec/Feature/Query/PreferencesSpec.hs
test/spec/fixtures/schema.sql

test-and-docs: add test and docs for max-affected preference with rpc

---

docs/references/auth.rst

Docs for JWK kid parameter validation

---

CHANGELOG.md
src/PostgREST/AppState.hs
src/PostgREST/CLI.hs
src/PostgREST/Metrics.hs
src/PostgREST/Observation.hs
test/io/test_io.py

feat: log `db-schemas` and `db-extra-search-path` in schema cache load error

---

CHANGELOG.md
src/PostgREST/Auth.hs
src/PostgREST/Error.hs
test/io/test_io.py

Improving error details as issues came up as mentioned in #4048.

feat: improve error details of PGRST301 error

---

CHANGELOG.md
src/PostgREST/Query/QueryBuilder.hs
test/spec/Feature/Query/SpreadQueriesSpec.hs

fix: empty spread embeddings return unexpected SQL error

---

.github/workflows/test.yaml
nix/tools/cabalTools.nix
nix/tools/devTools.nix
nix/tools/tests.nix

Resolves #4206
@steve-chavez can you try whether that improves it for you?

nix: avoid updating cabal on every run

---

CHANGELOG.md

Merge two `### Changed` sections into one. While at it, explained the recent change log entry of #4084 so it's more end-user friendly.

chore: correct recent change log entry

---

CHANGELOG.md
src/PostgREST/Response/OpenAPI.hs
test/spec/Feature/OpenApi/OpenApiSpec.hs

fix: empty enum in 'preferParams' openAPI parameter

---

CHANGELOG.md
src/PostgREST/ApiRequest.hs
src/PostgREST/Auth.hs
src/PostgREST/Error.hs
test/io/test_io.py
test/spec/Feature/Query/MultipleSchemaSpec.hs

According to the convo in https://github.com/PostgREST/postgrest/pull/4321#issuecomment-3282383366.

Backport error message improvements to v13

---

CHANGELOG.md
src/PostgREST/ApiRequest/Preferences.hs
src/PostgREST/Logger.hs
src/PostgREST/Plan.hs
src/PostgREST/Query.hs
src/PostgREST/Query/PreQuery.hs
src/PostgREST/Response.hs
test/io/test_io.py

Fixes https://github.com/PostgREST/postgrest/issues/4319

fix: not logging explain query for estimated count

---

CHANGELOG.md
src/PostgREST/Logger.hs
test/io/__snapshots__/test_cli/test_schema_cache_snapshot[dbRoutines].yaml
test/io/fixtures.sql
test/io/test_io.py
test/spec/fixtures/schema.sql

Addresses the first item on https://github.com/PostgREST/postgrest/issues/3934

fix: not logging tx variables and pre-request
