PostgREST/postgrest

src/Config.hs, test/Feature/CorsSpec.hs
Usefull if we want to redirect to show view (in ng-admin for instance) after creating a new entity.
=> Add 'Location' to exposed headers

src/Main.hs
This makes optparse-applicative show the long version of help output.
Its default behavior is not to do this since the showHelpOnError
setting defaults to False.  This turns it on.
=> Show long help output with defaults on usage errors

CHANGELOG.md, postgrest.cabal, src/PgQuery.hs, test/Feature/QuerySpec.hs, test/Feature/StructureSpec.hs, test/SpecHelper.hs, test/fixtures/schema.sql
This feature allows you to query `/table?col->>prop=eq.value` or path deeper into the json with `/table?col->foo->bar->>prop=eq.value`. It fixes #118
=> Filter results using properties in a jsonb column

src/PgStructure.hs
Without it, the following error occurs:
```
src/PgStructure.hs:88:5:
Non type-variable argument
in the constraint: Data.String.Conversions.ConvertibleStrings
Text k
(Use FlexibleContexts to permit this)
When checking that ‘addFK’ has the inferred type
addFK :: forall k.
(Ord k, Data.String.Conversions.ConvertibleStrings Text k) =>
Map.Map k ForeignKey -> Column -> Column
In an equation for ‘columns’:
columns table
= do { cols <- H.listEx
$ (\ _1 _2
-> Hasql.Backend.Stmt
"select info.table_schema as schema, info.table_name as table_name, info.column_name as name, info.ordinal_position as position, info.is_nullable as nullable, info.data_type as col_type, info.is_updatable as updatable, info.character_maximum_length as max_len, info.numeric_precision as precision, info.column_default as …
```
=> GHC 7.10.1 support

postgrest.cabal, src/App.hs, src/Auth.hs, src/Config.hs, src/Main.hs, src/Middleware.hs, src/PgQuery.hs, src/PgStructure.hs, src/RangeQuery.hs, test/Feature/AuthSpec.hs, test/Feature/StructureSpec.hs, test/SpecHelper.hs, test/TestTypes.hs
Hi guys,
This PR brings support for logging in through JSON Web Tokens.
Should close #163.
We have a new dependency on `jwt`
There is a new option `--jwt-secret secret` which can be used to change the secret used to encryp and decrypt the JWT
I've added a new route on `POST /postgrest/sessions` which accept `id` and `pass` and returns a JSON Web Token:
{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW5pc3RyYXRvciIsImlkIjoiZnJhbXAifQ.qKwM3TFSrK9eLZ2OvR9p1yMWwx32QoMgw2KANgBGtv4"
}
Or:
{
"message": "Failed authentication."
}
Adding a 
Authorization:Bearer JWT_TOKEN
to a request (with a valid JWT token of course) will authenticate the user.
I've made a couple of changes on how the config is passed across the application: now `authenticated` and `app` have full access to …
=> JWT support

src/PostgREST/PgQuery.hs, test/Feature/QuerySpec.hs, test/Feature/StructureSpec.hs, test/fixtures/schema.sql
Implements the @@ with a to_tsquery wrapped arount the input value, so we can use some of PostgreSQL full text search cababilities. Although is a very limited support it seems to be the the least intrusive way to implement and have at least some functionality.
Maybe in the future the unknownLiteral value could be wrapped with an arbitrary function defined by the query.
=> Tsearch operator

src/PostgREST/App.hs, src/PostgREST/Auth.hs, src/PostgREST/Middleware.hs, test/Feature/InsertSpec.hs, test/Unit/PgQuerySpec.hx, test/fixtures/schema.sql
As per title, with this PR a `user_vars.user_id` containing the user's `id` will be set.
The variable is scoped on the [connection](http://postgresql.nabble.com/can-I-define-own-variables-td1889836.html).
It can then be used in triggers with:
SELECT current_setting('user_vars.user_id');
The fixture and test I added should be quite easy to follow.
Should close #123
=> User_id support (via user_vars)

src/PostgREST/PgStructure.hs, test/Feature/StructureSpec.hs, test/Unit/PgStructureSpec.hx, test/fixtures/schema.sql
On important remark is that as far as I've tested the current code reports insertable as false in these cases but still sends the INSERT commands. But I believe that making the "insertable" field in postgrest true in these cases makes it more consistent with the actual behaviour.
I also converted the value to boolean in PostgreSQL for convenience.
=> Changes the insertable to true in views that are insertable through triggers [fixes #206]

src/PostgREST/PgStructure.hs
I've just applied the same solution to boolean conversion from the information schema which I have used in my previous PR thus eliminating the need for a haskell toBool function.
=> Removes toBool function as we now cast the 'YES/NO' values to boolean in PostgreSQL's queries

src/PostgREST/App.hs, src/PostgREST/PgQuery.hs, test/Feature/InsertSpec.hs, test/Feature/QuerySpec.hs, test/fixtures/schema.sql
This PR allows the use of [computed columns](http://www.postgresql.org/docs/9.4/interactive/xfunc-sql.html#XFUNC-SQL-COMPOSITE-FUNCTIONS) as filters in GET and PATCH calls without including these fields in the view being queried.
I know that it's not a super elegant solution but it's the least invasive I could think of.
With the current code to query for any function applied to the rows I need to include this function as a field in the view. Sometimes this is undesirable, for these columns can be quite large and I may want to keep a leaner response body.
The case I ran into was filtering by a concatenation of text fields like:
```sql
SELECT * 
FROM projects 
WHERE name || ' ' || author || ' ' || description ILIKE '%search string%';
```
So instead of modelling the above concatenation as a …
=> Qualifies columns of WHERE clauses so we can use computed columns as filters

src/PostgREST/Main.hs
This appears to enable capturing of log messages with "postgrest >> log"
=> Enable log capture if stdout is not a terminal (issue #229)

CHANGELOG.md, src/PostgREST/PgQuery.hs, test/Feature/QuerySpec.hs, test/Feature/StructureSpec.hs, test/fixtures/schema.sql
Just adds a test case and prefixes the uses of the count function with pg_catalog.
=> Fixes error code 42803 when trying to query a view with a column named count

CHANGELOG.md, src/PostgREST/PgStructure.hs, test/Feature/StructureSpec.hs, test/fixtures/schema.sql
Still does not implement the OPTIONS for materialized views, but I figured that could go on another PR.
A nice side effect of using the pg_catalog is:
```
Planning time: 0.721 ms
Execution time: 0.655 ms
```
Whereas the previous implementation using information_schema in the same system was:
```
Planning time: 2.063 ms
Execution time: 1.245 ms
```
=> Adds materialized views to list of relations in GET / [#242]

src/PostgREST/App.hs, src/PostgREST/PgQuery.hs, test/Feature/QuerySpec.hs, test/SpecHelper.hs
This is a draft, for I still need to make the accept headers work with text/csv + the API versioning.
But I'd like to get some early feedback on the code so far :D
This should fix issue #226
=> Get CSV response

src/PostgREST/PgQuery.hs, test/Feature/InsertSpec.hs, test/Feature/QuerySpec.hs
This adds a "NOT IN" query to the postgrest routing.
In #173 I was asking for an api change to allow any route to be negated with a NOT. This small change handles my current use case. 
If it's acceptable to handle each negative route by adding an opCode to the case statement as I did here then I'm more than happy to add them all to this, or another PR.
=> NOT IN queries

src/PostgREST/App.hs, src/PostgREST/PgQuery.hs, src/PostgREST/PgStructure.hs, test/Feature/QuerySpec.hs, test/fixtures/schema.sql
Allow client to invoke stored procedures by POSTing to `/rpc/proc_name` with named arguments as keys in the JSON request body.
This is a work in progress. I created a pull request as a place for conversation as the feature evolves.
=> Expose stored procedures

src/PostgREST/PgQuery.hs, test/Feature/QuerySpec.hs
I thought that the original proposal in #173 is a great addition and can give us a lot of functionality for a little extra code (we could even remove some hard-coded not operators in the future).
Besides, it seems to fit the convention of parameters very well, and since not has a higher priority than ```AND/OR``` we don't even need to add extra parenthesis.
=> Adds not as a keyword that can optionally be prepended to any operator in a parameter value [fix #173]

CHANGELOG.md, src/PostgREST/Auth.hs, src/PostgREST/Main.hs, src/PostgREST/Middleware.hs, test/Feature/AuthSpec.hs, test/SpecHelper.hs, test/fixtures/schema.sql
When a user auths we `set role` on a connection acquired from the pool. In the past when a db error happens it aborts our code and never resets the role back to the authenticator. This caused the dreaded `"permission denied for relation auth"` message.
Now I `set local role` inside a transaction. Hopefully using a transaction for each request will not introduce a performance hit. I'm using the weakest transaction isolation level I can, [read uncommitted](https://en.wikipedia.org/wiki/Isolation_(database_systems)#Read_uncommitted).
- Fixes #264 
- Fixes #164
=> Allow continued auth access after db errors

src/PostgREST/App.hs, src/PostgREST/PgQuery.hs, test/Feature/QuerySpec.hs, test/Feature/StructureSpec.hs, test/SpecHelper.hs, test/fixtures/schema.sql
Additional parameter (for GET requests) that provides the ability to shape the response
At it's core, it is changing the query from "select * " to "select col1, col2" if the parameter is present
Suggestion as to the code style are welcome
=> Support for &select=col1,col2,col3 as suggested in issue #227

CHANGELOG.md, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/PgQuery.hs, test/Feature/RangeSpec.hs
Implements ```Prefer``` header ```count=none``` as discussed in #273
This is already incredibly useful for us even without the ```estimated``` option.
Also changed all ```lookupHeaders "Prefer"``` for ```hasPrefer``` since the this header can have multiple occurrences.
=> Prefer count none

src/PostgREST/App.hs, test/Feature/RangeSpec.hs
The where clause should be discarded when count=none.
This was generating a database run time error for we did not have a test case for filters with count=none, so I modified one of the test cases I've included in the previous PR
=> Fix count=none when we have filters

postgrest.cabal, src/PostgREST/Config.hs, src/PostgREST/Main.hs
I tried to better encapsulate the config functionality.
This PR sets a default password as empty string, which renders unnecessary the parameter --db-pass for development environments where the authentication method is usually done without passwords.
I also changed the Config module to use an explicit list of exported module as it seems that in this way we have a better self-documented code and gives us more confidence to refactor private members.
I was also thinking of documenting the code with haddock, any opinions on this topic?
=> Moves all config related code to PostgREST.Config module and sets default db-pass

src/PostgREST/Config.hs, src/PostgREST/PgQuery.hs, src/PostgREST/PgStructure.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs
It requires pg to be 9.3 because of the lateral join.
If someone knows how to rewrite the query without the lateral join it can go down again back to 9.2
=> Fix for #302 (supporting compound foreign keys in relations)

CHANGELOG.md, README.md, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/Main.hs, src/PostgREST/Middleware.hs, test/SpecHelper.hs
I propose we remove the `--db-x` options for v3. First because they are ugly, second because the Postgres [connection string format](http://www.postgresql.org/docs/9.4/static/libpq-connect.html#LIBPQ-CONNSTRING) is much more expressive. It allows for multiple styles and more configuration options (`connect_timeout`, `application_name`) than we could ever logically allow.
The new syntax would be:
```bash
postgrest postgres://authenticator@localhost:5432/database -a anonymous -S public…
```
For those who store all the information in separate variables the syntax is also simpler for them too:
```bash
postgrest postgres://$DB_USER:$DB_PASS@$DB_HOST:$DB_PORT/$DB_NAME…
```
The one point of difficulty is that doing so removes `configDbUser` which is used as the PostgREST authenticator in the old …
=> Use postgres connection string instead of 5+ options

postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Main.hs, src/PostgREST/Middleware.hs
This prints out a full error message on startup if there are problems connecting to the database or if postgrest issues a bad query.
It should help with debugging problems. Only thing I'm not totally happy about is that it outputs the results as a pretty-printed JSON object. This output style doesn't match the usual logging convention which is line based with timestamps.
=> Clearer errors

src/PostgREST/App.hs
Per Nikita's suggestion https://github.com/nikita-volkov/hasql-postgres/issues/25 remove unnecessary string conversions
=> avoid ByteString -> Text -> ByteString converstion of the response body

stack.yaml
Also adds new hspec to custom build plan (since 2.2.0) is not included in Stackage 3.10.
The 2.2.0 version is already in the Stockage Nightly, so we will be able to remove then from the custom plan as soon as the next version is released.
=> Update stack resolver

CHANGELOG.md, src/PostgREST/PgQuery.hs, test/Feature/QuerySpec.hs, test/fixtures/schema.sql
Our queries usually return a row even when the results is empty.
The /rpc endpoints are an exception, they can actually return an empty row set, and this triggers a 500 error.
I just coalesced the null result to and empty array in the array_to_json call.
=> Fixes 500 when set returning function returns an empty row set [fix #332]

src/PostgREST/PgStructure.hs
Fixes it when the jwt_claims type is defined in a non-default schema
=> Encode JWT when proc return types end in jwt_claims

docs/install/server.md
Modify the server installation guide to include steps for installation
using Hombrew on OS X. Also, correct typo in command line
arguments in the same document.
=> Add documentation for installing via Homebrew

CHANGELOG.md, src/PostgREST/Config.hs, src/PostgREST/Main.hs, src/PostgREST/MainTest.hs, src/PostgREST/Middleware.hs, test/SpecHelper.hs
I was recently doing research and came across [this](https://github.com/interagent/http-api-design#require-secure-connections). I'll quote the relevant sections here:
> ### Require Secure Connections
>
> Require secure connections with TLS to access the API, without exception. It’s not worth trying to figure out or explain when it is OK to use TLS and when it’s not. Just require TLS for everything.
>
> Ideally, simply reject any non-TLS requests by not responding to requests for http or port 80 to avoid any insecure data exchange. In environments where this is not possible, respond with `403 Forbidden`.
>
> **Redirects are discouraged** since they allow sloppy/bad client behaviour without providing any clear gain. Clients that rely on redirects double up on server traffic and render TLS …
=> Do not redirect insecure requests

CHANGELOG.md, src/PostgREST/Auth.hs, src/PostgREST/Main.hs, src/PostgREST/Middleware.hs, test/Feature/AuthSpec.hs, test/SpecHelper.hs, test/fixtures/schema.sql
In order to implement a secure refresh token pattern (I assume Auth0 uses this) with JWT, we need to ensure that tokens are rejected if they have expired. Therefore, these changes.
There is one breaking change, whereas incorrectly formatted JWTs once just fell through (a 404 was returned), now a bad JWT will returns a 400 with the message "Invalid JWT".
=> Ensure JWT expires

CHANGELOG.md, src/PostgREST/App.hs, test/Feature/QuerySpec.hs
Use `Prefer: plurality=singular` to select single objects.
=> Implement single route selection

CHANGELOG.md, circle.yml, src/PostgREST/Main.hs, src/PostgREST/Middleware.hs, test/SpecHelper.hs
There was a big security hole where the server was not fetching the correct date. This PR fixes that. The issue involved the `unsafePerformIO` call, I don't know why I just know that when I removed it things worked 😊 (see more at #344, [this](https://github.com/begriffs/postgrest/pull/344#discussion-diff-44341727) discussion specifically @begriffs).
Closes #391.
And I promise, no bugs 😊 (#355).
=> Fix time fetch on initialization

docs/examples/users.md, mkdocs.yml
Writing this as a separate example which I will follow up with a short example for building a multi-tenant blogging API. That way the make a blog example won't be many pages long. I want it to look inviting.
Anyway here is the progress of the login management docs.
=> Document how to build username/pw auth on top of jwt

CHANGELOG.md, docs/api/reading.md, src/PostgREST/QueryBuilder.hs, test/Feature/QuerySpec.hs, test/fixtures/schema.sql
In #221 I forgot to add ORDER BY support, this PR fixes that oversight, making computed columns even more useful.
=> Order by computed column

CHANGELOG.md, docs/install/server.md, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/RangeQuery.hs, test/Feature/AuthSpec.hs, test/Feature/CorsSpec.hs, test/Feature/DeleteSpec.hs, test/Feature/InsertSpec.hs, test/Feature/QueryLimitedSpec.hs, test/Feature/QuerySpec.hs, test/Feature/RangeSpec.hs, test/Feature/StructureSpec.hs, test/SpecHelper.hs
Add command line option to limit the number of rows ever returned by any read request. This does not apply to inserting rows with `Prefer: return=representation`. All those kind of rows would be returned possibly in excess of the read row limit.
Also `rangeParse` now always returns a range, no more Maybe. Where it would have returned maybe before it now returns the unbounded range starting from 0. This simplifies other parts of the code.
=> Add --max-rows option

CHANGELOG.md, src/PostgREST/DbStructure.hs
This issue might also be a problem for functions like allPrimaryKeys, allColumns because they also use information_schema ... this needs investigation.
While debugging this i was confronted with the fact i could not clearly see where the problem is because the the old way of getting all the relations from the query was changed to getting the info in 2 stages.
I am planning on changing this in the future so that the query returns all the relations directly and eliminate the need  for the functions in this line
```
let rels' = (addManyToManyRelations . raiseRelations schema syns . addParentRelations . addSynonymousRelations syns) rels
```
so i am going to post the current query here to have it documented
```
/*
-- CTE to get the original columns reference in views
-- it returns results in …
```
=> Detect relations event when authenticator does not have rights to intermediate tables

CHANGELOG.md, postgrest.cabal, src/PostgREST/Main.hs
When I interrupt the program with ctrl-c I see it print out the message, "Releasing connection pool...". Other than that I'm not sure if it changes the behavior of the program. To manually test I run this command in another terminal:
```bash
watch "psql -d postgrest_test -c 'SELECT sum(numbackends) FROM pg_stat_database;'" 
```
When PostgREST is not running the count is 1 because of psql itself. Once the server starts the count goes to 2. When I ctrl-c the server it goes back down to 1. The decreasing to 1 happens with or without the code in this pull request though.
@monemihir can you check if this pull request helps? I'm not sure how else to test it.
=> Release db connections on sigint

CHANGELOG.md, src/PostgREST/QueryBuilder.hs, test/Feature/InsertSpec.hs, test/Feature/QuerySpec.hs, test/fixtures/data.sql, test/fixtures/schema.sql
Include records with missing parents and remove CTE related to parent relations.
Return [] instead of null for records that do not have children.
=> Fix #396 include records with missing parents and return [] instead of  null for missing children

docs/api/reading.md
One more sample query which is probably one of most useful ones in real life (by default, DESC ordering leads to NULLS FIRST option, this is not so clear for beginners), showing how to combine ordering direction and NULLS *** for the same column.
=> ordering with DESC & NULLS LAST together

postgrest.cabal, test/Main.hs, test/SpecHelper.hs
The error was in specDbStructure
it's parameter is the name of the schema, you were calling it with the name of the db, strange how only this test was failing :)
I also changed the main, the previous version was running tests separately, now they are ran as a single one (the way it was before).
Please merge your branch into master and close my previous PR (since it's commit is included in this branch)
=> Fix failing test after test structure optimization

CHANGELOG.md, src/PostgREST/QueryBuilder.hs
While I was knocking around the PostgREST codebase I wanted to knock out some of the easy issues. There were two I found. It might be nice to have a tag to denote these issues, anyway this should close #388. From what I know quoting everything shouldn't be a problem, maybe @diogob should weigh in?
=> `pgFmtIdent` always quotes #388

CHANGELOG.md, src/PostgREST/Config.hs
This was the second issue. Closes #389 and ends the versioning legacy ☺️
Except for all the API devs that are smart and still version their schemas…
=> Change default schema #389

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/QueryBuilder.hs
For now i went with keeping the "pg_source" CTE and inlining the count query.
Besides counting, it's also used when dealing with CSV.
It's not the final version of the code (i want to remove the wrapQuery... functions, at this point i think they are in the way, it made sense when it was only one) but i wanted to PR this so that @diogob can check the performance of the generated query. @diogob please also look at the performance when the requested response needs to be in CSV format
If the query is good, then i will clean up a bit and do another commit here.
=> #414 revert to separate count query

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/QueryBuilder.hs, test/Feature/InsertSpec.hs, test/Feature/StructureSpec.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
This PR adds the possibility of insterting records in tables with no SELECT privileges if you supply the header
```
Prefer: return=none
```
I don't really like the idea of an extra header but i don't see a way around this. Also this "feature" made the code a bit dirtier, especially the "createWriteStatement"
Let's discuss the issue like so:
Is the extra header the right way to go?
yes -> can the code that implements it be nicer?
no -> how do we put an "IF" around the "RETURNING *" in SQL ?
=> Fix #399 insert records in tables with no SELECT privileges

CHANGELOG.md, docs/api/reading.md, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/DeleteSpec.hs, test/Feature/QuerySpec.hs
Enables selection by column in a much more concise way for the new `3.x` codebase. I realize this pull request has historically been a source of contention, so if you don't want to merge immediately I understand. I'm going to use this in my application and then report back once I'm fully confident that this feature should be in PostgREST.
This request also includes the capability to embed rows by column without an `_id`, the row is also embedded with the sans `_id` name. This makes it more semantic and fixes the problem for some where say `author_id` could be both an integer and an object. It is the last resort option if no other relations could be found.
Oh, this PR also fixes a small capitalization bug ([see here](https://github.com/calebmer/postgrest/commit/68034f6f5ae640bd786f188ce39ef …
=> Enable selection by column

test/Feature/InsertSpec.hs, test/fixtures/data.sql, test/fixtures/roles.sql
What was going on is this
Range spec was expecting the "menagerie" table to be empty, but resetDb was not doing that (not all tables in fixture had truncate statements).
The reason it worked before is that because authenticator role inherited all the privileges from anonymous, it had the right to "clearTable" that was being executed after each test in "InsertSpec"
=> Fix errors in tests when setting authenticator to noinherit #407

docs/examples/start.md
Said 'restuls', should be 'results'
=> examples/start.md: Fixed typo

CHANGELOG.md, src/PostgREST/QueryBuilder.hs, test/Feature/QuerySpec.hs, test/Feature/StructureSpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
This is a simple bug fix. As I camel case my APIs PostgREST was generating bad queries which look like this:
```sql
SELECT
"api"."posts".*,
row_to_json(postTopics.*) AS "postTopic"
FROM
"api"."posts"
LEFT OUTER JOIN (
SELECT
"api"."postTopics".*
FROM
"api"."postTopics"
) AS postTopics
ON
"postTopics"."id" = "posts"."postTopicId";
```
Note how some of the `postTopics` are not quoted. This is because those values are not run through `pgFmtIdent`. This caused an error as `posttopics` and `"postTopics"` do not match. This is a quick PR to fix that.
=> Consistent read query escaping

docs/examples/python-requests-jwt.md, docs/install/ecosystem.md, mkdocs.yml
As discussed with @begriffs, this example documents:
* logging into a PostgREST API using python-requests
* obtain token from response
* use token auth with requests-jwt
* use Range header for pagination of results
=> Document python requests jwt

docs/admin/security.md
This was confusing when I got started with the docs. Above in the docs you're using `foo` as the authenticator role. Later, you're giving the example of using the `authenticator` role for this purpose. When using CREATE ROLE, the role will not have the LOGIN permission and starting the server with `postgrest postgres://authenticator@localhost:5432/mydb --anonymous anon` will result in `FATAL: role "authenticator" is not permitted to log in`. The docs should either use CREATE USER (like you door set LOGIN when using CREATE ROLE, as I understand it.
=> Set login permission for authenticator role

src/PostgREST/App.hs, src/PostgREST/DbStructure.hs
So the history of this is as follows:
In the beginning the / request used to go to the db (like in this pr).
The we started caching the db structure (along the info of who has access to what) and serving the response using that.
Then during discussions about how to model "users/auth" we figured that when someone wants to use 1 user = 1 role, this way of doing things (caching who has access to what) so we started to migrate back and at the same time there was some dbstructure refactoring and things got mixed up.
PS: @begriffs before merging this, can you test in 3.0.3 my suspicion that this bug only appears when the "grant" command is executed during the time postgrest is running and the bug presents itself but when you restart postgrest, it works again. If that is correct then the docs …
=> fix #453 by sending the request to the db (instead of using the cached data)

docs/install/server.md
This is a dependency of postgresql-libpq-0.9.1.1, which results in
a failure when missing during stack build.
Closes #463.
=> Add step to install libpq-dev when building from source on Ubuntu

docs/examples/users.md
No need to use the uuid-ossp extension
From http://www.postgresql.org/docs/current/static/uuid-ossp.html :
> Note: If you only need randomly-generated (version 4) UUIDs, consider using the gen_random_uuid() function from the pgcrypto module instead.
`gen_random_uuid` was only added in to postgres in version 9.4. I'm not sure what version the docs are meant to be compatible with?
=> docs/examples/users.md: pgcrypto includes uuidv4 generation

docs/examples/external_auth.md
In line 126 the endpoint url is api_token. Therefore it should be the same in line 178.
=> Rename endpoint for consistent endpoint names

circle.yml, postgrest.cabal, src/PostgREST/App.hs, stack.yaml, test/SpecHelper.hs
The new config has a few benefits
* Builds like we do in development
* Removes helpers like hlint and packdeps from the cabal file and into the circle config
* Newer stack resolver
* More kinds of ghc warnings
* Added checks for
* cabal file warnings
* haddock coverage
* problems creating hackage tarball
=> Switch to Stack on CircleCI

docs/install/server.md
I expanded the section 'Running the Server' in the documentation.
Based on this comment:
https://github.com/begriffs/postgrest/issues/169#issuecomment-177031035
Related issue: #169
=> Explain how to connect without a password through Unix socket

CHANGELOG.md, circle.yml, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, test/Feature/QuerySpec.hs
Fixes #481
Eventually we will allow GET requests for non-volatile functions but not yet. Note that this will also issue a 405 for OPTIONS on an rpc endpoint. Implementing OPTIONS is another todo.
=> Issue http 405 for anything but POST on RPC

CHANGELOG.md, docs/install/server.md, src/PostgREST/Config.hs, test/SpecHelper.hs
Several people have been confused about which command line arguments are required to run postgrest. This pull request changes the usage message slightly to hopefully make it clear. The new message looks like this:
```
$ postgrest
Missing: DB_URL (-a|--anonymous ROLE)
Usage: postgrest DB_URL [-p|--port PORT] (-a|--anonymous ROLE)
[-s|--schema NAME] [-j|--jwt-secret SECRET] [-o|--pool COUNT]
[-m|--max-rows COUNT]
PostgREST 0.3.0.3 / create a REST API to an existing Postgres database
Available options:
-h,--help                Show this help text
DB_URL                   (REQUIRED) database connection string
-p,--port PORT           port number on which to run HTTP
server (default: 3000)
-a,--anonymous ROLE      (REQUIRED) postgres role to use for non-authenticated
requests
-s,--schema NAME …
```
=> Adjust usage message to indicate required arguments

circle.yml
For those wishing to use postgrest as a library
=> Ensure plain cabal can determine a build plan

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/Main.hs, src/PostgREST/QueryBuilder.hs, test/Feature/QuerySpec.hs, test/Feature/RangeSpec.hs
I believe this adds consistency for a very small cost.
Using the same mechanism to paginate the result of procedure calls makes it easier to reuse front end pagination code.
=> Apply range headers to rpc

docs/examples/users.md, docs/install/server.md
* Do not build under `sudo` (which fails).
* Use `gen_random_uuid()` instead of `uuid_generate_v4()` in example.
=> Minor changes in documentation

CHANGELOG.md, Dockerfile, src/PostgREST/Main.hs
Without exec the `postgrest` process is not run with PID 1 (it
is a child process of the shell that starts it). This means
signals send to the docker (like `docker stop` or ^C) will
not be handled correctly.
This commit adds `exec` to resolve this problem, as per the
recommendation in the Dockerfile documentation:
<https://docs.docker.com/engine/reference/builder/#shell-form-entrypoint-example>
=> Use `CMD exec` in Dockerfile

docs/install/server.md
Just fixing a typo in the docs where it lists -p twice instead of -p and -o
=> Fix typo-d flag in the installation docs.

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/QueryBuilder.hs, test/Feature/AuthSpec.hs, test/Feature/InsertSpec.hs, test/Feature/QuerySpec.hs
Fixes #516
It seems like the interpolated strings are safe in the case when return-type polymorphism to the `Text` type causes `[qc| ... ]` to preserved unicode. Because interpolated strings are pleasant to read I've left them in but annotated all occurrences with `:: Text`. On one hand it's kind of touchy because future uses of interpolated strings without the Text annotation will cause problems, we have to be vigilant. On the other this PR adds tests that the operations of insert, update, and procedure call work with Unicode so it protects against regressions in these operations.
=> Preserve unicode in requests and responses

postgrest.cabal, test/Feature/UnicodeSpec.hs, test/Main.hs, test/SpecHelper.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
Test (suggested by @ruslantalpa) to ensure that non-English table/schema names are accessible.
I verified that it fails when cherry-picked onto v0.3.1.0:
```
status mismatch:
expected: 200
but got:  404
body mismatch:
expected: []
but got:  {"hint":null,"details":null,"code":"42P01","message":"relation \"*3*.EH'1/\" does not exist"}
```
=> Regression test for read/write unicode table names

src/PostgREST/Config.hs
This allows to see the corruption of binary secrets,
e.g. using --jwt-secret "$(openssl rand 4)" to test
with a random short secret.
Related issue:
https://github.com/begriffs/postgrest/issues/495
=> Output JWT secret before and after Data.String.Conversions (cs)

CHANGELOG.md, src/PostgREST/Auth.hs, src/PostgREST/Middleware.hs
I verified in the sql logs that this fixes the order of `set local` statements. From the outside there is no change of behavior so I don't know what regression test I could add.
=> Set role only once, and set it before other GUC vars

CHANGELOG.md, docs/api/reading.md, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Main.hs, test/Main.hs
Fixes #475
I manually verified this works, but it's hard to think how to add an automated test.
=> Reload schema definition on SIGHUP

CHANGELOG.md, docs/api/reading.md, src/PostgREST/App.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs, test/fixtures/schema.sql
With this PR now you can do this
`/projects?id=eq.1&select=myId:id, name, project_client:client_id{*}, project_tasks:tasks{id, name}`
to get this type of output
```
{
"myId":1,
"name":"Windows 7",
"project_client":{
"id":1,
"name":"Microsoft"
},
"project_tasks":[
{
"id":1,
"name":"Design w7"
},
{
"id":2,
"name":"Code w7"
}
]
}
```
This can also close #310
=> Ability to rename columns/nodes in the output and support "-" in column names

src/PostgREST/Main.hs
A small change in Main.hs to fix the Windows build. I moved Data.IORef outside of the block of code covered by `ifndef mingw32_HOST_OS` and deleted line 14, `Control.Monad.IO.Class` because that generated a warning about the import being redundant and the warning was treated as an error.
=> Fix Windows build issue 589

CHANGELOG.md, src/PostgREST/QueryBuilder.hs, test/Feature/QuerySpec.hs, test/Feature/StructureSpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
This type of query was generating a bad sql
`/orders?id=eq.1&select=id, name, billing_address_id{id, name}, shipping_address_id{id, name}`
The PR fixes that
=> Fix include entities from the same parent table using two different foreign keys

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/Auth.hs, src/PostgREST/Error.hs, src/PostgREST/Middleware.hs, test/Feature/AuthSpec.hs, test/Feature/StructureSpec.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
When PostgreSQL returns code `42501` for insufficient privilege we now return an access denied status code rather than a 404. If the request did not provide a JWT token with role claim then we return 401 Unauthorized with a `WWW-Authenticate` header. When the request does have a JWT with role then we return 403 Forbidden.
Fixes #584
As decided in the referenced issue we are changing the behavior unconditionally, no need for a special command-line flag.
=> Return proper 401/403 when access denied

CHANGELOG.md, src/PostgREST/ApiRequest.hs, test/Feature/InsertSpec.hs
Allows inserts or RPC calls via HTML forms like
```html
<form method="post" action="https://myapi.com/people">
<input type="text" name="fullname" />
<input type="text" name="dob" />
<input type="submit" value="Create New">
</form>
```
=> Accept POST requests from HTML forms

CHANGELOG.md, docs/api/reading.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Parsers.hs, test/Feature/QuerySpec.hs
like so
`/projects?select=id,name,tasks{id,name}&order=id.asc&tasks.order=name.ask`
=> Ability to order embedded items (closes #509)

src/PostgREST/Auth.hs, src/PostgREST/Middleware.hs
It's a tiny refactor but I believe the code is better like this.
Before this PR `jwtClaims` was returning a Right value in some invalid JWT cases, so we had to double check in our `Middleware` using a clumsy `if`.
It makes more sense to always return a `Left` value in error cases.
The PR also improves readability as the case for empty JWTs is now handled separately.
=> jwtClaims should always return Left for invalid JWT

postgrest.cabal, src/PostgREST/Auth.hs
We don't need the whole Lens library. The difference in compilation time is minimal though, but if you guys don't think it's worth changing I totally understand.
Compiling from scratch with lens:
Compiling from scratch with microlens:
=> Replace lens dependency for microlens

src/PostgREST/App.hs, src/PostgREST/QueryBuilder.hs, test/Feature/InsertSpec.hs
Possible after bug fix in a Hasql that we picked up with the new
dependency bounds in #606.
=> Simplify serialization of location header

CHANGELOG.md, postgrest.cabal
=> Run GC every 2s rather than 0.3s

CHANGELOG.md, docs/api/reading.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/RangeQuery.hs, src/PostgREST/Types.hs, test/Feature/QueryLimitedSpec.hs, test/Feature/RangeSpec.hs, test/SpecHelper.hs
This PR allows limiting embedded items and also enforces globally `--max-rows` setting.
In addition, it's possible now to specify the top level limit/range by using `&limit` and `&offset` (but Range header overrides them).
Just like for ordering, you specify the limit using `tree.path.limit=10`, however `offset` can only be specified for the top level (it does not make sense for the embedded items)
The code still needs a lot of cleanup (mainly because i don't fully understand the Range datatype, i just "guest" how it works, so i "improvised" some functions to fit my needs) but it works as it should and the tests pass.
Mainly i would like help with cleaning up/simplifying things in `ApiRequest.hs` and `RangeQuery.hs`, the rest of the files i will cleanup.
=> Limit embeded items

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, test/Feature/DeleteSpec.hs
Something i missed when implementing &select for mutate requests.
Would be good to include in the upcoming release
=> Implement select/return representation for DELETE queries (fix #518)

CHANGELOG.md, src/PostgREST/App.hs, test/Feature/StructureSpec.hs
If the table is updatable it includes all the verbs, otherwise just GET.
Fixes #96
=> Include allow header in options response

postgrest.cabal
Allows `stack test` to build and pass on Windows.
=> Remove unix dependency for tests

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/QueryBuilder.hs, test/Feature/QueryLimitedSpec.hs
small bugfix, but worth 3.2.1 since without it you can't use --max-rows
=> Do not apply limit to parents, fix #637

CHANGELOG.md, src/PostgREST/DbStructure.hs, test/Feature/StructureSpec.hs
I use quite a lot of custom types in my schema, and would like to get the actual typenames when doing an OPTIONS request on a table. Right now, postgrest returns 'USER-DEFINED' if it is a custom type, and the base type if it is a domain. I had a look at the code and patched it to allow my usecase. I couldn't think of any reason to treat domains differently than other types in this context, or if outputting user-defined types in general is a bad idea?
=> Name custom types and domains on OPTIONS requests

postgrest.cabal
Postgresst uses hAllow, which was only added in 0.9.
=> Add version bounds on http-types

src/PostgREST/Parsers.hs
While I was working in another refactor when I came across this code that can be simplified right away.
As it turns out it maps a `[Text]` to another `[Text]` and a `Maybe Text` to another `Maybe Text` without changing the value.
=> Remove unnecessary string conversions

circle.yml, main/Main.hs, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/Auth.hs, src/PostgREST/Error.hs, src/PostgREST/Parsers.hs, src/PostgREST/Types.hs
This is the first of a series of PRs to banish String from our code and replace the default `Prelude` provided by haskell with a custom library.
I chose the [protolude](https://github.com/sdiehl/protolude/) for the sake of simplicity (it has less dependencies than [classy-prelude](https://github.com/snoyberg/classy-prelude) and focus only on very basic functionality). 
Some advantages we get from this:
- We have a default setup that will be easier for newcomer to work safely, for we won't have any more partial functions included by default. 
- We get rid of `string-conversions` as the `Show` class becomes polymorfic.
- We have much less work converting strings since most of `Wai` data comes in `ByteString` already.
=> Protolude first fugues

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/DbStructure.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs, test/fixtures/schema.sql
This PR introduces a breaking change, for functions that return scalar types, the output will be directly that value, it used to be wrapped in `[{functionname:...}]`.
This particular change, coupled with the fact that before running the PRC we know the output type, we can generate different queries (for example binary output). These issues are addressed #600 #599.
The other (more interesting) features are the fact that RPC path now joins the elites :) (GET/POST/PATH/DELETE) and supports filtering and shaping/embedding with &select
Enjoy
=> Rpc refactor

CONTRIBUTING.md
This adds a note to the CONTRIBUTING file about checking for schema cache freshness, since it has confused many people, including @wkrause13.
@rkoberg suggests we add an issue template; do we want to revisit #615?
=> Add schema cache freshness warning

stack.yaml
Its raw commit on github no longer exists
(Discovered this while testing build instructions on a new machine)
=> Use real version of hjsonschema

src/PostgREST/App.hs
This broke the build on GHC 8 with df6cbc4afa5b025f31c27a0d32c2d0253dd50eb3.
=> App: Remove erroneous import of Data.Monoid

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/OpenAPI.hs, test/Feature/InsertSpec.hs, test/Feature/QuerySpec.hs
This is an addon to #634 which addresses @nerfpops' comment about the Prefer header separator. [RFC7240](https://tools.ietf.org/html/rfc7240) specifies that comma rather than semicolon should separate multiple Prefer values.
Closes #627
=> Use comma rather than semicolon to split header values

CHANGELOG.md, main/Main.hs, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Auth.hs, src/PostgREST/Config.hs, src/PostgREST/Middleware.hs, test/Feature/AuthSpec.hs, test/Feature/NoJwtSpec.hs, test/Main.hs, test/SpecHelper.hs, test/fixtures/database.sql, test/fixtures/jwt.sql, test/fixtures/privileges.sql, test/fixtures/roles.sql, test/fixtures/schema.sql
Taking the opportunity to make some breaking changes for v0.4
This is a work in progress. It removes the default value of `"secret"` for JWTs, and responds with an error if someone tries authenticating against a postgrest server which has not been configured with a secret. The new code also adds the convention that a secret beginning with `@` means a filename from which to read the real secret. Reading from a file should allow unicode and binary secrets alike (but this requires testing). Reading from a file also removes sensitive information from the unix process list.
Two other JWT requested features not yet addressed are #505 and #567. Are these issues something we still want to fix?
I'll also be incorporating the custom validation discussed in #632...
=> Big bag of JWT fixes for accumulated issues

CHANGELOG.md, src/PostgREST/Auth.hs, test/fixtures/database.sql, test/fixtures/schema.sql
Fixes #674 
Saving `request.cookie` and `request.header` for another day after the 0.4 release.
=> Set request.jwt.claim.*

CHANGELOG.md, Dockerfile, main/Main.hs, postgrest.cabal, src/PostgREST/Config.hs, src/PostgREST/Error.hs
Fixes #474
Removes all the command line arguments except an argument `-c` to override path to configuration file. The default config file path is `~/.config/postgrest/conf` or `$XDG_CONFIG_HOME/postgrest/config` if that environment variable is set.
As of this first commit the PR is somewhat lacking because it doesn't provide help text that guides the user to the expected format of the config file.
=> Read settings from config file

src/PostgREST/QueryBuilder.hs
I originally used `count(1)` in queries because I mistakenly thought it was a speed optimization. Turns out `count(*)` is a special form and goes faster.
=> count(*) is faster than count(1)

stack.yaml
postgrest depends on postgres and zlib. When using stack's nix
integration, these dependencies must be specified explicitly.
Note that `--nix` must be passed to stack, or `nix.enable:true` must
be set in `stack.yaml` to enable using nix while building.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/begriffs/postgrest/726)
=> add nix.packages to stack.yaml

postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Error.hs, src/PostgREST/Middleware.hs, src/PostgREST/OpenAPI.hs
This PR is a small refactor in preparation for a series of refactors with the goal of reducing and simplifying the big `app` function.
It extracts the content type negotiation to a separate function (`servesMatchingContentTypes `) that later could be entirely removed and coded in terms of a new type called `InvalidResponse` that would encompass several error cases closer to the domain level.
It also extracts some common cases that checked for valid db requests into the functions `servesMutateRequest` and `servesReadRequest'`. This reduces duplication and improves a bit the readability of the big case body in the `app` function.
As part of readability improvements some lines were moved to bring definitions closer to their respective usage.
There is also some naming improvements, …
=> Reduce app function

postgrest.cabal, src/PostgREST/Config.hs
Fixes #736
The `readOptions` function is getting ungainly. I added comments to help explain it. The notion of having a command line argument that is conditionally mandatory does not fit Haskell's notion of Applicative, hence using optparse-applicative to parse the args is awkward. However that library is pretty convenient with help text formatting etc that I kept it and am working around it a little.
Code reviews appreciated.
=> Support conditional requirement for -c argument

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/QueryBuilder.hs, test/Feature/QuerySpec.hs, test/Feature/StructureSpec.hs, test/fixtures/schema.sql
At present, the parameters from an urlencoded form POST are first converted to JSON, and then this json is expaned into named parameters in [`callProc`](https://github.com/begriffs/postgrest/blob/41c1cf6e018b1ced2f720219fd4928cdc2259fa6/src/PostgREST/QueryBuilder.hs#L261). 
This flag instructs `callProc` to pass all parameters as a single JSON object to a stored procedure. If the request contains the header `Prefer: rpcParams=asJson`, then the call assumes a stored procedure with a single input JSON parameter and passes the complete params object as JSON.
This is super-useful for letting the database dispatch on more complicated HTML forms, or when the application has dynamically generated forms. Instead of creating multiple stored procedure for every possible combination of fields, a …
=> Introduce new 'Prefer' header, rpcParams=asJson

src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Error.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs
The idea behind this refactor is to extract error cases that were inside the `ApiRequest` type (namely as the `ActionInappropriate` and `PayloadParseError` constructors).
Now this error cases are handled by the `userApiRequest` that returns an `Either ApiRequestError ApiRequest`.
The type `ApiRequestError` has a function inside the error module that converts this type into an HTTP response. This function is used in the `postgrest` function making the `app` function slightly simpler as well.
=> Moves request error handling to user api request

postgrest.cabal
In #751 @SkinyMonkey discovered that regular cabal had a build error. The cause was a breaking change in optparse-applicative 0.13.0.0. This is an error we would have seen when upgrading to Stack LTS 7.10 as well actually.
I'm wondering whether I should examine the package versions chosen in the current LTS snapshot and add major version constraints to the packages in the cabal file. This will ensure that people who use cabal can also comfortably contribute to the project.
While I have gotten used to Stack and rather enjoy it, I know some other Haskellers prefer using the constraint solver for finer grained control. Cabal now supports `new-build` as well which can reuse build artifacts so it's really not so bad.
=> Add constraint for vanilla cabal builds

src/PostgREST/App.hs, src/PostgREST/Error.hs, test/Feature/QuerySpec.hs
The `formatGeneralError` function was being used in the same context as other plain text error messages. It seems to me that we don't need that JSON formatting for those error messages.
If we would keep the message/details structure for that message we would need a more extensive code change.
I also fixed a bug with our `errResponse` that would generate messages using text concatenation which could create an invalid json body.
=> Fix embeded relations error message

.gitignore, CHANGELOG.md, main/Main.hs, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Config.hs, test/Feature/BinaryJwtSecretSpec.hs, test/Main.hs, test/SpecHelper.hs
Backstory: Auth0 generates binary secrets and gives the user a base64URL encoded value to use. I was decoding that payload into a file and then trying to run postgrest with `jwt-secret = "@path/to/key"`. When postgrest would read that key file, it would read the contents as a string `[Char]`, convert to `Text`, and attempt to decode the jwt using this bastardized secret.
My solution was to have postgrest optionally accept base64 encoded secrets. All secrets are then converted to a `ByteString` and then decoded with the `binarySecret` function included in the jwt library.
The one "gotcha" is that if a service like Auth0 gives you a base64URL encoded value, you would need to convert* that into a base64 value when you insert that into your configuration file or `@secretfile`.
Auth0 is …
=> Binary secrets working and tested

CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Error.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/QueryBuilder.hs, stack.yaml, test/Feature/AuthSpec.hs, test/Feature/DeleteSpec.hs, test/Feature/InsertSpec.hs, test/Feature/QuerySpec.hs, test/Feature/SingularSpec.hs, test/Main.hs, test/SpecHelper.hs, test/fixtures/schema.sql
Fixes #748
This PR will remove support for `Prefer: plurality=singular` and add support for a special mime type in the Accept header that is like JSON except it encodes objects only, not arrays.
=> Use a mime type to request singular JSON responses

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/DeleteSpec.hs, test/Feature/InsertSpec.hs
Currently when doing this request:
```
POST /projects?select=pId:id,name,client_id
Prefer: return=representation
{"id":7,"name":"New Project","client_id":2}
```
This response is obtained:
```json
{"hint":null,"details":null,"code":"42703","message":"column pg_source.id does not exist"}
```
The error comes from the ```returningF``` function that allows the RETURNING to use alias and the subsequent SELECT made to shape the response doesn't consider the renamed columns.
This PR fixes that and also I refactored because I think that the RETURNING section fits better in the ```MutateQuery``` type since it's a part of the sql syntax for each of the sql mutate statements.
=> Fix alias in select for mutate queries and small refactor

postgrest.cabal, src/PostgREST/Config.hs, stack.yaml
Fix #778
- Compilation OK both with stack and nix (tested with ghc-8 only)
- Adding `import Data.Monoid` should be useless whenever Protolude releases a new version (https://github.com/sdiehl/protolude/commit/0fb7730b0c540c1be28cc18601a39cea50677eb7)
- I didn't update to a more recent LTS-7 version (to minimize PR changes)
=> Increase lower and upper bound for optparse-applicative

postgrest.cabal, src/PostgREST/Config.hs, src/PostgREST/Types.hs, stack.yaml, test/Feature/AuthSpec.hs, test/Feature/ConcurrentSpec.hs, test/Feature/DeleteSpec.hs, test/Feature/InsertSpec.hs, test/Feature/QueryLimitedSpec.hs, test/Feature/QuerySpec.hs, test/Feature/RangeSpec.hs, test/Feature/SingularSpec.hs, test/Feature/UnicodeSpec.hs, test/SpecHelper.hs
Stack resolver is now nightly-2017-01-31.
I actually started this upgrade to be able to compile on sierra (since GHC 8.0.1 was broken and the stackage nightly is using 8.0.2).
But to do so, hspec-wai had to be updated to 0.8.0 which changes the type for the `ResponseMatcher`.
Some caveats:
* When matching json now hspec assumes the header `Content-Type: application/json` when no `matchHeaders` is given, so I needed to specify it manually in some cases.
* When using `ResponseMatcher` I had to change the data constructor to use the `IsString` instance instead of the explicit `ResponseMatcher`.
* We cannot match against a body `Nothing` so now the body always has to be given as something that can be converted to a `ByteString`.
* In `SingularSpec.hs` line 145 the comment seems to be …
=> Update hspec-wai to 0.8.0

docker/Dockerfile, docker/config.conf, docker/docker-compose.yml
Updated the Dockerfile command to point postgrest at a config file. Verified that docker compose could spin it up locally when using a local image I built from the Dockerfile. After merging this I can generate a new "latest" on dockerhub.
This supports the direction I talked about in #808
=> Dockerfile that works with postgrest 0.4

CHANGELOG.md, main/Main.hs, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/Error.hs, src/PostgREST/Middleware.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Parsers.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs
This PR make fixes the problem of double encoding JSON errors and avoids whenever possible using Text values to represent error information. 
This is related to #791 and #757
Besides the fix there are some extra goals:
* Avoid exposing the `ParseError` type to better encapsulate the `Parsec` module inside our `Parsers`.
* Avoid exposing any formatting error functions from `Error` module so the error representation becomes more opaque.
* Add more constructors to `ApiRequestError` so it can describe in details more error conditions.
* Move the `ApiRequestError` type and some helper functions to the more generic `Types` module since they are used in several modules.
=> Refactor error type and fix nested error message [fix #791]

CHANGELOG.md, main/Main.hs, stack.yaml
I was able to find a few references to "Thread killed by Warp's timeout reaper" in other projects. One (Hets) resolved the issue by increasing the Warp connection timeout to one day. I'll explain and attempt to justify this below.
If accepted, this pull request resolves #827 in the same way as referred to in a Yesod [issue](https://github.com/yesodweb/wai/issues/351) and [resolved](https://github.com/spechub/Hets/pull/1520) in the Hets project.
---
Some browsers keep TCP connections open for a while, probably to improve the speed of subsequent requests to the same site. This is a reasonable practice.
Warp apparently has a feature to kill (reap) long running connections. The default connection timeout is 60 seconds. I can't find code listing the 60 second default--I see a [default of 30 …
=> Increase Warp connection timeout

CHANGELOG.md, src/PostgREST/ApiRequest.hs, test/Feature/QuerySpec.hs, test/fixtures/schema.sql
Fixes #777. I added the non-parametric stored procedure mentioned in the issue to the test database and wrote a test that simulates the curl command which makes an rpc call without a json body. Then located the call of the rpc in the request API and mapped the empty ByteString for rpc calls to an empty JSON body.
I added two imports in order to use empty ByteStrings and JSON Values, since I could find no elegant way to build them from the existing libraries. Would be happy to change that if there is some alternative I am missing.
=> Accept empty string as empty json body when calling an rpc

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/OpenAPI.hs
The latest version of swagger-ui https://github.com/swagger-api/swagger-ui/tree/v3.0.4 cannot consume the OpenAPI spec provided at `/api/`, throwing a content type error in the browser:
```
Failed to load resource: the server responded with a status of 415 (Unsupported Media Type)
GET http://localhost/api/ 415 (Unsupported Media Type)
```
The response sent by `postgrest` shows
```
{"message":"None of these Content-Types are available: application/json"}
```
This is caused by the [Content-Type request by swagger-ui](https://github.com/swagger-api/swagger-ui/blob/e23dada9fed460a5e4a88809db362ee75ccd08aa/src/core/plugins/download-url.js#L18).
This PR adds support for this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Adds application/json to inspect type

CHANGELOG.md, src/PostgREST/App.hs
When `server-proxy-uri` is not set in `postgrest.conf`, the `swagger.json` would report a `Base url: 0.0.0.0:3000/`, which results in the generated API calls for the examples to have an extra slash i.e. the "//" in:
```
curl -X GET http://0.0.0.0:3000//skills -H  "accept: application/json" -H  "content-type: application/json" -H  "Range: undefined" -H  "Range-Unit: items" -H  "Prefer: undefined"
```
This results in a failure when trying out the API, see:
This PR removes this extraneous tailing "/" for the case where `server-proxy-uri` is not set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/begriffs/postgrest/857)
=> Fix swagger-ui when "server-proxy-uri" is not set

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Types.hs, test/fixtures/schema.sql
A read-only standby postgresql server does not support read-write transactions. Our code used to ask for these kind of transactions to call stored procs, but this PR checks the volatility class of the function and uses read-only transactions when possible.
=> Read only proc tx

CHANGELOG.md, src/PostgREST/App.hs, test/Feature/InsertSpec.hs
Fixes #493. 
While running the new tests noticed that the table `items`, which is being used by several tests of the update requests, changes between those tests. Made some corrections but could not discover why `id:16` is being added to it. For the time being I just ignored that.
=> Update with empty json

.gitattributes
When we have multiple pull requests modifying the changelog the later ones to be merged have had to do a rebase to eliminate the conflict. This PR specifies the "union" merge strategy apply on the changelog which accepts lines from all differences and includes them in random order.
=> Use union merge strategy on changelog

CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/Auth.hs, src/PostgREST/Middleware.hs, src/PostgREST/QueryBuilder.hs, test/Feature/QuerySpec.hs, test/fixtures/schema.sql
This PR makes request headers available as GUC vars for each request
It also sets `request.jwt.claims.role`, it useful when doing RLS through views.
Please look at runWithClaims from middleware if it needs some nicer style/formatting
=> Make HTTP headers available as GUCs #800

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
While working on the ```where``` param I noticed that it may suffer from this lacking #701 as well, for example in ```people?where=and{name=in.Thompson, Larry,or{age=gte.18,height=lte.180}}``` or even ```..eq.Thompson, Larry,or{age..``` I'll have to consider that later.
Because of that I thought on working this first and also do some refactoring, the ```where``` param may combine different parsers so I'm trying to be cautious and not make my implementation a source of bugs or maintainability problems.
=> Fix #701: allow quoted values for IN operator, refactor and Fix #641: allow IN filter to have no values

CHANGELOG.md, main/Main.hs, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Error.hs, test/Main.hs
This adds a capped exponential backoff(base is 1 second, cap is 32 seconds, arbitrarily picked, could be improved) for retrying the db connection in a background thread.
This thread is started at postgREST startup and leaves it rejecting all requests with a 503 with no parsing or further processing, it's in an ```unavailable``` state until connection succeeds; this thread can also be started on SIGHUP.
I considered that postgREST is in an ```available``` state when the dbStructure is successfully obtained, and that's what the ```connectionWorker``` works on, I'll explain why:
At first I had an ```available``` IORef for when the connection succeeded but got some issues when the dbStructure was not obtained, for example postgREST succeeded with requests like:
```http
GET /clients
GET …
```
=> Add connection retrying on startup and SIGHUP, Fix #742

CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/AndOrParamsSpec.hs, test/Feature/QuerySpec.hs, test/Main.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
The ```and/or``` params are working as discussed in #652 though this is a work in progress(only working for GET for now), I wanted to show how this currently works and propose some solutions to some conflicts I've bumped into, so right now:
```http
GET /people?not.or={student.is.true,not.and{age.gte.18,height.lte.180}}
```
Gets translated in sql to:
```sql
WHERE NOT ( student IS TRUE OR NOT ( age => 18 AND height <= 180))
```
I've added the optional ```not``` to the and/or, also since in #652 no one objected to the idea of replacing ```=``` with ```.``` I went ahead and implemented it like that to avoid the need to urlencode.
Also added the ability to combine ```and``` with ```or``` params, in addition to the ability to combine those with traditional filters:  
```http
GET …
```
=> Add and/or params for doing complex boolean logic, Fix #652

CHANGELOG.md, docker/Dockerfile, docker/docker-compose.yml, docker/postgrest.conf, postgrest.cabal, src/PostgREST/Config.hs, stack.yaml
Work in progress to use a combination of config file and environment variables in a Dockerfile.
=> Use env interpolation in config

docker/Dockerfile
Running postgrest requires the libpq library runtime, not the -dev
package.
Make sure that tools that are used to download and extract the postgrest
package do not remain installed in the image.
=> Dockerfile: Clean up to save space

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/DbStructure.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs, test/fixtures/schema.sql
Fixes #883. By default, when requesting ```Accept: application/octet-stream``` the user has to do 
```?select=single_col``` similar to binary output on GET, but since a stored procedure can return a scalar    I considered that is not necessary to force the user to do a ```/rpc_name?select=rpc_name``` so in the case of scalar I'm not applying that restriction.  
To do that I changed ```callProc``` to make it consider if the proc is scalar by consulting the ```ProcDescription```, this also avoids doing a [count](https://github.com/begriffs/postgrest/blob/b00742814216be685fddcd3ed61c2ce81894fbf0/src/PostgREST/QueryBuilder.hs#L158-L161) to determine this. 
A disadvantage of that is that now for a proc to return the scalar properly(e.g. a rpc that returns an integer should return ```4``` not …
=> Binary output support for RPC

docker/postgrest.conf
There was this typo in the ./docker/postgrest.conf example file, hoping to spare others from having to chase this straight back to the source code.
=> fix(doc): server-proxy-uri -- URI, not URL

src/PostgREST/DbRequestBuilder.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs
This is for not having ```flt_::[Filter], logic::[LogicTree]``` and instead just a single 
```where_:[LogicTree]``` in the ```ReadQuery/MutateQuery``` types, this was mentioned in https://github.com/begriffs/postgrest/pull/864#issuecomment-296352326
=> Put traditional Filters inside [LogicTree]

CHANGELOG.md, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs
*Well, this bothered me more than it should :)*
When embedding parents we had the ability to say which FK to use by using it directly instead of the table name ( `billing_address_id`, `shipping_address_id` )
but when requesting children, there is no such possibility.
This PR adds the possibility to "lock" the path in the other direction like this
`/addresses?select=id,billed:orders.billing_address_id{id},shipped:orders.shipping_address_id{id}`
*the aliases before `:` are not mandatory when there is no collision*
In this case, the part after the `.` is the name of the FK
When there is a many to many relation, it's also possible to select it like so
`/tasks?select=id,users.users_tasks{id}`
In this case the part after the `.` is the name of the "link" table.
PS: I'd like to thank the …
=> Ability to embed using a specific relation when there are multiple between tables, fixes #907

CHANGELOG.md, src/PostgREST/DbStructure.hs
Reduce computation required to generate relations on the first request.
**PostgREST v0.4.2.0**
```
$ time curl 'http://localhost:3000/x?select=x(*)'
real	0m27.601s
user	0m0.001s
sys	0m0.001s
```
**PostgREST with combinations improvement**
```
$ time curl 'http://localhost:3000/x?select=x(*)'
real	0m0.012s
user	0m0.001s
sys	0m0.001s
```
=> Improve relations initialization time (#924)

circle.yml, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/QueryBuilder.hs, stack.yaml
Upgrade for the speed improvements prior to releasing a new postgrest version.
@ruslantalpa note that I had to use a stackage snapshot plus hold some other packages' versions back. I'd kind of like to wait for hasql to appear in stackage again and work cleanly with the other packages...
=> Upgrade to fast new hasql

src/PostgREST/Config.hs
Docker may pass in an empty string, in which case use the default value.
Wanted to get this PR in before release.
=> Treat blank host config param as missing

test/create_test_db, test/destroy_test_db
Without this, psql will try to use the default database name for the user
The database part of the uri only needs to be stripped for the final part of create_test_db
=> Allow passing URI with database to tests

.circleci/config.yml, CHANGELOG.md, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/AndOrParamsSpec.hs, test/Feature/QuerySpec.hs, test/fixtures/data.sql
Fixes #887, #601. Now is possible to:
```http
GET /tsearch?ts_vector=french.fts.amusant
GET /tsearch?ts_vector=plain.fts.The%20Fat%20Cats
GET /tsearch?ts_vector=phrase.fts.The%20Fat%20Rats
GET /tsearch?ts_vector=phrase.english.fts.The%20Fat%20Cats
GET /tsearch?ts_vector=not.phrase.english.fts.The%20Fat%20Cats
```
There is a catch the `phraseto_tsquery` function is only supported for pg > 9.6, so this should be noted in the docs also that's the reason why I upgraded the circle pg to 9.6.2, otherwise the tests would fail.
=> Allow specifying dictionary and plain/phrase in full text search

src/PostgREST/ApiRequest.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/RpcSpec.hs, test/fixtures/schema.sql
Fixes the bugs mentioned in https://github.com/begriffs/postgrest/pull/946#issuecomment-330617307.
=> Fix RPC GET filters bugs with not/{plain,phrase}fts operators

CHANGELOG.md, main/Main.hs, test/io-tests.sh
This allows to read binary secrets as well as text (UTF-8) or Base64
secrets. Also, the final LF character (`\n`), if any, is now removed.
After this change, all I/O unit tests now pass.
=> Read secret file as binary, without premature parsing as UTF-8 (#876)

README.md
Add a shield to the readme to steer people to the new repo on docker hub.
Related to https://github.com/begriffs/postgrest-docs/issues/101
=> Link to new docker hub repo

CHANGELOG.md, src/PostgREST/QueryBuilder.hs
Error is reported while resource embedding when table name and column name in the table are same.
```
{"hint":"No function matches the given name and argument types. You might need to add explicit type casts."
,"details":null
,"code":"42883"
,"message":"function row_to_json(uuid) does not exist"
}
```
`uuid` is type of column, but it should be `row`.
To name table explicitly use `.*`
=> Fix embedded column conflicts table name

CHANGELOG.md, src/PostgREST/DbStructure.hs, src/PostgREST/QueryBuilder.hs, test/Feature/QuerySpec.hs, test/Feature/RpcSpec.hs, test/Feature/StructureSpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Fixes #974, I had to accommodate OpenAPI output because this [test](https://github.com/steve-chavez/postgrest/blob/master/test/Feature/StructureSpec.hs#L23-L25) was failing when including functions with OUT/INOUT parameters in `fixtures/schema.sql`, also I included a test for the recent #996.
Would be better to merge this PR before the others currently opened so the commit with the test can follow up the commit in #966. Also from now on, after reviews, I would like to merge my own PRs if that's fine.
=> Fix RPC error when function has single OUT param

postgrest.cabal
It is a deps of hjsonchema and does not need to be pinned to a specific version.
=> Remove hjsonpointer

.circleci/config.yml, CHANGELOG.md, main/Main.hs, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Error.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/AndOrParamsSpec.hs, test/Feature/PgVersion96Spec.hs, test/Feature/QuerySpec.hs, test/Feature/RpcSpec.hs, test/Main.hs, test/fixtures/schema.sql
PR adds the following:
- When invoking an rpc is possible to set http headers by doing:
```sql
SET LOCAL "response.headers" = '[{"X-Test": "Domain=.server.com; Secure; Version=1"}, {"X-Test-2": "TimeoutLoggedIn=login; Version=1"}]';
```
This gets mapped to:
```http
HTTP/1.1 200 OK
Server: postgrest/0.4.3.0
Content-Type: application/json; charset=utf-8
X-Test: Domain=.server.com; Secure; Version=1
X-Test-2: TimeoutLoggedIn=login; Version=1
```
The value for the `response.headers` must be a json array of objects with a single key and a string value for the reason mentioned in https://github.com/begriffs/postgrest/pull/664#issuecomment-231635405, if a specified value doesn't comply with this a `500` response is sent to the client.
- As proposed in …
=> Add ability to set custom http headers and http status

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/AndOrParamsSpec.hs, test/Feature/PgVersion96Spec.hs, test/Feature/QuerySpec.hs, test/Feature/RpcSpec.hs
Changes the syntax for `phrase/plain` introduced in #964.
Previous syntax:
```http
GET /tsearch?tsv=french.fts.amusant
GET /tsearch?tsv=plain.german.fts.Art%20Spass
GET /tsearch?tsv=phrase.english.fts.The%20Fat%20Cats
```
New syntax:
```http
GET /tsearch?tsv=fts(french).amusant
GET /tsearch?tsv=plfts(german).Art%20Spass
GET /tsearch?tsv=phfts(english).The%20Fat%20Cats
```
New syntax is a bit shorter, it's more alike to the pg `{plain/phrase}to_tsquery` functions in that the first arg is the language(previous one has the language between plain/phrase and fts) and also it's more consistent because dots `.` are currently used like separators and the `(language)` fits better as an optional argument.
Also have to mention that having `not.english..` was kinda confusing inside `and/or` …
=> Change phrase/plain full text search syntax

CHANGELOG.md, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs
**Edit**: Omit this proposal, no need to upgrade PostgreSQL version, see my comment below.
Main idea to solve this was to include the primary keys on the LEFT JOIN subquery regardless of whether the user requested them or not, and then remove them from the output by using PostgreSQL jsonb `-` operator.
So now when requesting:
```http
GET /projects?select=*,client{name}
```
This query is generated:
```sql
WITH pg_source AS (
SELECT "test"."projects".*,
to_jsonb("clients_client".*) - 'id' AS "client"
FROM "test"."projects"
LEFT JOIN (
SELECT "test"."clients"."id",
"test"."clients"."name"
FROM "test"."clients"
) AS "clients_client" ON "clients_client"."id" = "projects"."client_id")
SELECT NULL AS total_result_set,
pg_catalog.count(_postgrest_t) AS page_total, array[]::text[] AS header, …
```
=> Remove the need for pk in &select for parent embed

CHANGELOG.md, postgrest.cabal, src/PostgREST/Config.hs
When people submit a bug report for a custom binary they built off master it would be helpful to know exactly which git hash they built from. This helps us debug problems better.
This pull request adds the first seven characters of the git sha to the version output in the Server response header and also the usage screen.
=> Include git sha in version

CHANGELOG.md, src/PostgREST/QueryBuilder.hs, test/Feature/InsertSpec.hs, test/Feature/QueryLimitedSpec.hs, test/Feature/QuerySpec.hs, test/Feature/RangeSpec.hs, test/Feature/RpcSpec.hs, test/Feature/SingularSpec.hs
with these changes a single postgrest joined query with json encoding over 3 tables is as fast as making 3 distinct queries (with `id in (...)` condition) on one table each.
tests changed because json_agg returns a slightly different json format, but the same data.
=> Faster queries using json_agg

CHANGELOG.md, src/PostgREST/Middleware.hs, test/Feature/QuerySpec.hs, test/Feature/StructureSpec.hs, test/fixtures/jwt.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Fix #828, breaking change: computed columns now only work if they are on the config schema.
Fix #835, tests now not depend on the search_path of the postgrest_test_authenticator.
=> Add `set schema` to middleware

.circleci/config.yml, CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, stack.yaml, test/Feature/InsertSpec.hs, test/Feature/RpcSpec.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql, test/memory-tests.sh, test/memory-tests/config
Fixes #925, the memory usage when posting a big payload on RPC now is practically the same as when doing an INSERT.
I'm using `json_to_record` pg function for this, it's available on pg >= 9.4, it's possible to maintain backwards compatibility by querying the pg version and keeping the previous custom input sanitizing for pg 9.3, but for now not sure if it's worth it.
=> Change RPC/UPDATE query to a parametrized query, avoid payload json encoding

src/PostgREST/ApiRequest.hs, test/Feature/InsertSpec.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql, test/memory-tests.sh
For #690, currently when POSTing a json payload of 3.4M that has 100000 array values, we get a `41G` memory usage:
<details>
<summary>Master branch profile report</summary>
<pre>
total time  =       10.41 secs   (10414 ticks @ 1000 us, 1 processor)
total alloc = 41,337,480,760 bytes  (excludes profiling overheads)
COST CENTRE              MODULE                         SRC                                                 %time %alloc
basicUnsafeNew           Data.Vector.Mutable            Data/Vector/Mutable.hs:(99,3)-(102,32)               58.5   96.9
basicUnsafeCopy          Data.Vector                    Data/Vector.hs:(280,3)-(281,29)                      23.5    0.0
">>=.\.succ'"            Data.Attoparsec.Internal.Types Data/Attoparsec/Internal/Types.hs:146:13-76           6.7    0.7 …
=> Reduce memory usage of bulk inserts

CHANGELOG.md, main/Main.hs, postgrest.cabal, src/PostgREST/Config.hs, src/PostgREST/DbStructure.hs, test/Feature/QuerySpec.hs, test/Main.hs, test/SpecHelper.hs
- allows queries to refer to current_setting('app.env.[ENV]') to
retrieve environment variables
- useful for 12-factor apps (app data can be in environment)
- provides workaround for AWS Relational Database Service (RDS) not
allowing `ALTER DATABASE SET 'app.[KEY]' TO '[VALUE]'` on database.
Fixes #1062 
UPDATE: Now uses `current_settings('app.settings.*')` and a more generic way of getting data into those settings--rather than dump the entire ENV into the session, the config file can now specify which ENV vars, if any, are added to the db session, along side other strings and app setting data.
=> Add the postgREST process' environment to the DB's SESSION

CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/Error.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/UpsertSpec.hs, test/Main.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Closes #256. UPSERT is done with the `ON CONFLICT` clause available on PostgreSQL >= 9.5. 
Bulk UPSERT can be done by adding `Prefer: resolution=ignore-duplicates/merge-duplicates` headers, these do a `INSERT .. ON CONFLICT(<pkCols>) DO NOTHING/DO UPDATE`. 
The `ignore-duplicates/merge-duplicates` Prefer values only work with tables that have a PK, if the table doesn't have a PK the `Prefer` will be ignored(no error).
Single row UPSERT can be done with PUT if the client specifies only PK columns as `eq` filters and the payload is identified by the URI, other restrictions include not allowing `Content-Range/limit/offset`(took into account the previous [implementation](https://github.com/begriffs/postgrest/blob/a34051b1774eb4b589354a469024d4ce2482bc83/src/Dbapi.hs#L137-L158)).
=> Add support for UPSERT

CHANGELOG.md, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Fixes #987.  Using the `family_tree` TABLE provided in https://github.com/begriffs/postgrest/issues/987#issue-260720899 we do a: 
`GET /family_tree?id=eq.3&select=family_tree.parent(*)` and currently this generates the following query:
```sql
SELECT COALESCE((
SELECT array_to_json(array_agg(row_to_json("family_tree"))) 
FROM (
SELECT  "test"."family_tree".* FROM  "test"."family_tree"  
WHERE  "test"."family_tree"."parent" = "test"."family_tree"."id") "family_tree"),
'[]') AS "family_tree" FROM  "test"."family_tree"  WHERE  "test"."family_tree"."id" = '3'::unknown;
-- Gives []
-- It should give [{"id":"5","name":"Grandkid Two","parent":"3"}]   
```
The problem is that the subquery should be referring to the parent `"test"."family_tree"`, to get the correct result the query should be like: …
=> Add tables aliasing to avoid conflict in embeds with self reference fks

CHANGELOG.md, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
On #1054 aliasing was added to all tables to fix the self join cases, however that made the error messages a bit unclear:
```http
GET "/items?select=id,wrong"
{"hint":null,"details":null,"code":"42703","message":"column items_1.wrong does not exist"}
GET "/clients?select=*,projects(id,name,wrong)"
{"hint":null,"details":null,"code":"42703","message":"column projects_2.wrong does not exist"}
GET "localhost:3000/tasks?select=id,name,project(id,name,client(id,name,wrong))"
{"hint":null,"details":null,"code":"42703","message":"column tasks_3.wrong does not exist"}
```
There may be other cases where the error messages and generated queries are harder to understand.
Self reference fks are rare in db designs, so I thought it'd be better to restrict the aliasing to only self joins.
=> Allow embeds alias to be used in filters, specifying source column in embed and only alias tables on self join

CHANGELOG.md, appveyor.yml, src/PostgREST/Parsers.hs, src/PostgREST/Types.hs, test/Feature/AndOrParamsSpec.hs, test/Feature/DeleteSpec.hs, test/Feature/InsertSpec.hs, test/Feature/QueryLimitedSpec.hs, test/Feature/QuerySpec.hs, test/Feature/RangeSpec.hs, test/Feature/RpcSpec.hs, test/Feature/SingularSpec.hs
As agreed on https://github.com/begriffs/postgrest/pull/864#issuecomment-298477923 and https://github.com/begriffs/postgrest/pull/938#issuecomment-322067169, also mentioned in the docs, for the upcoming `v5.0.0` I'm removing support for:
```http
-- brackets "{}" for embeds
GET /clients?select=id,projects{id,name}
-- from now on parens "()" will be used for embeds
GET /clients?select=id,projects(id,name)
-- @@  @>  <@ operators
GET /entities?arr=not.<@.{1}&arr=@>.{1,2,3}&tsv=@@.smth
-- from now on their url safe equivalents will be used
GET /entities?arr=not.cd.{1}&arr=cs.{1,2,3}&tsv=fts.smth
```
=> Remove support for non url safe characters

CHANGELOG.md, src/PostgREST/DbStructure.hs, test/Feature/QuerySpec.hs, test/Feature/StructureSpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
A continuation of #1061 adding the missing `'f'` in the `accessibleTables` query and making sure it works with [file_fdw](https://www.postgresql.org/docs/10/static/file-fdw.html) tests as suggested by begriffs. Credit in the CHANGELOG goes to @rhyamada.
=> Add foreign tables to OpenAPI output

CHANGELOG.md, src/PostgREST/Parsers.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs
Continuing the work on #1047, also included a test for multi-column sorting.
=> Fix accepting misspellings in order syntax

docker/postgrest.conf
With #1091, the role-claim-key was added, but it is not configurable in docker containers as the template config doesn't allow it.
This patch adds the necessary line to the postgrest.conf of the docker container.
=> Add role-claim-key to docker postgrest.conf

postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/QueryBuilder.hs, stack.yaml
protolude provides headMay since 0.2.2, it can be used instead of safe.
=> Use protolude 0.2.2

CHANGELOG.md, postgrest.cabal, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/AndOrParamsSpec.hs, test/Feature/InsertSpec.hs, test/Feature/JsonOperatorSpec.hs, test/Feature/PgVersion95Spec.hs, test/Feature/QuerySpec.hs, test/Main.hs, test/create_test_db, test/destroy_test_db, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Closes #1099, json/jsonb array indexes can now be specified as:
```http
GET /json_arr?select=data->2->key->>1 
```
Negative indexes(only for pg >= 9.5), e.g. `select=data->-4`, also work as per the PostgreSQL [docs](https://www.postgresql.org/docs/9.5/static/functions-json.html).
Only thing missing for fully compliant `->/->>` operators would be to allow finishing a json path with `->` and not restrict it to finish with `->>`. As it is now, for obtaining json the user needs to cast like `data->>key::json`.
The docs used to say: `The final arrow must be the double kind, ->>, or else PostgREST will not attempt to look inside the JSON`, but not sure why it was done this way, @ruslantalpa maybe you can shed some light into this.
=> Add support for getting json/jsonb by array index

CHANGELOG.md, src/PostgREST/DbStructure.hs, test/Feature/QuerySpec.hs, test/Feature/StructureSpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
For #945, the change to the regex included in #761 seems to generate excessive backtracks, I've removed that and simply void the `search_path` for the query to have a normalized output, this was also recommended in #761 as a better alternative, the counterarguments presented there against this are at best nice-to-haves when taking into account the huge performance impact.
This is still a work in progress, I believe the query can be improved further, it's pending to generate a test case for this(programatically creating a big schema) and the `SET schema ''` is affecting a whole session, this won't be an issue because we also do a `SET schema <db-schema>` on each request, but it'd be better to isolate it in a transaction. 
Edit: This approach was discarded, see below.
=> Improve the allSynonyms query

CHANGELOG.md, src/PostgREST/OpenAPI.hs, test/Feature/StructureSpec.hs
This PR adds the `definitions.{definition}.required` list with the names of the columns that have `colNullable` set to `False`.
For example, if I have a table
```sql
create table organisms (
name   text primary key,
tax_id text not null
);
```
Then the corresponding definition in the generated OpenAPI specification will be
```json
"definitions": {
"organisms": {
"required": [
"name",
"tax_id"
],
"properties": {
"name": {
"format": "text",
"type": "string",
"description": "Note:\nThis is a Primary Key.<pk/>"
},
"tax_id": {
"format": "text",
"type": "string"
}
},
"type": "object"
}
}
```
Notice the `required` list: `name` column is the primary key, so it's not null and `tax_id` has an explicit `not null` annotation.
Motivation: I'm using the Swagger/OpenAPI specification provided by …
=> OpenAPI: add required section for the non-nullable columns

CHANGELOG.md, src/PostgREST/QueryBuilder.hs, test/Feature/RpcSpec.hs, test/fixtures/schema.sql
Your proposed change did not do it, there was another spot that also needed pgFmtIdent()
=> Quote identifier names in RPC function arguments

CHANGELOG.md, main/Main.hs
Fixes #905. Basically revert https://github.com/PostgREST/postgrest/pull/834, main problem that PR intended to solve was to remove a warning in the logs. Don't see a strong reason(like perf tests) to not restore the timeout default of 30 seconds.
I don't have the means to reproduce this bug now so don't know exactly why the empty replies happen on certain systems(like raspbian on rpi), but I'm suspicious of kernel [tcp variables](https://www.frozentux.net/ipsysctl-tutorial/chunkyhtml/tcpvariables.html)(can be queried with `sysctl -a | grep tcp`), these are usually [tuned](http://www.linux-admins.net/2010/09/linux-tcp-tuning.html) on low-memory setups.
=> Fix #905, intermittent empty replies

stack.yaml
This was reported in https://gitter.im/begriffs/postgrest?at=5b7431eb5b07ae730ac083af
and according to https://ghc.haskell.org/trac/ghc/ticket/13112#comment:25
this is an issue with linking in postgresql-libpq. The 0.9.4.1 version
contains a patch(https://github.com/lpsmith/postgresql-libpq/pull/45) that fixes the issue.
=> Fix segmentation fault/access violation on windows 10

src/PostgREST/Config.hs, test/Feature/CorsSpec.hs
PUT requests are part of the public upsert API, so if postgrest
runs at a different origin, these requests will fail because they
don't pass CORS.
=> Config: apply CorsResourcePolicy to PUT requests

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/Auth.hs, src/PostgREST/Config.hs, test/Main.hs, test/SpecHelper.hs
This should resolve #505.
The configuration option `jwt-secret` is a bit overloaded now as it's doing three things so perhaps there should be thought about whether one option works (also perhaps the name needs to be updated).
I'll update the documentation once this feature has been reviewed and accepted.
=> Add support for parsing JSON Web Key Sets

CHANGELOG.md, postgrest.cabal, src/PostgREST/Config.hs, src/PostgREST/Middleware.hs, src/PostgREST/QueryBuilder.hs, test/Feature/ExtraSearchPathSpec.hs, test/Feature/QuerySpec.hs, test/Main.hs, test/SpecHelper.hs, test/fixtures/data.sql, test/fixtures/database.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Fixes #1200. The config value has a list format: 
```rust
db-extra-search-path = ["public", "extensions"]
```
By default the config is `["public"]` .
Is the list format appropriate? Or perhaps I should change it to maintain the format used by pg `search_path`, like `db-extra-search-path = "public, extensions"`? I just reused `configurator-ng` functionality for now, but I guess I could parse the value and make it comma separated.
**Edit**: Now the config value has the following format
```rust
db-extra-search-path = "public, extensions"
```
=> Add db-extra-search-path config

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/Parsers.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/InsertSpec.hs, test/Feature/RpcSpec.hs, test/memory-tests.sh
Fixes #690. Also fixes #1234.
As proposed in https://github.com/PostgREST/postgrest/issues/690#issuecomment-378363946, now a `columns` query parameter can be specified to delegate all the json processing to PostgreSQL when doing POSTs(also RPC and PATCH). This is analogous to how we've been doing GET until now.
This new mechanism makes our perf test of bulk inserting 100000 json array values improve on memory consumption, from 1.15G to 20M, around 1% of what it used to be.
=> Faster bulk insert with ?columns query arg

CHANGELOG.md, src/PostgREST/DbStructure.hs, test/Feature/QuerySpec.hs
Currently, it's only possible to do resource embedding on non-materialized views and tables. This PR enables support for materialized views.
Fixes #1239
=> Allows resource embedding on materialized views

CHANGELOG.md, src/PostgREST/OpenAPI.hs, test/Feature/StructureSpec.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
At the moment smallint and other numeric types get `string` types in the OpenAPI spec. This attempts to fix this by adding some missing types to `toSwaggerType`. Types are based on https://www.postgresql.org/docs/current/datatype.html and https://swagger.io/docs/specification/data-models/data-types/ .
This should fix #1238 .
Note: I'm not at all familiar with Haskell, so point me in the right direction if a test or something else is missing or necessary to implement this.
Edit: I've missed the RPC test in `StructureSpec.hs`. Test should pass now.
=> Add numeric and character types to OpenAPI spec

docker/Dockerfile
The docker image should not run as root by default.
I think it is best practice to create a separate user to run the process. Therefore I added a user and modified the docker image to use this user.
=> The process should not run as root within docker

CHANGELOG.md, src/PostgREST/QueryBuilder.hs, test/Feature/ProxySpec.hs, test/Feature/RpcSpec.hs, test/Feature/StructureSpec.hs, test/fixtures/schema.sql
Still working on relational inserts. I wanted to do a quick PR.
I'm commenting the OpenAPI tests that timeout on CircleCI. Having these errors require frequent manual restarts and could also make our release workflow fail(this would hurt to correct).
I'll resort to running these tests locally to make sure OpenAPI output doesn't break.
A better solution would be https://github.com/PostgREST/postgrest/issues/934#issuecomment-478696637, but for now I'll do this. 
Also added support for #1264.
=> Add support for bulk rpc

src/PostgREST/Types.hs, test/Feature/AuthSpec.hs, test/Feature/InsertSpec.hs, test/Feature/JsonOperatorSpec.hs, test/Main.hs
Hey there.
While running PostgREST test suit, I found 5 tests that failed. Investigating it further, it seems there was a change in postgres error messages, making the expected outputs in a way, obsolete.
Reproducing this issue by running the tests as described in the [documentation](http://postgrest.org/en/v5.1/install.html?highlight=test#testing-with-docker):
```
$ docker run --name db-scripting-test -e POSTGRES_PASSWORD=pwd -p 5434:5432 -d postgres:latest
$ POSTGREST_TEST_CONNECTION=$(test/create_test_db "postgres://postgres:pwd@localhost:5434" test_db) stack test
```
Notice the flag as latest. Omitting it or using the tag `:11` or even `:11.2` would fetch the same postgres image. To get the tests running we can simply pick the tag `:10` or anything under (and above PostgREST minimum …
=> Fix tests expected responses due to changes in pg11

CHANGELOG.md, src/PostgREST/QueryBuilder.hs, test/Feature/UpsertSpec.hs
Simple fix and respective test that resolves #1265.
I've added a simple check to check what columns are selected. If none are (the reason behind the syntax error), then it creates a `DO NOTHING` as suggested in the issue.
=> Fix invalid SQL generated for bulk upsert with empty array

src/PostgREST/App.hs, src/PostgREST/Error.hs, test/Feature/InsertSpec.hs, test/Feature/SingularSpec.hs, test/fixtures/schema.sql
This is a simple attempt to fix the reported bug described in title.
So, citing #1257 and confirmed by this test in this PR:
> Right now in my tests, I'm getting 204 whether or not any rows were updated. 
This PR can be tweaked to take care of some of the failing tests, but like in the previous PR, I would argue that some of those failing tests should be tweaked as well.
Let me know what you think.
This resolves #1257 .
=> Fix wrong status 404 when PATCH request didn't change anything

CHANGELOG.md, main/Main.hs, src/PostgREST/Config.hs, test/SpecHelper.hs
Resolves #1278 
Added to config, key `db-pool-timeout` that accepts float/int.
=> Add config option for pool timeout

.github/CONTRIBUTING.md
This updates the [`CONTRIBUTING.md`](https://github.com/PostgREST/postgrest/blob/e2bd91623777b2ade2ddd78f48fa7cc115556533/.github/CONTRIBUTING.md) instructions about sending a `SIGHUP` call (deprecated) to `SIGUSR1`, and links to relevant docs: http://postgrest.org/en/v5.2/admin.html#schema-reloading
Per the docs:
> As of PostgREST v5.1 reloading with SIGHUP is deprecated, it’s still supported but will be removed in v6.0. SIGUSR1 should be used instead.
See [5.1.0 CHANGELOG](https://github.com/PostgREST/postgrest/blob/d32f373e1ee95ba68141a3f3a48ab8c94ea2453a/CHANGELOG.md#deprecated) or https://github.com/PostgREST/postgrest/issues/724
=> Fix reference to deprecated SIGHUP call

.circleci/config.yml, CHANGELOG.md, main/Main.hs, src/PostgREST/ApiRequest.hs, src/PostgREST/Config.hs, src/PostgREST/Parsers.hs, stack.yaml, test/Feature/QuerySpec.hs
Breaking changes for the upcoming version. 
- Remove SIGHUP
- Change server-host default of 127.0.0.1 to !4
- Change symbol for disambiguating resource embedding(undocumented featured added in #918) from dot '.' to plus '+'. Used to be `/clients?select=id,projects:projects.client_id(id,tasks(id))`, now is `/clients?select=id,projects:project+client_id(id,tasks(id))`.
+ Dot is not clear since we already use the dot '.' for representing embedded filters.
+ Dot in pg implies dot notation(e.g. `table.col`) which is not the case when we use the dot for disambiguating many to many relationships.
=> Breaking changes

CHANGELOG.md, main/Main.hs, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/Error.hs, src/PostgREST/Middleware.hs, src/PostgREST/Parsers.hs, src/PostgREST/Types.hs, test/Feature/InsertSpec.hs, test/Feature/NoJwtSpec.hs, test/Feature/PgVersion96Spec.hs, test/Feature/QuerySpec.hs, test/Feature/RangeSpec.hs, test/Feature/RpcSpec.hs, test/Feature/UpsertSpec.hs
Hey there.
This is a PR to clean out a bit the error responses code and improve coverage for it. I've tried to keep it from noticeable run-time changes.
Changes from this PR:
- Created typeclass `PostgRestError`, which is used for all error responses. It also requires the error to be an instance of `toJSON` to render the body. This was already the case for the pgerrors and apiRequestError.
- Moved `ApiRequestError` from `Types.hs` to `Error.hs`.
- Created instance of `PostgRestError` for `ApiRequestError`.
- Created `PgError` datatype. It bundles the hasql error and the `authed` var.
- Created instance of `PostgRestError` for `PgError`.
- Created instance of `toJSON` for `PgError`. This only calls `toJSON` on the hasql error, using the already implemented instances to render the final …
=> Small refactor around error responses and more tests

shell.nix, stack.yaml
For NixOS users. Couldn't  `stack build` with latest NixOS(19.03) otherwise.
=> Add shell.nix

postgrest.cabal
parseQueryReplacePlus was introduced with version 0.12.2
I ran into this trying to build postgrest against stackage, which has http-types 0.12.2 only.
=> Add lower bound for http-types

src/PostgREST/DbRequestBuilder.hs
This causes a compile failure with newer GHC.
I think the duplication is bearable, but if you have a nicer idea to fix this do tell me.
=> Fix non-exhaustive pattern match warning by duplicating a line.

test/create_test_db
- usage information on argument error
- ~~print an export line, making it possible to do:
$ eval `./test/create_test_db`~~
(The export line broke circle-ci.)
=> Make test/create_test_db slightly friendlier

.circleci/config.yml, postgrest.cabal, stack.yaml, test/Feature/ProxySpec.hs, test/Feature/StructureSpec.hs, test/SpecHelper.hs, test/fixtures/jsonschema.sql
Fixes #934.
Embeds https://github.com/gavinwahl/postgres-json-schema.
Feels like gavinwahl/postgres-json-schema should be credited more properly, but I didn't find a good place to do so, and `test/fixtures/jwt.sql` does things the same.
(The tests pass with some other local changes and stackage LTS-13.23, haven't been able to test with cabal or older stackage, but I don't expect problems there.)
=> Change tests to use postgres-json-schema instead of hjsonschema.

test/Feature/RpcSpec.hs, test/Feature/StructureSpec.hs, test/SpecHelper.hs, test/fixtures/schema.sql
In particular, check buggy behavior around embedded quoted JSON
and Postgres versions, compare
https://www.postgresql.org/message-id/D6921B37-BD8E-4664-8D5F-DB3525765DCD%40vllmrt.net
This adds version-bounded tests for the handling of quoted JSON,
and a pending test that documents the assumption that Postgres >=10
intends to parse quoted JSON as a string (similar to how jsonb works
now).
=> Test current behavior with respect to JSON RPC arguments

test/io-tests.sh
This brings the messages for passing/non-passing of individual
tests closer together, making it easier to compare successful
and failing test runs.
=> io-tests: more consistent output

postgrest.cabal, src/PostgREST/Config.hs, stack.yaml
I put together a variant of configurator-ng at https://github.com/robx/configurator-pg that should make a fine replacement for PostgREST's purposes. I believe it supports all features of configurator-ng's that PostgREST uses.
Test coverage is not great, but it does pass the relevant tests of the original configurator-ng, as well as a few extra ones. I also didn't manage to break it by hand. It seems to do fine across ghc versions: https://travis-ci.org/robx/configurator-pg
~~With the exception of proper dependency bounds,~~ the package should be ready to be published. I'd be happy for it to live under the PostgREST github org, but can also put it on hackage from where it's at right now. What do you prefer?
Errors come out of the API a little less structured; on the other hand PostgREST's …
=> Replace configurator-ng by configurator-pg (via stack.yaml/git)

main/Main.hs, src/PostgREST/ApiRequest.hs, src/PostgREST/Config.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Error.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Parsers.hs, src/PostgREST/Types.hs, test/Main.hs
This refactors things a bit to avoid hlint warnings for a somewhat newer hlint version. (These show up when moving to a new stackage release that includes a new hlint on circle-ci.)
Split out from the unwieldy #1319.
=> Fix hlint warnings for hlint v2.1.20

.circleci/config.yml, test/memory-tests.sh
- update stack version (required to build with GHC 8.6 stackage releases)
- remove some unused packages (packdeps, cabal-install) (these aren't used and cause trouble with newer stackage releases)
- avoid rebuilding in `memory-tests.sh` (no idea why this was there)
Split out from #1319 which was getting unwieldy.
=> Tweaks to circle-ci profiling build

postgrest.cabal
I went over the PostgREST dependencies now that the problematic hjsonschema and configurator-ng dependencies are gone, with the results in this PR.
The important changes are:
- Add `base >= 4.9` to force GHC >= 8.0 for the `DuplicateRecordFields` extension.
- Add `swagger2 < 2.4` since it has incompatible changes.
- Relax the base upper bound to `< 4.13`, allowing GHC 8.6.
- Allow Ranged-sets 0.4.0 and protolude 0.2.3.
The current restrictive upper bounds seem to be:
- swagger2 < 2.4 as mentioned above.
- hasql < 1.4 due to incompatible changes in 1.4.
- jose < 0.8 due to an error message change in jose-0.8 that causes a unit test failure.
~~I've included stack configurations that I've built edge cases successfully with.~~ I compiled with tests but didn't actually run the tests in all …
=> Update cabal bounds

postgrest.cabal, src/PostgREST/DbStructure.hs, src/PostgREST/QueryBuilder.hs, stack.yaml
Another PR that's more meant to document/not lose work, not necessarily to be merged. Perhaps at some point it will be desirable to use the latest hasql version?
hasql version 1.4 changes how nullable/non-nullable values are de- and encoded. Perhaps the new API has advantages, but for now it seems to just add verbosity. For now, this PR simply emulates the old API (redundantly in both affected modules).
=> Upgrade hasql to 1.4

.circleci/config.yml, .travis.yml, appveyor.yml, docker/Dockerfile, docker/config.conf, docker/distro_release/Dockerfile.centos6, docker/distro_release/Dockerfile.centos7, docker/distro_release/Dockerfile.ubuntu, docker/distro_release/Dockerfile.ubuntui386, docker/postgrest.conf
Trying to fix the release process and trying to build the binaries manually for each platform. PR not necessarily to be merged, I'm mostly documenting the workarounds I'm trying.
The [ubuntu failure](https://circleci.com/gh/PostgREST/postgrest/3311?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) is a fresh one reported in https://github.com/commercialhaskell/stack/issues/4888. I think It could be solved by pinning the stack version instead of using the latest one in the container.
Right now I'm trying manual builds on an ec2 instance but I keep getting `Unable to commit 1048576 bytes of memory` errors. Seems there's [no](https://www.reddit.com/r/haskell/comments/83ks19/unsure_how_to_deal_with_this_error/) …
=> Fix release process

postgrest.cabal, stack.yaml, test/Feature/AuthSpec.hs
Not sure this is necessarily a good change, but I'd like to put it up for discussion. While raising the cabal bounds, I ran into a test failure with jose 0.8.0 because the `Show` instance of a certain error message changes. (Compare https://github.com/frasertweedale/hs-jose/issues/72.)
This generalizes the corresponding test to pass with both versions. Thoughts:
- I'd assume that PostgREST doesn't want to make any guarantees about precise wording of error messages, hence testing for precise error messages is rather because that's easier to test than because we want to check the precise error message
- the generalised test code is annoyingly complicated
- maybe it would be better to make some better test helper that understands how postgrest errors look `shouldRespondWithError request …
=> Support jose 0.8.0

test/Feature/AndOrParamsSpec.hs
After reading #1249 I've noticed that there are no tests for the `ov` operator being used in array types. This PR addresses that. 
I was hesitant to put the tests in the `AndOrParamsSepc` file and in the `operators inside and/or` context, but since the `range` tests were also there, I've followed that convention.
Besides adding the `ov` tests I've also added tests for the rest of the supported array types operations.
The proper documentation was added in another [PR](https://github.com/PostgREST/postgrest-docs/pull/225).
=> Add tests for overlap operator in array types

appveyor.yml
This is where stack installs GHC versions.
This fixes appveyor builds downloading GHC every single run for me.
=> appveyor: cache stack appdata directory

CHANGELOG.md, src/PostgREST/Types.hs, test/Feature/AndOrParamsSpec.hs, test/Feature/QuerySpec.hs, test/Feature/RpcSpec.hs, test/Main.hs
This PR aims to add `websearch_to_tsquery` support and close #1243.
Since `websearch_to_tsquery` is only supported in `pg` 11.x, I was not sure how to struct the tests.
I've decided to pass the `PgVersion` where needed but, as @steve-chavez said on #1337, I think a `PgOperatorsSpec` test file would be ideal and that would contain most of the conditional tests. Didn't take that route here to keep this PR focused on the new feature.
One thing I've noticed is that `postgrest` gives a `404` error when a `pg` function is not implemented/found. Not sure if that's intentional or not, but I didn't find it intuitive since `pg` functions are more like operators than resources per se.
=> Add websearch_to_tsquery support

CHANGELOG.md, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/Types.hs, test/Feature/HtmlRawOutputSpec.hs, test/Feature/RawOutputTypesSpec.hs, test/Feature/RpcSpec.hs, test/Main.hs, test/SpecHelper.hs
Should solve #1336 and  #1077
It seems functional but needs tests, for now I have only been able to extract rawContentTypes to Config.hs from Types.hs
It was used as a global value in App.hs so I had to make minor changes to a few helper functions.
Posting the WIP here to get feedback on the code while I work on the tests suggested by @steve-chavez
=> Introduced raw-media-types config option 

.travis.yml, appveyor.yml, stack.yaml
Fixes #1334. Also enabling Travis and Appveyor on every PR to ensure builds succeed.
=> Fix windows build

src/PostgREST/DbStructure.hs, test/Feature/StructureSpec.hs, test/fixtures/schema.sql
When testing postgREST's openAPI output, I noticed column descriptions being truncated. It turned out the issue was postgres version 12, which made this change:
([pg12 release notes](https://www.postgresql.org/docs/12/release-12.html#id-1.11.6.5.5.3.6.3))
`
Force information_schema outputs to honor the system-defined maximum 63-byte identifier length (Tom Lane)
`
Which interacts with https://github.com/PostgREST/postgrest/blob/master/src/PostgREST/DbStructure.hs#L440, where comments on columns are being cast to the `sql_identifier` type.
I don't think comments need to be cast to this type (?), so this PR
* makes the test comment a little longer to confirm there is no truncation
* removes the typecast
One can replicate this on this PR by spinning up pg12 as the db with
`docker run --name …
=> Fix long column descriptions being truncated at 63 characters in pg12

src/PostgREST/OpenAPI.hs, test/Feature/StructureSpec.hs
If you use `return=representation`, `select` is useful in `POST` requests.
It already works correctly, but is missing from the OpenAPI spec.
=> Allow select in OpenAPI for POST requests

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/QueryBuilder/Private.hs, src/PostgREST/QueryBuilder/Procedure.hs, src/PostgREST/QueryBuilder/ReadStatement.hs, src/PostgREST/QueryBuilder/WriteStatement.hs, src/PostgREST/RangeQuery.hs, test/Feature/RangeSpec.hs, test/Feature/RpcSpec.hs, test/Feature/StructureSpec.hs, test/Main.hs
For #1378.
- ~~Added support for `Prefer: count=estimate` for obtaining an EXPLAIN statement "Plan Rows". This only works for `GET /table` now. It's possible to extend it and support  `GET /rpc/func` later(it would involve changing how #1266 was implemented).~~ This will be finished on a next PR.
- Added support for HEAD requests. Basically a headers-only GET. This is for better HTTP compliance and will help later on when we focus on caching. Also helps in debugging headers with `curl -I`.
Also includes some reorganization around modules and some changes to the test suite to make it run faster.
=> Add HEAD http method support

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/QueryBuilder/Private.hs, src/PostgREST/Statements.hs, src/PostgREST/Types.hs, test/Feature/QueryLimitedSpec.hs, test/Feature/RangeSpec.hs, test/Main.hs, test/QueryCost.hs, test/SpecHelper.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
This should solve #1378.
For including some reproducible tests when using EXPLAIN, I've used ROWS from [CREATE FUNCTION](https://www.postgresql.org/docs/11/sql-createfunction.html) and wrapped the function in a VIEW.
=> Add support for `Prefer: count=planned/estimated` on GET /table

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/QueryBuilder/Private.hs, src/PostgREST/Types.hs, test/Feature/InsertSpec.hs, test/Feature/RpcSpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Fixes #1301. Continuing the work on #1358.
The main problem was in the `toSourceRelation` function, which was added in this PR https://github.com/PostgREST/postgrest/pull/331. Specifically in https://github.com/PostgREST/postgrest/commit/f02b8381eaeb8b1a26872e8be4e1c9f8830201db#diff-0721c0195214a5855036d6df3d06e076R488-R493.
The first line of that function contained some logic to replace the source tableName from the `Relation` to `pg_source` which was making the self reference case not be found by `findRelation`.
The third line of the function seems to contain some logic for handling the M2M case, however since we have https://github.com/PostgREST/postgrest/issues/1389 reported it probably means that logic never worked.
So I removed the unnecessary lines in that function(which actually …
=> Allow self join resource embedding on PATCH

CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Private/Common.hs, src/PostgREST/Private/QueryFragment.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/QueryBuilder/Private.hs, src/PostgREST/Statements.hs, src/PostgREST/Types.hs, test/Feature/DeleteSpec.hs, test/Feature/InsertSpec.hs, test/Feature/QueryLimitedSpec.hs, test/SpecHelper.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Fixes #1355.
Basically, `return=minimal` was introduced to prevent failure on a POST when the requester doesn't have SELECT rights on the table(see https://github.com/PostgREST/postgrest/issues/399). `return=minimal` is needed because POST by default generates a `Location` header based on the table PK.
However for PATCH/DELETE we don't need to look at the table PK since no special header is added for these methods. So, we can allow these requests to be successful by default w/o `return=minimal` by doing a `RETURNING 1` instead of `RETURNING *` on the generated queries. If `return=minimal` is specified for these methods, we get the same behavior, so no breaking change.
The `RETURNING 1` also ensures we get the correct http status response since we'll know if a row was updated/deleted …
=> Allow PATCH/DELETE w/o return=minimal when not having SELECT privileges

LICENSE, postgrest.cabal, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Error.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/EmbedDisambiguationSpec.hs
As noted in https://github.com/PostgREST/postgrest/pull/1358#issue-300720791 we had the relationships backward(getting the cardinality from parent to child) on the request tree. This made things really confusing, not only for development/debugging but also for error reporting. With this change, we now get a better error message for disambiguation(added in https://github.com/PostgREST/postgrest/pull/1401).
```http
GET /message?select=*,sender(*)
```
```json
{
"details": [
{
"cardinality": "many-to-one",
"source": "test.message[sender]",
"target": "test.person[id]"
},
{
"cardinality": "many-to-one",
"source": "test.message[sender]",
"target": "test.person_detail[id]"
}
],
"hint": "Disambiguate by choosing a relationship from the `details` key",
"message": "More than one relationship was …
```
=> Improve disambiguation error message

CHANGELOG.md, main/Main.hs, postgrest.cabal, src/PostgREST/Config.hs, test/SpecHelper.hs
started working on solving #1408 
Currently I apply a default (changed to 660) whenever the file mode is not specified, or (I think this part is problematic) whenever the mode provided is invalid (not in octal)
I also still need to validate that the octal provided is not above 777
@steve-chavez is this the preferred way to set the permission, or should we rather go with a string in the more readable format "rwxrwxrwx" ?
=> added config option server-unix-socket-mode

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/Error.hs, test/Feature/SingularSpec.hs
Hello
I get Incorrect statuses by using "Accept: application/vnd.pgrst.object+json" with and without "Prefer: return=representation".
for multiple entities on
POST expected 406, receive 201
PATCH expected 406, receive 204
DELETE expected 406, receive 204
for zero entities on
PATCH expected 404, receive 406 
DELETE expected 404, receive 204
=> Improvement singular/plural logic

CHANGELOG.md, src/PostgREST/Config.hs, test/SpecHelper.hs
The default 755 doesn't make sense, should be 777 or 770. IMHO default 777 is better, because PostgREST does authorization.
=> Change default server-unix-socket-mode 755 -> 777

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Parsers.hs, test/Feature/UpsertSpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
This introduces new optional query syntax  `on_conflict=key1,key2,...` for POST, as discussed on #1327.  It enables upsert on keys with unique constraint other than primary keys. 
Given unique constraint on `unique_key`;
```
POST /employees?on_conflict=unique_key HTTP/1.1
Prefer: resolution=merge-duplicates
[
{ "unique_key": 1, "value": "A" }
]
```
performs upsert with `unique_key` instead of primary keys.
For compound unique keys, comma-separated list of column names should be given.
When multiple `on_conflict` terms are given, only the first one is used (like `select`).
Comply with the semantics of `merge-duplicates/ignore-duplicates` in request headers, and `Preference-Applied` in response headers as with upsert on primary keys.
=> Upsert with "Prefer: resolution=merge-duplicates" on specified columns (#1327)

CHANGELOG.md, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Error.hs, src/PostgREST/Parsers.hs, src/PostgREST/Types.hs, test/Feature/EmbedDisambiguationSpec.hs, test/Feature/InsertSpec.hs, test/Feature/QuerySpec.hs, test/Feature/RpcSpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
This makes the previous duck typing rules(undocumented) unnecessary, allows composite FK disambiguation and supports a more flexible naming scheme. 
The previous duck typing can give unexpected matches: see https://github.com/PostgREST/postgrest/issues/1406#issue-520233773 (how it allows embedding `smallmolec`) and this [previous test](https://github.com/PostgREST/postgrest/blob/2e6c78d72349cc5fd6214ee08c4f5f5daf19fac2/test/Feature/EmbedDisambiguationSpec.hs#L41-L131)(which shows how long the error message can get). These make the disambiguation error less helpful.
A migration path(without changing the clients/frontends) for deployments that used the duck typing feature would be renaming the foreign key:
```sql
alter table projects rename constraint projects_client_id_fkey to client;
``` …
=> Allow specifying the constraint name to disambiguate an embedding

BACKERS.md, CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Middleware.hs, src/PostgREST/Private/QueryFragment.hs, src/PostgREST/Statements.hs, src/PostgREST/Types.hs, test/Feature/PgVersion96Spec.hs, test/Feature/QuerySpec.hs, test/Feature/RpcSpec.hs, test/Main.hs, test/SpecHelper.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
Custom headers improvements.
- Fixes #1088.
- Fixes #1168.
- Aiming to Fix #1427. Also thinking to allow overriding Content-Type(requested in https://github.com/PostgREST/postgrest/issues/1422) and Content-Range(requested in chat https://gitter.im/begriffs/postgrest?at=5dcacd06e75b2d5a19bcfb2c).
=> Add response.headers GUC for GET/POST/PATCH/PUT/DELETE

src/PostgREST/App.hs, test/Feature/PgVersion96Spec.hs, test/SpecHelper.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
Should fix a side-effect of implementing #1427. There were empty headers(see https://github.com/PostgREST/postgrest/issues/1427#issuecomment-595907535) being added in POST/PATCH/DELETE(added a test for GET, just in case). This caused proxies to fail the response coming from postgrest.
=> Fix empty headers being added on POST/PATCH/DELETE

src/PostgREST/Config.hs
After searching for a while I found that there is a hidden requirement of at least being 32 characters in the `jwt-secret`.
It would be best to fail on config parsing if this requirement is not satisfied, but my Haskell is not good enough, so hopefully this documentation update will prevent people from making the same mistake in the future.
https://github.com/PostgREST/postgrest/issues/977
=> Improve command line help

docker-compose.yml, test/Dockerfile.test, test/SpecHelper.hs, test/docker-compose.yml
Tried to run the tests with docker according to the docs and came up with this docker-compose file.
Tests can be run with:
`docker-compose up test`
Although the first run will fail, while the database container is still created and not accepting connections, yet - calling it again works. Calling `docker-compose up postgres` separately before would as well.
Some notes regarding the other changes:
- Had to add a couple of missing dependencies to `test/Dockerfile.test`, otherwise it wouldn't build for me.
- Changing `-a` to `-q` for the psql command was needed to stop psql from printing non-ascii characters to stdout, which readProcess would fail to read correctly. It would just throw with `spec: fd:14: hGetContents: invalid argument (invalid byte sequence)`.
=> Add docker-compose file to run tests

CHANGELOG.md, main/Main.hs, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Error.hs, src/PostgREST/Middleware.hs, src/PostgREST/Private/Common.hs, src/PostgREST/Types.hs, test/Feature/JsonOperatorSpec.hs, test/Feature/MultipleSchemaSpec.hs, test/Feature/QuerySpec.hs, test/Main.hs, test/SpecHelper.hs, test/fixtures/data.sql, test/fixtures/database.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql, test/memory-tests.sh
=> multiple schemas in one instance

docker/Dockerfile
Debian stretch has a libpq < 10: https://packages.debian.org/stretch/libpq5.
But buster has libpq >= 10 https://packages.debian.org/buster/libpq5.
Fixes https://github.com/PostgREST/postgrest/issues/1443.
Better to do this now before v7.0.0 so the automatic release can upload the right docker image.
=> Change docker image to support scram-sha-256 auth

test/with_tmp_db
This utility script makes it much simpler to run the tests locally - just run:
```bash
test/with_tmp_db stack test
```
No Docker or a host Postgres cluster needed, and you can always be sure that the tests are run on a fresh database. The only dependencies are the Postgres binaries 'initdb' and 'pg_ctl'.
Happy to provide matching testing docs to postgrest-docs if there is interest! This might also make some CI tasks faster/simpler.
=> Add a script for running the test suite in a local temporary database.

.circleci/config.yml
Currently, the postgres 9.4 job is also responsible for
- running style checks
- caching the dependencies
This has a couple downsides. E.g. it's not apparent at a glance that your PR tests failed due to linter issues, and you need to wait quite a while for these. Secondly, on a dependency update, most of the test jobs do the full compile work in parallel because the cache doesn't exists, and again it's hard to distinguish between postgres version specific failures and a general postgrest build failure.
This PR aims to address those by
- splitting out a style checking target that doesn't even build
- splitting out a dedicated build and cache target, and having the various postgres-version-specific jobs depend on this
=> circleci: Split out dedicated style check and build caching jobs

postgrest.cabal
This allows lens-4.19, network-uri-2.7 and time-0.10. According to
the respective changelogs, none of these should cause trouble.
lens-4.19 is required to build with GHC 8.10.
=> Relax upper bounds for lens, network-uri, time.

.circleci/config.yml
Previously, the linters would use the cached build artefacts from
building postgrest with -fno-spec-constr via stack.yaml. Potentially
passing it to the linter build explicitly will fix recent out-of-memory
issues.
=> circleci: Build linters with memory-saving ghc-options.

.gitignore, default.nix, nix/README.md, nix/nixpkgs-upgrade.nix, nix/nixpkgs-version.nix, nix/overlays/gitignore.nix, postgrest.cabal, shell.nix
This makes it possible to run `nix-build` to build a PostgREST binary. With `nix-shell`, you are dropped into a new shell with the correct GHC and Cabal version for building PostgREST interactively with cached intermediate results.
The version of nixpkgs is pinned to a nixpkgs-unstable version where all dependencies of PostgREST have recently been unbroken - no overrides required anymore! A small utility to upgrade the pinned version is also included - run `nixpkgs-upgrade > nix/nixpkgs-version.nix` in `nix-shell` to upgrade.
=> Basics for building PostgREST with Nix

default.nix, nix/README.md, nix/overlays/postgresql-legacy.nix, nix/tests.nix, shell.nix
Now for some Nix magic :-)
This makes it possible to run the Haskell test suite against all supported PostgreSQL versions, locally and without Docker. Simply run `postgrest-test-spec-all` in nix-shell!
This is on top of #1488, which introduces several improvements to the `with_tmp_db` script.
It's not yet possible to install the test scripts with `nix-env -iA tests` and then run them outside nix-shell directly (e.g. `postgrest-test-spec` instead of `nix-shell --run postgrest-test-spec`), as running the tests currently depends on the build environment provided in our `shell.nix`. This would be nice to have for CI, for example, but I think the PR is already useful in this state.
=>  Run tests against several PostgreSQL versions using Nix

default.nix, nix/overlays/haskell-packages/README.md, nix/overlays/haskell-packages/default.nix, nix/overlays/haskell-packages/protolude.nix
Protolude 0.3, which was added as a dependency with #1496, is not yet available in our pinned version of nixpkgs. This pins the protolude package to fix the issue.
This is a great example I think for how to solve this kind of issues if they should crop up. In the future, this incompatibility would have been automatically flagged to us by the failing Nix build in CI.
=> Pin version 0.3 of protolude in nix

.circleci/config.yml
This would require that a cachix binary cache named 'postgrest' exists and that the CACHIX_SIGNING_KEY is available in the CircleCI environment.
=> Basic CI integration for Nix builds

stack.yaml
They are redundant after being added to postgrest.cabal in #1489
=> Remove ghc options from stack.yaml

postgrest.cabal
Seems like a harmless change: http://hackage.haskell.org/package/base64-bytestring-1.1.0.0/changelog
Would a 7.0.1 release to hackage be feasible, since we've got the GHC 8.10 changes together now? (Actually this one isn't required, but we might as well include it.)
=> Allow base64-bytestring 1.2.

src/PostgREST/DbStructure.hs
First suggestion for some cleanup in the DbStructure queries:
Overall, this should hopefully make the queries easier to read and understand.
I did not change the case or indentation of most of the queries in order to keep the diff a bit smaller.  
--
Before edit:
While working on a PostgREST bindings generator I noticed that the `DbStructure` type contains a lot of redundant info and that the queries for reading the DbStructure from the database are probably more complex than they need to be. This might negatively impact performance and maintainability, but of course changing this part of the project is highly sensitive - so it might not be worth it to change anything here, to be discussed.
An approach to simplifying the structure could be:
1. Simplify the queries in DbStructure.hs as …
=> Simplify the DbStructure queries

default.nix, nix/docker.nix, nix/docker/default.nix, nix/docker/postgrest.conf
This builds a PostgREST Docker image directly from Nix using the static executable. Usage would look something like this:
```bash
$ nix-build -A docker.load
...
$ result/bin/postgrest-docker-load
Loaded image: postgrest/postgrest:latest
Loaded image: postgrest/postgrest:v7.0.0
$ docker push postgrest/postgrest:latest
The push refers to repository [docker.io/postgrest/postgrest]
9c714c7702db: Pushed                                 
latest: digest: sha256:5dba29a5d2c8c257307378da428e46c7d2096d369c717a05a0056596eea2d291 size: 529
```
I re-tagged the built image a pushed it here for testing: [monacoremo/postgrest:latest](
https://hub.docker.com/layers/monacoremo/postgrest/latest/images/sha256-5dba29a5d2c8c257307378da428e46c7d2096d369c717a05a0056596eea2d291)
Benefits:
* Building the image from …
=> Build Docker image from Nix

default.nix, postgrest.cabal, stack.yaml
When doing:
```
cabal upload dist-newstyle/sdist/postgrest-7.0.1.tar.gz
```
The following error is shown:
```
Error: Invalid package
'ghc-options: -Wall -Werror' makes the package very easy to break with
future GHC versions because new GHC versions often add new warnings.
Use just 'ghc-options: -Wall' instead. Alternatively, if you want to
use this, make it conditional based on a Cabal configuration flag
(with 'manual: True' and 'default: False') and enable that flag
during development.
```
Put -Werror in a cabal flag to work around this restriction.
=> cabal: fix upload to hackage

default.nix, nix/patches/default.nix, nix/patches/openssl-split-runtime-dependencies-of-static-builds.patch, nix/static/default.nix, shell.nix
As discussed in #1522, this reduces the closure size of the Nix static build by improving the openssl package.
Benefit: The size of the static docker image should be reduced to 4mb.
Issues: This will trigger a rebuild for all our dependencies that depend on static openssl, so this will almost certainly time out in CI... :-)
=> Reduce size of the static docker image by patching the Nix openssl package

CHANGELOG.md, src/PostgREST/Config.hs
Fix for #1530 
This might be a good compromise - it will show the commit hash in the help text if `.git` is available (e.g. when someone built PostgREST from source), but it will not show `UNKNOWN` if it's not.
There are some cases where `.git` simply can't be available (e.g. when cabal or nix build the package from a sdist tarball from Hackage), so this would give us the best of both worlds I think.
Example when built with nix:
```
Usage: postgrest FILENAME
PostgREST 7.0.1 / create a REST API to an existing Postgres database
```
Example when built with stack:
```
Usage: postgrest FILENAME
PostgREST 7.0.1 (69516b9) / create a REST API to an existing Postgres database
```
=> fix UNKNOWN being shown as git commit hash (fixes #1530)

postgrest.cabal
Builds fine and all tests pass here.
=> Allow aeson 1.5

.circleci/config.yml, .gitignore, default.nix, nix/README.md, nix/tests.nix, shell.nix, test/QueryCost.hs, test/io-tests.sh, test/io-tests/configs/app-settings.config, test/io-tests/configs/base64-secret-from-file.config, test/io-tests/configs/role-claim-key.config, test/io-tests/configs/secret-from-file.config, test/io-tests/configs/simple.config, test/io-tests/configs/unix-socket.config, test/io-tests/dburis/uri.noeol, test/io-tests/dburis/uri.txt, test/memory-tests.sh, test/memory-tests/config
As discussed in #1535, this integrates the io and memory tests with the Nix setup.
A few notes:
* The io and memory scripts are now independent from stack and take the postgrest executable from the PATH (also reflected in the stack CI jobs)
* This PR touches quite a few files because the db URI needed to be parameterized (the `with_tmp_db` will never be in the same location) - otherwise I tried to keep the changes minimal
* The tests still feels a bit hacky/brittle - the nmap dependency could probably be removed (its process not being properly terminated currently), as could the dependency on a hardcoded port. Shellcheck throws many warnings on the two scripts, but I left as much as possible as it was for this PR :-)
* The Nix test scripts now depend on the final executables (both a …
=> Nixify io and memory tests

CHANGELOG.md, nix/tests.nix, src/PostgREST/App.hs, src/PostgREST/Error.hs, src/PostgREST/Private/QueryFragment.hs, src/PostgREST/Statements.hs, test/Feature/PgVersion96Spec.hs, test/fixtures/schema.sql
Fixes https://github.com/PostgREST/postgrest/issues/1525.
A quick feature for this new batch of enhancements!
I think this should finish the [HTTP Logic](http://postgrest.org/en/v7.0.0/api.html#http-logic) features. I should turn that on its own page, the API reference is getting big.
=> Allow http status override through response.status guc

.circleci/config.yml, CHANGELOG.md, main/Main.hs, nix/docker/default.nix, nix/docker/postgrest.conf, nix/overlays/haskell-packages/default.nix, nix/patches/default.nix, nix/patches/static-haskell-nix-hasql-notifications-openssl-linking-fix.patch, nix/static-haskell-package.nix, postgrest.cabal, src/PostgREST/Config.hs, stack.yaml, test/SpecHelper.hs
Fixes #1512
Helps on environments where you can't send unix signals(Windows, managed
containers). Also provides better UX for schema reloads - NOTIFY
can be send from pg clients(psql, pgadmin).
By default, `NOTIFY pgrst` - with no payload - should be done to reload
the schema cache. Notifications with a payload will be ignored.
The channel name can be configured with `db-channel`.
~~There's limitation for now, if the LISTEN connection is lost the
connection won't be retried.~~
**Edit**: The LISTEN connection is retried if lost now. With exponential backoff, same way as the pool.
=> Allow schema cache reloading with NOTIFY

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/Auth.hs, src/PostgREST/Middleware.hs
Fixes https://github.com/PostgREST/postgrest/issues/1094.
Expired JWTs were doing an empty BEGIN/COMMIT in the db.
For testing this manually, do the following request on the master branch:
```bash
curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIiA6ICJ3ZWJ1c2VyIiwgImV4cCIgOiAxNTkzNjQ0MTc3fQ.p0M9dhxX9RMkq7ZwTdWpjWQHLuSH-0zEudZ2vm01tNo" localhost:3000/authors_only
{"message":"JWT expired"}
```
The `postgrest.conf` should have `jwt-secret=reallyreallyreallyreallyverysafe`.
And the empty BEGIN/COMMIT should show in the [db logs](http://postgrest.org/en/v7.0.0/admin.html#database-logs):
```
2020-07-01 23:00:37.171 GMT [25897] LOG:  00000: execute 0: BEGIN ISOLATION LEVEL READ COMMITTED READ ONLY
2020-07-01 23:00:37.171 GMT [25897] LOCATION:  exec_execute_message, …
```
=> Fix expired JWTs starting an empty transaction

CHANGELOG.md, main/Main.hs, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Auth.hs, src/PostgREST/Config.hs, src/PostgREST/Middleware.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Parsers.hs, src/PostgREST/Private/ProxyUri.hs, src/PostgREST/Types.hs, test/Main.hs, test/SpecHelper.hs, test/io-tests.sh, test/io-tests/configs/sigusr2-settings.config
Continuing the work on https://github.com/PostgREST/postgrest/pull/1289. Should also fix https://github.com/PostgREST/postgrest/issues/1119.
Considerations:
- SIGUSR2 only re-reads the config, but doesn't reload the schema cache. This is because `jwt-secret` and other settings don't deal with the db. Reloading the cache on a `jwt-secret` update would be wasteful.
- From the above, if a `db-schema` changes, a SIGUSR2 + SIGUSR1 would be needed for a correct schema cache reload.
- If the config file path has changed, the reload will fail(and show an error) but postgrest will continue to work. The reloading will be done in a different thread. This is probably not an issue in production since services have an absolute path defined for the config.
- If the config file has an invalid config …
=> Enable config file re-reading with SIGUSR2

nix/nixpkgs-version.nix
As discussed, it makes sense that we track nixpkgs-unstable until our dependencies are in the next stable version.
This upgrades `libpq` to the version from PostgreSQL 12.3 (from 12.1). No other major changes as far as I could see.
=> Bump nixpkgs pin to current unstable

CHANGELOG.md, main/Main.hs, src/PostgREST/App.hs, src/PostgREST/Error.hs, test/io-tests.sh
The current SIGUSR1 schema cache reload causes downtime for some milliseconds(depending on schema size). To test this:
```bash
postgrest conf
killall -SIGUSR1 postgrest & curl localhost:3000/projects
{"message":"Database connection lost, retrying the connection."}
```
This is because the current reload(implemented in https://github.com/PostgREST/postgrest/pull/869) was meant for a single schema and the error message prevented getting a response from a stale schema cache.
(The error message is inaccurate when the db connection is actually up and a reload is done).
But now that we support multiple schemas in `db-schema`, is not appropriate to err a response on an up-to-date schema just because a newly added one can be stale.
So with this PR, responses can come from a stale cache. Embedding …
=> Schema cache reload with zero downtime

CHANGELOG.md, src/PostgREST/Error.hs, test/Feature/RpcSpec.hs
As discussed in https://github.com/PostgREST/postgrest/pull/1552#issuecomment-657863333
I changed the CHANGELOG to include this changed behaviour, but still need to change the docs, I guess ;)
=> Return 405 Method not Allowed for GET of volatile RPC instead of 500

postgrest.cabal
Relax some bounds for stackage, compare https://github.com/commercialhaskell/stackage/issues/5598 and https://github.com/commercialhaskell/stackage/issues/5597
=> Allow base64-bytestring 1.2 and optparse-applicative 0.16

postgrest.cabal
See https://github.com/commercialhaskell/stackage/issues/5655.
If this passes CI without changes to source code, would be nice to add to add to hackage as a revision.
=> Allow wai-extra 3.1

CHANGELOG.md, src/PostgREST/Error.hs
=> Fix error messages on connection failure for postgres on localized Windows

postgrest.cabal
Changelog:
- Only serve static files on HEAD or GET requests.
The old behaviour seemed wrong, but I'm not 100% sure we don't rely on it. Let's see what the tests say. :)
Stackage tracking issue: https://github.com/commercialhaskell/stackage/issues/5672
=> Allow wai-middleware-static 0.9

CHANGELOG.md, main/Main.hs, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/Middleware.hs, src/PostgREST/Types.hs, test/Main.hs, test/SpecHelper.hs
Add the `log-level` config option. The admitted values are:
- `crit`: No requests are logged. Only startup and db connection recovery messages are logged.
- `error`: Only failed requests(status >=400) are logged.
- `info`: All requests are logged. This is the only level we've been offering until now.
Partly addresses: https://github.com/PostgREST/postgrest/issues/540 (`debug` level for another PR).
According to my load tests, the lower levels give more requests per second:
- `crit`: 208 req/s more on average.
- `error`: 170 req/s more on average.
Which makes sense because our default `info` level doesn't buffer the log messages. It writes them to disk, directly.
The `error` level is a bit slower because of the status filtering.
- Should we change the default log level to `error`? It …
=> Add log level config

stack.yaml.lock
When I run `make check` on the current master branch, I get this diff.
The changes to `stack.yaml.lock` appear whenever I run `make test`.
Seems like the whitespace stuff for imports only appeared after I updated stylish-haskell. Right now, I can't use `make style` because the resulting diff is just too annoying.
Is this something where I have to change my config somehow? Or should we just merge those changes?
=> make check on current master

.circleci/config.yml
- Removed CircleCI caching for Nix build jobs. It's finicky (e.g. https://github.com/PostgREST/postgrest/pull/1617#issuecomment-707868410) and is not really worth it build time wise - Nix will always provide all dependencies and we only ever build PostgREST and the test suite with cabal-install, which is relatively quick
- Merged nix-build and nix-test - separating those steps makes things more complicated than they need to be and negatively impacts performance for PRs, as we can't push to cachix for those
=> Simplify Nix CI jobs

appveyor.yml, main/Main.hs
Seems like the appveyor build is silently throwing errors right now. This is because the error code is swallowed. This change should make it pass on a timeout, but fail on every other error.
=> fix appveyor build script

.cirrus.yml
So I had a look at the cirrus build, that takes like forever all the time.
Looking at the output, it seems to me like the cabal cache is not updated properly and all dependencies are built again every time. The cache update is based on the contents of `postgrest.cabal` - but since there are version ranges given in this file, I could imagine that cabal still decides to download newer packages and not use those from cache.
I tried removing the `fingerprint_script` line. Now it should default back to `reupload_on_changes: true` and scan the `~/.cabal` folder for changes to upload.
Let's see what happens when I trigger this twice.
=> improve cirrus build time by properly using cabal cache

.circleci/config.yml
this is just to debug - nothing to merge, yet.
Right now, `stack-test` often fails with a segmentation fault during the io-tests. I tried to reproduce locally, but couldn't. Here, I ripped out all the other CI pipelines (no need to run them loads of times) and removed some `> /dev/null` redirections. Hopefully I can reproduce the error when running the CI pipeline a couple of times and get more useful logging output.
Let's see what happens.
=> remove io tests from stack-test because of random segmentation faults

src/PostgREST/App.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/Private/QueryFragment.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Statements.hs, src/PostgREST/Types.hs, test/QueryCost.hs
Improves performance by not utf8 encoding the full queries with `encodeUtf8`(done in `unicodeStatement`). It only encodes certain parts like pg identifiers and literals.
I get around ~220 req/s more on my load tests more with this change.
This is also a gradual step needed to use the Snippet type from [hasql-dynamic-statements](http://hackage.haskell.org/package/hasql-dynamic-statements-0.3.1/docs/Hasql-DynamicStatements-Snippet.html). We'll get prepared statements for GET when this library is integrated.
=> perf: change Text queries to ByteString

.circleci/config.yml, .travis.yml, README.md, nix/README.md, test/io-tests.sh
Wouldn't it be good to have code coverage tools in CI as well?
I have found 3 packages that send hpc coverage results to one of the ci services, but only `stack-hpc-coveralls` seems to be compatible to stack. The other 2 use cabal.
I thought it would make sense to use `stack-test` for that purpose. I'm not sure why that was specifically targeting the oldest supported PG version and changed that to the latest. Coverage results seem to be more interesting against the latest version, as that might touch more features, which are not enabled for older versions!?
To make this work, @steve-chavez, you would have to register the postgrest repo with coveralls.io. I'm not sure whether we need to add a token somewhere. The coveralls docs suggest we have to, but the source code for …
=> ci: add coveralls.io integration

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/DbRequestBuilder.hs, src/PostgREST/DbStructure.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/QueryBuilder.hs, src/PostgREST/Types.hs, test/Feature/RpcSpec.hs, test/Feature/StructureSpec.hs, test/QueryCost.hs, test/fixtures/schema.sql
Remake of #1552 - new PR for a clean history and easier discussion. Resolves #1470.
This implements variadic arguments for RPCs by either:
- using JSON arrays in the function body or
- using repeated query params
See the test cases for some examples.
To be able to implement this, I had to do the following in 3 commits
- The first commit just improved the "accepts a variety of arguments" test case to include arrays. I had that done in the other PR already and included them here mainly to make sure I'm not breaking regular arrays with everything that follows.
- The second commit is "just" a refactor. The basic idea is to move the column parsing and `findProc` from App to ApiRequest, to be able to later use the result of `findProc` already when parsing the query string - to make sure to only …
=> Allow calling variadic functions with repeated parameters

src/PostgREST/DbRequestBuilder.hs
I updated stylish-haskell again (after it was broken in #1616 at first) and now I only get a small diff, that doesn't look too bad.
Couldn't get nix-shell to run yet, so I'm not sure whether the older stylish-haskell will revert this change... Let's see whether CI complains!
=> run stylish-haskell v0.12.1.0

.circleci/config.yml, .cirrus.yml, .travis.yml, appveyor.yml, nix/release/default.nix
Fixes #1645. Adds nightly builds for Linux, Windows, OSX, FreeBSD. The results would look like this(using my own repos for the examples): 
- For github: https://github.com/steve-chavez/postgrest/releases/tag/nightly.
- For dockerhub: https://hub.docker.com/layers/stevechavez/postgrest/nightly-2020-11-09-bd4ddd0/images/sha256-4bade454085b08006f6d307a4b0deec63c769d7c7500bf4a55dfee972cbedd0d
Didn't like the idea of spamming the GitHub releases page and creating tags with every build, so all the nightly builds will be added on a single release. For dockerhub, new tags will be created.
The workflow is partly manual and partly automated. These manual steps are required for releasing a nightly:
```bash
git tag -f nightly
git push <remote> nightly -f
```
Then all of the CI's process should kick …
=> Add nightly builds

CHANGELOG.md, main/Main.hs, src/PostgREST/DbStructure.hs, test/Feature/ExtraSearchPathSpec.hs, test/Feature/QuerySpec.hs, test/Main.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
Resolves #1607.
Changes the `allSourceColumns` query to recurse, when the base relation is still a view or materialized view. The query now returns the "true" base columns through multiple view layers, enabling the embedding of views of views of... you know!
=> Enable embedding through multiple layers of views recursively

CHANGELOG.md, src/PostgREST/DbStructure.hs, test/Feature/QuerySpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Restricting M2M mapping detection to single foreign key column seems to be unreasonable. I can't see how can it be a problem (by scanning the code), therefore lifted the unnecessary restriction. All tests run fine. Everything is working fine (at least in my app). 
Added some minor fixes. 
- It is impossible for groupWith to return empty foldable, therefore filtering empty is unreasonable and confusing. 
- Text concatenation is ambiguous. myschema_my.table and myschema.my_table should be different, but concatenating them with "_" they evaluate the same which is undesirable and leads to a nasty bug if both schemas are accessible. (Very rare...but still).
=> Removing single column limit from join table M2M mapping detection.

CHANGELOG.md, src/PostgREST/DbStructure.hs, test/Feature/AuthSpec.hs, test/Feature/DeleteSpec.hs, test/Feature/EmbedDisambiguationSpec.hs, test/Feature/InsertSpec.hs, test/Feature/JsonOperatorSpec.hs, test/Feature/QuerySpec.hs, test/Feature/RpcSpec.hs, test/Feature/SingularSpec.hs, test/Feature/UpdateSpec.hs, test/Feature/UpsertSpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
So #1615 is rather lengthy. Most of that stuff you already approved, @steve-chavez.
So this is the first 4 commits of that branch, so we can merge them already. Had quite a few merge conflicts when rebasing on master after development has progressed there, and I don't need to repeat that when possible ;)
Resolves #1469.
=> Fix rpc return part1

CHANGELOG.md, test/fixtures/schema.sql
Resolves #1638.
This has in fact already been fixed in e08bb3a197cbc03e5c623b9847651880955e45b8.
Just added another function with the same name as a set-returning function to the fixtures. Before this commit, this breaks a test, but now it passes. Confirms, that it is fixed already.
=> Add test to ignore functions unnamed arguments for rpc disambiguation

CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/Types.hs, test/Feature/RollbackSpec.hs, test/Main.hs, test/SpecHelper.hs
Resolves #1598.
In that issue we discussed `Prefer: rollback` vs. `Prefer: tx=rollback`. I implemented the latter and also added `Prefer: tx=commit` (the default) for completeness (see #1656 as well).
---
This would also allow adding another config option to use `rollback` as the default, to be overwritten with `Prefer: tx=commit`. This would be something that I would run the test environment in my projects with, because those automated tests should almost never change the database for real.
Now that I write this, I wonder whether we should change the config option `allow-rollback` to something like `allow-prefer-tx` now. This would allow us to allow/deny the use of `tx=commit`, when the default is `rollback`.
The combo of `tx-default = rollback` and `allow-prefer-tx = false` could be a …
=> Add support for Prefer tx=rollback

.circleci/config.yml, default.nix, nix/README.md, nix/devtools.nix, nix/docker/default.nix, nix/nixpkgs-upgrade.nix, nix/overlays/checked-shell-script/checked-shell-script.nix, nix/overlays/checked-shell-script/default.nix, nix/overlays/default.nix, nix/release/default.nix, nix/style.nix, nix/tests.nix, shell.nix
@wolfgangwalther has started using the nix tooling and had a plethora of excellent ideas to improve the developer experience. Should not be too difficult to realize, so tracking here:
Tbd/potentially for later PRs:
* integrate coverage
* option to preserve temporary dbs and explore them
* script to run postgrest against a temporary db
Edit: tracking those in #1671
=> Improve dev tools in the Nix environment

.circleci/config.yml, nix/README.md, nix/tests.nix, shell.nix, test/io-tests.sh
As mentioned in #1666 and #1671, this runs the io-tests with `cabal v2-exec`. I need to use those currently, so went ahead with that.
This does not change the memory tests, those are going to be a bit trickier.
Would love to have your feedback on this @monacoremo.
=> Use cabal v2-exec to run io tests, include io tests in nix-shell by default; remove obsolete ncat dependency

test/Feature/AndOrParamsSpec.hs, test/Feature/DeleteSpec.hs, test/Feature/EmbedDisambiguationSpec.hs, test/Feature/InsertSpec.hs, test/Feature/JsonOperatorSpec.hs, test/Feature/MultipleSchemaSpec.hs, test/Feature/QueryLimitedSpec.hs, test/Feature/QuerySpec.hs, test/Feature/RangeSpec.hs, test/Feature/RollbackSpec.hs, test/Feature/RpcPreRequestGucsSpec.hs, test/Feature/RpcSpec.hs, test/Feature/SingularSpec.hs, test/Feature/UnicodeSpec.hs, test/Feature/UpdateSpec.hs, test/Feature/UpsertSpec.hs, test/Main.hs, test/SpecHelper.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Follow-up on #1659:
> And then for another PR: Make rollback the default for our spec-tests. This will require quite a bit of cleanup. My goal would be to be able to run the whole test suite multiple times against the same database without recreating the schema.
This is based on the other PR, so the diff is a bit longer than it should be. Still, it's huge. I hope it looks better with "Hide whitespace changes" turned on.
Quick guide on how to look at this:
- Everything in `src/...` is from the other PR. Ignore here.
- Changes have been made to `test/Main.hs` and `test/SpecHelper.hs`. Removed the schema reloading, re-ordered the tests and enabled `transaction-rollback = true`. This caused a lot of broken tests.
- Everything in `test/Feature/...` + `test/fixtures/...` is fixing those tests, …
=> Make transaction-rollback=true the default for test-suite

test/io-tests.sh, test/with_tmp_db
We used to get some "segmentation faults" for the io tests in CI. I am currently trying to set up a nix-based coverage script - and ran into those errors again.
It turns out that the seg fault is just bash complaining, because some traps are set where bash tries to kill itself multiple times. Something similar happenend in `with_tmp_db`, where those calls led to errors regarding the log file, because it didn't exist anymore.
After fixing all those traps and obsolete output I was left with.. nothing. The actual error that I was looking for was still hidden, because all postgrest stderr is piped to `/dev/null` in the `io-tests.sh`. Some errors during the test are expected, so it's fine to filter those out, but in my case I had some startup errors for postgrest due to missing libraries and …
=> improve error output for io-tests and with_tmp_db

nix/devtools.nix, nix/style.nix, nix/tests.nix, shell.nix, test/io-tests.sh, test/io-tests/configs/app-settings.config
This PR does:
* speed up io tests
* avoid infinite loop while watching io tests
* improve auto-complete with postgrest-watch postgrest-run
* detect when files are added or deleted
TODO:
=> dev: improve postgrest-watch experience

CHANGELOG.md, src/PostgREST/Middleware.hs, src/PostgREST/Private/Common.hs, src/PostgREST/Private/QueryFragment.hs, src/PostgREST/QueryBuilder.hs
Changes how we set the GUCs from using SET LOCALs to using [set_config](https://www.postgresql.org/docs/current/functions-admin.html#FUNCTIONS-ADMIN-SET-TABLE).
We go from this:
```sql
SET LOCAL search_path = 'test', 'public';SET LOCAL "role" = 'postgres';SET LOCAL "request.jwt.claim.role" = 'postgres';
SET LOCAL "request.method" = 'GET';SET LOCAL "request.path" = '/projects';SET LOCAL "request.header.host" = 'localhost:3000';
SET LOCAL "request.header.connection" = 'keep-alive';SET LOCAL "request.header.upgrade-insecure-requests" = '1';
SET LOCAL "request.header.user-agent" = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36';
SET LOCAL "request.header.sec-fetch-user" = '?1';SET LOCAL "request.header.accept" = …
```
=> Change SET LOCAL gucs to set_config

main/Main.hs, src/PostgREST/Error.hs, src/PostgREST/Types.hs
When the "Failed to load the schema cache" error happens, the connection is not retried. This can be reproduced on https://github.com/PostgREST/postgrest/compare/master...steve-chavez:failed-to-load-schema.
This error is actually a regression that happened on #1542(check this [deleted comment](https://github.com/PostgREST/postgrest/pull/1542/files#diff-aefb86a77d8df9fc673b38b36a8d87d1eb9c6e16ba2cfc2bb3b807d7f005df61L61-L62)).
=> fix: retry connection on failed schema cache load

src/PostgREST/DbStructure.hs, test/Feature/QuerySpec.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
Resolves #1608, resolves #1635.
This is on top of the changes in #1625. Will rebase, once the other one is merged.
Background:
Due to the nested nature of `pg_node_tree`, it is not possible to correctly parse all kinds of views with just a regex. This replaces that parsing by using the postgres `json` parser. First the `pg_node_tree` is reformatted to proper json with a series of `replace()` and `regexp_replace()` calls. After that, a cast to json is possible and the TargetEntries can easily be extracted.
The json that is produced is a very much stripped down version of the node tree, that has just two parts left:
- the fields that we require for our query
- the whole structure, i.e. all object and array brackets with some empty string keys, where required
It looks roughly like this: …
=> Fix embedding through views with subqueries inside function calls

src/PostgREST/App.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Private/QueryFragment.hs, src/PostgREST/Statements.hs, src/PostgREST/Types.hs, test/Feature/QuerySpec.hs, test/Feature/RpcSpec.hs, test/fixtures/schema.sql
This PR fixes a couple of things regarding the returns of RPC calls:
1. The 1st commit is something that I discovered while fixing the other stuff and has - to my knowledge - not been reported, so far. This comment tells the whole story: `_   -> Scalar qi -- 'b'ase, 'd'omain, 'e'num, 'r'ange`. Domain types were always treated as `Scalar` here. That, of course, is not correct once a domain has a composite base type (this seems to be possible to do starting with PG 11, which might explain why it was done that way earlier on). Test added, test failed - confirmed.
The solution is to add a recursive CTE to the proc query, to replace the return type characteristics with those of the base type for domains. The recursive query makes sure, that this works also for domains of domains of domains.... …
=> Fix RPC returns

test/Feature/InsertSpec.hs, test/Feature/RollbackSpec.hs, test/Feature/UpdateSpec.hs, test/Main.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
Now that we are able to run the spec tests repeatedly on the same database, I was wondering whether we could run them in parallel as well. With a few more tests adjusted, this is possible.
I only get an improvment of running postgrest-test-spec-all of about 20-25%. It took ~ 1 min before for me, ~45 seconds now. I had hoped for more, but hey it's still an improvement!
=> run spec tests in parallel

main/Main.hs, nix/tests.nix, postgrest.cabal, src/PostgREST/Config.hs, src/PostgREST/Types.hs
Add a `--dump-schema` option that pretty-prints the schema cache and exits.
This does not pretty print at this stage - thinking about outputting JSON, which would require adding some Aeson derivations on the DbStructure types. WDYT?
=> Add --dump-schema

nix/README.md, nix/devtools.nix, nix/overlays/checked-shell-script/checked-shell-script.nix, nix/style.nix, nix/tests.nix, test/with_tmp_db
As discussed in https://github.com/PostgREST/postgrest/pull/1694#discussion_r545403933
@monacoremo: I felt like a `postgrest-rootdir` was not necessary and just added it to the checked-shell-script wrapper. What do you think?
=> nix: add "cd $rootdir" to all shell scripts via checked-shell-script

nix/README.md, nix/tests.nix, test/io-tests/configs/app-settings.config, test/io-tests/configs/base64-secret-from-file.config, test/io-tests/configs/dburi-from-file.config, test/io-tests/configs/role-claim-key.config, test/io-tests/configs/secret-from-file.config, test/io-tests/configs/sigusr2-settings.config, test/io-tests/configs/simple.config, test/io-tests/test_io.py, test/memory-tests.sh, test/with_tmp_db
Will rebase on #1691 once merged
Edit: rebased, and refactored a bit using our new env vars. The environment that we run the PostgREST process in is now fully explicit and controlled, much better than the setup we had before.
=> Improvements to io-tests

nix/UPGRADE.md, nix/devtools.nix, nix/docker/default.nix, nix/nixpkgs-upgrade.nix, nix/overlays/checked-shell-script/checked-shell-script.nix, nix/release/default.nix, nix/style.nix, nix/tests.nix
This adds docs to every `checkedShellScript`-based script that we have in our Nix setup.
Need to figure out how to best use the `docs` attribute in `checkShellScript`, but this is already useful as is I think.
=> Add docs to all checkShellScripts in Nix

main/Main.hs
When merging #1691 I introduced the failing appveyor windows build. It didn't fail when merging, because the windows build was not finished yet (cancelled after timeout). Now it has been failing ever since. I first thought this was a caching issue, but it turns out it is for real - one of the imports is not used for the Windows build.
=> Fix "unused-imports" warning for windows build

.circleci/config.yml, .codecov.yml, .gitignore, default.nix, nix/devtools.nix, nix/tests.nix, postgrest.cabal, stack.yaml, test/Feature/InsertSpec.hs, test/Feature/QueryLimitedSpec.hs, test/Feature/RollbackSpec.hs, test/Feature/RpcPreRequestGucsSpec.hs, test/Feature/UnicodeSpec.hs, test/Feature/UpdateSpec.hs, test/QueryCost.hs, test/io-tests/test_io.py
`postgrest-coverage` is here.
Some background on the why and how: When I introduced code coverage in CI a while back, I went with a combination of stack, coveralls, `stack-hpc-coveralls` and travis. I turns out that this has many disadvantages. This PR replaces everything, and we are now using cabal, codecov, `hpc-codecov` and circleci.
This has the following advantages:
- Coveralls does not support partial line coverage at all - codecov does. Of course some information is still lost, because the hpc coverage info is very detailed for expressions, etc. - but having that marked as partial line coverage instead of "no coverage at all" will hopefully be much better.
- Only travis supported token-less upload of coverage reports for coveralls. For codecov, we can do the same from circleci. …
=> Add postgrest-coverage to show and upload hpc reports to codecov

nix/tests.nix, test/io-tests/test_io.py
Before, postgrest was killed after each test and no coverage data was saved.
Now the process is terminated gracefully via SIGTERM first to allow writing the .tix file.
To avoid concurrency issues when executing the io tests in parallel, each io test case yields a separate tix file now.
=> Fix io tests not collecting coverage data when using run()

nix/tests.nix
This fixes the problem mentioned in https://github.com/PostgREST/postgrest/pull/1694#discussion_r549749331.
Inside `nix-shell` the environment variable `LOCALE_ARCHIVE` is set - but when installing with `nix-env` it is not. Apparently this throws off `hpc markup`... no idea why.
=> Fix postgrest-coverage throwing error when installed with nix-env

.codecov.yml, README.md
The master branch now has coverage, so we can add the badge in the Readme.
Until now, I have not seen any GitHub checks / status reports from codecov, yet. I have requested to install the codecov App in the repo, @steve-chavez will have to approve it.
Keeping this as WIP, until that's done to test the codecov status reports.
=> Codecov config

nix/overlays/checked-shell-script/checked-shell-script.nix, postgrest.cabal
Since we enabled the hpc flags on every build (even without `postgrest-coverage`), `.tix` files are created on every command. Sometimes regular commands (test-spec, test-io, build, run) will fail because of those stale `.tix` files.
Here, I add a tmp `HPCTIXFILE` location for every nix script to avoid those files from ever appearing. This can be overriden either from inside the script by setting the `HPCTIXFILE` location manually (as is done in `postgrest-coverage`) or from the outside by setting `HPCTIXFILE` before running the command.
=> nix: Fix build errors with stale .tix files present

src/PostgREST/DbRequestBuilder.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Error.hs, src/PostgREST/Private/Common.hs, src/PostgREST/Types.hs, test/fixtures/schema.sql
=> Refactor dbStructure.hs

.circleci/config.yml, nix/README.md, nix/devtools.nix, nix/tests.nix, shell.nix
I need to run `postgrest-test-io` or `postgrest-run --dump-schema` against an older version. Right now they always use the latest pg version. If I do `test/with_tmp_db postgrest-run`, it will use my hosts pg version, but that won't really help.
Therefore I introduced `postgrest-with-postgresql-xx` commands. They replace the `postgrest-test-spec-postgresql-xx` commands, but are more flexible, because they take any other command as argument. The same goes for `postgrest-with-all`.
=> nix: Add postgrest-with-* tools

main/Main.hs, main/UnixSocket.hs, src/PostgREST/App.hs, src/PostgREST/Auth.hs, src/PostgREST/Config.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Private/ProxyUri.hs, test/SpecHelper.hs, test/fixtures/schema.sql, test/io-tests/fixtures.yaml, test/io-tests/test_io.py
Fixes a bug in the recently added https://github.com/PostgREST/postgrest/pull/1729.
When altering a config with an invalid setting and reloading:
```sql
ALTER ROLE postgrest_test_authenticator SET pgrst."jwt-role-claim-key" = 'invalid';
NOTIFY pgrst, 'reload config';
```
postgrest will respond with:
```
Retrying listening for notifications on the pgrst channel..
Attempting to connect to the database...
Connection successful
Listening for notifications on the pgrst channel
Schema cache loaded
```
This is because the `readConfig` function panicked and killed the `listener` thread.
Don't panic on `readConfig` and instead do it on the `Main.hs` module.
So with this change, postgrest will respond with:
```
Failed config reload. Error in config: "\"failed to parse role-claim-key value (asdf)\" …
```
=> Fix notify config

.cirrus.yml
We were using FreeBSD 12.1, which is EOL: https://www.freebsd.org/security/#sup. (That appears like it will happen regularly within 3 months of a point release.)
=> freebsd ci: attempting to fix build failure

postgrest.cabal
There appear to be no significant changes to the release. Addresses https://github.com/commercialhaskell/stackage/issues/5874. A hackage revision would likely be fine (but I'm not sure how far `main` has diverged from 7.0.1 by now).
Built locally (but didn't run tests) with `stack.yaml` below. Requires swagger2 to also have its bounds relaxed (https://github.com/GetShopTV/swagger2/pull/223), but we'll be able to pick up the swagger2 update automatically since it's likely to stay on 2.6.*.
```
resolver: lts-16.26 # 2020-12-13, GHC 8.8.4
nix:
packages:
- pcre
- pkgconfig
- postgresql
- zlib
pure: false
extra-deps:
- protolude-0.3.0@sha256:8361b811b420585b122a7ba715aa5923834db6e8c36309bf267df2dbf66b95ef,2693
- hasql-notifications-0.1.0.0@sha256:9ab112d2bb5da0d55abd65f0d27a7bb1dc4aeb792518d9a2 …
```
=> Allow lens-5.0

.circleci/config.yml, test/Feature/InsertSpec.hs, test/SpecHelper.hs
This is prompted by a report that postgrest tests fail with newest hashable due to unstable order in aeson output: https://github.com/commercialhaskell/stackage/issues/5878. Stackage doesn't actually run postgrest tests, so this change isn't required, but the underlying issue *does* cause test failures.
The PR addresses two issues:
- cryptonite-0.27 build failure on the legacy circleci base image
- test failures due to changed JSON ordering with hashable-1.3.1.0
There's a bit more detail in the commit messages.
=> fix tests to be independent of JSON ordering

.cirrus.yml
Updated CI for using PostgreSQL 12 (as a default FreeBSD version) instead 9.5 (as an EOS version).
=> cirrusci: update FreeBSD pkg

.gitignore, default.nix, nix/devtools.nix, nix/hsie/Main.hs, nix/hsie/README.md, nix/hsie/default.nix, postgrest.cabal, shell.nix, src/PostgREST/Config.hs, src/PostgREST/Private/QueryFragment.hs, src/PostgREST/Statements.hs
This uses the actual GHC parser, so it should be fairly robust. Works on both our Haskell modules and the ones generated with `-ddump-minmal-imports`.
To use:
```bash
nix-build -A haskellimports
./result src/PostgREST/App.hs
```
Example output so far:
```csv
source,moduleName,impQualified,impAs,impHiding,symbolName
src/PostgREST/App.hs,Control.Monad.Except,false,,false,liftEither
src/PostgREST/App.hs,Data.Either.Combinators,false,,false,mapLeft
src/PostgREST/App.hs,Data.IORef,false,,false,IORef
src/PostgREST/App.hs,Data.IORef,false,,false,readIORef
src/PostgREST/App.hs,Data.List,false,,false,union
src/PostgREST/App.hs,Data.Time.Clock,false,,false,UTCTime
src/PostgREST/App.hs,Data.ByteString.Char8,true,BS8,,
src/PostgREST/App.hs,Data.ByteString.Lazy,true,LBS,, …
```
=> Nix: Add a tool for checking Haskell imports and exports

src/PostgREST/Private/QueryFragment.hs, test/Feature/RpcSpec.hs, test/fixtures/schema.sql
Fixes #1762. Includes a test for functions returning an integer with null value.
=> Void functions return null instead of empty body

test/with_tmp_db
=> Fix incorrect use of bash variable

nix/devtools.nix
Just tried to run `postgrest-hsie-graph-modules` and got this:
```bash
[...]/postgrest-hsie-graph-modules: line 11: $1: unbound variable
```
Had to figure out that I need to pass the output filename as an argument.
With this change, I now get:
```bash
[...]/postgrest-hsie-graph-modules: line 11: 1: outfile not set
```
=> nix: show better error messages for missing arguments in hsie scripts

postgrest.cabal
I was able to reproduce locally: Running `postgrest-coverage` repeatedly resulted in different `spec.tix` files. Removing `-threaded` from the spec test ghc-options made it consistent across runs again.
Let's see how this unfolds over a few commits to main.
Will let CI run and then merge.
=> fix random codecov/project drops in CI, resolves #1800

src/PostgREST/Private/Common.hs, src/PostgREST/Private/QueryFragment.hs, src/PostgREST/QueryBuilder.hs
As discussed in https://github.com/PostgREST/postgrest/pull/1793#discussion_r611031922
=> refactor: Remove misleadingly named emptyOnFalse and similar

.cirrus.yml
Related to https://github.com/PostgREST/postgrest/pull/1813#issuecomment-819066151.
Let's see whether that works better.
=> ci: fix cirrus build timeout

src/PostgREST/Request/ApiRequest.hs, src/PostgREST/Request/Preferences.hs, test/Feature/InsertSpec.hs
Fixes #1656.
Allows returning only the Location header using "Prefer return=headers-only".
Defaults the POST request made without Prefer header to minimal instead of headers only.
=> Allow headers only POST request and default the request to minimal

.circleci/config.yml
As discussed via email. This is to secure our cachix, docker and github tokens better. Contexts will still have to be filled with environment variables.
The split in `nix-build` and `nix-test` should also make our pipeline faster, because they can both run in parallel. @monacoremo Did I miss anything in there? I don't think the `nix-build` step will have any problems, but will that be OK for `nix-test`? Or is it missing anything that I removed in that step?
=> ci: split nix-build-test into nix-build nix-test and introduce circle ci contexts

src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Relation.hs, src/PostgREST/Error.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Request/DbRequestBuilder.hs
While working on https://github.com/PostgREST/postgrest/pull/1794, I noticed that we can have recursive Junctions:
https://github.com/PostgREST/postgrest/blob/4b46c4eff329c91dc13b26c78b266c7361ecace4/src/PostgREST/DbStructure/Relation.hs#L43-L53
Which didn't seem right, as discussed in https://github.com/PostgREST/postgrest/commit/522308217a03b912e858bdb3311641b6c65c1954#r49568150.
This PR fixes that, also Cardinality now contains the constraint or junction that defines it:
```haskell
data Cardinality
= O2M ConstraintName -- ^ one-to-many cardinality
| M2O ConstraintName -- ^ many-to-one cardinality
| M2M Junction       -- ^ many-to-many cardinality
deriving (Eq, Generic, JSON.ToJSON)
```
That makes sense IMO, it clears up the code in some parts.
=> refactor: make Junction non-recursive

postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Relationship.hs, src/PostgREST/Error.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Request/DbRequestBuilder.hs, src/PostgREST/Request/Types.hs, test/Feature/EmbedDisambiguationSpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Fixes https://github.com/PostgREST/postgrest/issues/1736. Also fixes https://github.com/PostgREST/postgrest/issues/1587.
While working on the pure json schema cache, we noticed that the schema cache contains private db objects: https://github.com/PostgREST/postgrest/pull/1794#issuecomment-815264688.
The solution was to filter the private objects from the json output https://github.com/PostgREST/postgrest/pull/1794#issuecomment-815264688. However, I noticed that this fix would be better applied at a lower level(DbStructure), and thus also solve other issues, like #1736.
It should also increase embedding speed, since there are less relationships to search.
=> fix: disregard internal junction when embedding

src/PostgREST/App.hs, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Table.hs, src/PostgREST/OpenAPI.hs, test/Feature/OptionsSpec.hs, test/fixtures/schema.sql
WIP.  It will resolve issue #1647. 
My approach is to check first if the role has the permissions assigned to the DB table/view, only then check if it's insertable, etc.
=> fix: Allow options to generate certain HTTP methods for a DB view

.circleci/config.yml, default.nix, nix/overlays/checked-shell-script/checked-shell-script.nix, nix/tools/cabalTools.nix, nix/tools/devTools.nix, nix/tools/nixpkgsTools.nix, nix/tools/style.nix, nix/tools/tests.nix, nix/tools/withTools.nix, nix/tools/withtools.nix, shell.nix, test/create_test_db, test/fixtures/database.sql, test/with_tmp_db
There are a couple of things I needed to do for #1805, #1812 and while playing around with CI in #1822 - some of which I needed to have fixed in multiple of those PRs. To avoid juggling the same commits in the different PRs, I want to merge them ahead of time.
This PR does the following:
- Moves `default.nix` and `shell.nix` into the `nix/` subfolder. This is to have all nix-related files in one directory, which allows to set up the context for a ci-nix-Dockerfile much easier. This adds a convenience wrapper for `shell.nix` in the root directory, so that `nix-shell` can still be called the same way as before.
- Splits `cabalTools` from `devTools` to allow installing `postgrest-build` in CI without the overhead of many `devtools` dependencies.
- Fix `postgrest-dump-schema` currently not …
=> Some refactoring and fixes in the nix development environment

.circleci/config.yml, nix/README.md
After merging #1827 this came up in `nix-build` running on main. Double checked all ci jobs that only run on main, should be fine now.
Since this path will not be taken on a PR CI, I will merge this right away.
=> nix(fix): Fix missed devtools->devTools renaming

src/PostgREST/App.hs, src/PostgREST/Error.hs, src/PostgREST/Request/ApiRequest.hs
This is a smaller intermediate step to carving out a small API to `Request`. This moves the code that finds an acceptable response content type into ApiRequest.
=> refactor: Move accept content type code from App into ApiRequest

src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Relationship.hs, src/PostgREST/DbStructure/Table.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Workers.hs, test/Main.hs
As noted on https://github.com/PostgREST/postgrest/pull/1794#issuecomment-826048398, having a foreign key attached to the Column type doesn't make sense(a single column can have multiple FKs defined). So I've removed `colFK` from our `Column` type, without breaking the current OpenAPI output.
The advantage of this is that filtering internal `colFKs`(as mentioned on https://github.com/PostgREST/postgrest/pull/1794#issuecomment-826001841) is no longer needed.
TODO:
=> refactor: more DbStructure cleaning

postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/Config.hs, src/PostgREST/Config/Database.hs, src/PostgREST/Config/PgVersion.hs, src/PostgREST/Config/Proxy.hs, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Identifiers.hs, src/PostgREST/Middleware.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Query/Statements.hs, src/PostgREST/Request/ApiRequest.hs, src/PostgREST/Workers.hs, test/Feature/AndOrParamsSpec.hs, test/Feature/AuthSpec.hs, test/Feature/InsertSpec.hs, test/Feature/JsonOperatorSpec.hs, test/Feature/MultipleSchemaSpec.hs, test/Feature/QuerySpec.hs, test/Feature/RootSpec.hs, test/Feature/RpcSpec.hs, test/Main.hs, test/SpecHelper.hs, test/fixtures/schema.sql
Aims to close https://github.com/PostgREST/postgrest/issues/1731. Partially addresses https://github.com/PostgREST/postgrest/issues/1698.
When `db-root-spec` is used and when the root endpoint(`/`) is requested, this will add a `request.spec` GUC for that transaction.
The `request.spec` GUC is PostgREST schema cache in plain json(no OpenAPI), it contains the relationships between tables/views we infer, among other things.
Example usage:
```sql
create or replace function root_override() returns json as $$
select current_setting('request.spec', true)::json;
$$ language sql;
-- on the config file, add:
-- db-root-spec = "root_override"
```
Doing a `GET /`, will obtain the following [big json](https://gist.github.com/steve-chavez/bccb5ae9f426fd247bedec3cebdc76a2)(this one uses our test suite …
=> Add `request.spec` to db-root-spec

CHANGELOG.md, src/PostgREST/Middleware.hs
Postgrest's gzip support was surprisingly slow, lacked in configurability, was undocumented and untested. This pull request drops that support entirely.
Not gzipping the output more than triples the throughput for a simple no database access RPC function.
Most browsers do send this header, and while it's possible to drop the header in the proxy if you're aware, it's a bit of an undocumented gotcha.
Better then not support gzip at all, further focusing on ensuring Postgrest is a minimal layer over Postgres. Postgrest essentially requires a proxy in production (to set rate limits for example) and chances are that proxy will be much better suited for the job. Nginx, for instance, provides critical options such as min length, vary headers and so forth, and is much faster at it in my testing. …
=> New: drop gzip support, improve performance.

main/Main.hs, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/Config/Database.hs, src/PostgREST/Unix.hs, src/PostgREST/Workers.hs, test/io-tests/test_io.py
Fixes #1850. Now the recovery and startup logs include the time:
```
12/Jun/2021:17:47:39 -0500: Attempting to connect to the database...
12/Jun/2021:17:47:39 -0500: Listening on port 3000
12/Jun/2021:17:47:39 -0500: Connection successful
12/Jun/2021:17:47:39 -0500: Config re-loaded
12/Jun/2021:17:47:40 -0500: Schema cache loaded
12/Jun/2021:17:47:51 -0500: Attempting to connect to the database...
12/Jun/2021:17:47:51 -0500: {"details":"could not connect to server: Connection refused\n\tIs the serv127.0.0.1 - - [12/Jun/2021:17:47:51 -0500] "GET /x HTTP/1.1" 503 - "" "curl/7.64.0"
er running on host \"localhost\" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host \"localhost\" (127.0.0.1) and …
```
=> feat: Add logging with time for worker

postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/CLI.hs, src/PostgREST/Config.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Request/ApiRequest.hs, test/Feature/DisabledOpenApiSpec.hs, test/Feature/IgnoreAclOpenApiSpec.hs, test/Main.hs, test/SpecHelper.hs, test/io-tests/configs/expected/aliases.config, test/io-tests/configs/expected/boolean-numeric.config, test/io-tests/configs/expected/boolean-string.config, test/io-tests/configs/expected/defaults.config, test/io-tests/configs/expected/no-defaults-with-db-other-authenticator.config, test/io-tests/configs/expected/no-defaults-with-db.config, test/io-tests/configs/expected/no-defaults.config, test/io-tests/configs/expected/types.config, test/io-tests/configs/no-defaults-env.yaml, test/io-tests/configs/no-defaults.config
Fixes #1449. Adds the `openapi-mode` config:
* `openapi-mode="follow-acl"`(default): OpenAPI output follows access control for the JWT role.
* `openapi-mode="ignore-acl"`: OpenAPI output  ignores access control for the JWT role.
* `openapi-mode="disabled"`: disables OpenAPI output, the root endpoint replies with 404 Not Found.
=> feat: add openapi-mode config

nix/nixpkgs-version.nix, nix/overlays/ghr/ghr.nix, nix/overlays/gitignore.nix, nix/static-haskell-package.nix
Update dependencies once more now that https://github.com/NixOS/nixpkgs/pull/129606 and https://github.com/nh2/static-haskell-nix/pull/107 are merged. Also update `nix gitignore` and `ghr` to the latest versions.
=> Upgrade Nix dependencies in preparation for new release

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/Workers.hs
Fixes issue [1878](https://github.com/PostgREST/postgrest/issues/1878)
=> Add Retry-After hint

CHANGELOG.md, src/PostgREST/OpenAPI.hs, test/Feature/OpenApiSpec.hs, test/fixtures/privileges.sql, test/fixtures/schema.sql
Closes #1871
Detects most string formats excluding "json" and "jsonb".
Arrays are now detected as an "array" type instead of "string".
=> fix: Detect default values for String types in OpenAPI output

CHANGELOG.md, src/PostgREST/DbStructure.hs, test/Feature/RpcSpec.hs, test/fixtures/schema.sql
This is a regression after changing responses for RPCs with INOUT or OUT arguments in #1615.
Resolves #1930.
The main idea of #1615 was "whenever any argument is given a name, we should return it in object style". We forgot about `RETURNS TABLE`, which has a special case when there is only one column given. With multiple columns in `RETURNS TABLE(...)`, PostgreSQL creates a record type behind the scenes, which we handle correctly. With only one column, this is not the case and we need to specifically check the existance of `TABLE`.
From the two tests I added the first one failed before my change, confirming #1930. The second one is working fine and is just added for completeness.
I added a second commit, too, which removes the check for the record pseudo type. I think we fully replaced …
=> fix: Return array of objects for RPCs with single-column TABLE return type

.cirrus.yml
Stack bug on FreeBSD when using cached working dirs?
=> ci: Fix FreeBSD build

CHANGELOG.md, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Request/Parsers.hs, test/Feature/QuerySpec.hs, test/fixtures/data.sql
Closes #1938.
- **fix**: using `"` and `\` as values on the `in` filter.
- **feat**: Allow backslash escaping inside double quotes.
Examples:
+ `?col=in.("Double\"Quote")`
+ `?col=in.("Back\\slash")`
Backslashed chars get passed as is
+ `?col=in.("\a\b\c")` = `?col=in.(abc)`
=> Values with double quotes on the "in" operator

default.nix, nix/hsie/Main.hs, nix/nixpkgs-version.nix, nix/overlays/postgresql-future.nix, nix/static-haskell-package.nix, stack.yaml, stack.yaml.lock
* Update to latest nixpkgs and stackage
* Building postgresql with musl yields two failing regression tests that should not impact the libpq library that we link; will investigate ans report to nixpkgs
* Upgrade hsie tooling to same compiler version
=> Update nixpkgs and stackage to use GHC 8.10.7

default.nix, nix/nixpkgs-version.nix, nix/overlays/haskell-packages.nix, nix/tools/nixpkgsTools.nix, nix/tools/style.nix, shell.nix
https://github.com/nerdypepper/statix is a very promising new linting tool for nix code, it already identified and automatically fixed several improvements in our codebase. Hooked into `postgrest-style`
=> Nix: Add statix linting for nix code

default.nix, nix/tools/style.nix, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/Config.hs, src/PostgREST/Config/Database.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Error.hs, src/PostgREST/Middleware.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Query/Statements.hs, src/PostgREST/Request/ApiRequest.hs, src/PostgREST/Request/Types.hs, src/PostgREST/Workers.hs
This is an item on our refactoring roadmap: https://github.com/PostgREST/postgrest/issues/1804
Our Haskell Import/Export tool `hsie` is able to check whether we use consistent aliases when importing modules. Before this PR, when running `hsie check-aliases main src` we get:
```
The following imports have inconsistent aliases:               
Module 'Data.Aeson' has the aliases:
'Aeson' in file:
src/PostgREST/CLI.hs
'JSON' in files:
src/PostgREST/Auth.hs
src/PostgREST/Config.hs
src/PostgREST/Config/PgVersion.hs
src/PostgREST/DbStructure.hs
src/PostgREST/DbStructure/Identifiers.hs
src/PostgREST/DbStructure/Proc.hs
src/PostgREST/DbStructure/Relationship.hs
src/PostgREST/DbStructure/Table.hs
src/PostgREST/Error.hs
src/PostgREST/GucHeader.hs
src/PostgREST/Middleware.hs
src/PostgREST/OpenAPI.hs …
```
=> Refactor: Make import aliases consistent

CHANGELOG.md, src/PostgREST/Request/ApiRequest.hs, test/Feature/RpcSpec.hs, test/fixtures/schema.sql
WIP
Implementing this idea https://github.com/PostgREST/postgrest/pull/1927#discussion_r737776638 to avoid responding with a `300 Multiple Choices` error when doing a POST request to overloaded functions if one has a single unnamed JSON parameter.
The first commit is an ugly attempt, which is working so far (only the test for the overloaded function is failing as expected).
=> Allow overloaded functions if one has a single unnamed JSON param

src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/Config/JSPath.hs, src/PostgREST/DbStructure/Identifiers.hs, src/PostgREST/Middleware.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Request/ApiRequest.hs, src/PostgREST/Request/Preferences.hs, src/PostgREST/Request/Types.hs
This is an item on our refactoring roadmap #1804 
Using `GHC.Show` to pretty-print or serialize data is an [anti-pattern](https://www.stephendiehl.com/posts/strings.html), show is meant to create a Haskell expression that can be parsed by `read`, see https://hackage.haskell.org/package/base-4.16.0.0/docs/GHC-Show.html
This PR removes all uses of `GHC.Show` instances in the codebase. As a side effect, this avoids several string conversions, especially when parsing preference headers, for what is likely a small performance gain.
=> Refactor: Remove (mis)uses of GHC.Show instances

.cirrus.yml, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/Config.hs, src/PostgREST/Config/JSPath.hs, src/PostgREST/Config/Proxy.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Error.hs, src/PostgREST/GucHeader.hs, src/PostgREST/Middleware.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Query/Statements.hs, src/PostgREST/RangeQuery.hs, src/PostgREST/Request/ApiRequest.hs, src/PostgREST/Request/Parsers.hs, src/PostgREST/Version.hs, src/PostgREST/Workers.hs
This is another item on our refactoring roadmap #1804 and builds on top of the commits in #2016
Currently, we use `toS` from [`Protolude.Conv`](https://hackage.haskell.org/package/protolude-0.3.0/docs/Protolude-Conv.html) in almost all modules. `toS` contains partial functions and expensive transformations, which is why it is not exported by Protolude by default. For example, converting `ByteString` to `Text` involves [`T.decodeUtf8`](https://hackage.haskell.org/package/text-1.2.5.0/docs/Data-Text-Encoding.html#v:decodeUtf8) (see: https://hackage.haskell.org/package/protolude-0.3.0/docs/src/Protolude.Conv.html#StringConv) which will raise an uncatchable exception if the input is not valid utf-8.
This PR replaces all uses of `Protolude.Conv.toS` with the respective explicit transformations …
=> Refactor: Remove uses of Protolude.Conv.toS

.github/workflows/ci.yaml, nix/tools/devTools.nix, nix/tools/tests.nix, postgrest.cabal, src/PostgREST/Request/ApiRequest.hs, src/PostgREST/Request/Preferences.hs, test/doctests/Main.hs
This is another item on our refactorin roadmap #1804, building on top of #2016 
This PR integrates doctests into our Nix tooling and adds examples to the `Request.Preferences` module
=> Add doctests

nix/tools/style.nix
I found `actionlint` yesterday. Thought we could add it. Of course, we have @remo, whose github workflows are flawless - actionlint reports no problems, so far! But just to make sure we don't make things worse in the future, we can still add it..
=> nix(feat): Add actionlint to postgrest-lint

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/CLI.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Workers.hs, test/Feature/InsertSpec.hs, test/Feature/OpenApiSpec.hs, test/Feature/OptionsSpec.hs, test/Feature/QuerySpec.hs, test/Feature/UpsertSpec.hs, test/Main.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Closes #1783.
Implements: https://github.com/PostgREST/postgrest/issues/1783#issuecomment-961681153
=> Remove partitions from the schema cache

CHANGELOG.md, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Request/Parsers.hs, src/PostgREST/Request/Types.hs, test/Feature/QuerySpec.hs, test/fixtures/data.sql, test/fixtures/privileges.sql, test/fixtures/schema.sql
Closes https://github.com/PostgREST/postgrest/issues/1998.
- feat: allow unknown on the is operator 
Also make the IS values strict at the Parser level since IS cannot be parametrized.
- refactor: remove pgFmtLit
This is so there's no more logic related to escaping in the codebase.
=> Allow unknown for is operator

test/Feature/RpcSpec.hs, test/fixtures/schema.sql
Closes #1672 
As mentioned in https://github.com/PostgREST/postgrest/issues/1672#issuecomment-971005376, looks like the changes made in the `findProc` function solved the issue with embedding on overloaded functions with the same signature except for the last parameter, which has a default value.
This PR adds tests to confirm the resolution.
=> Add tests for embedding on overloaded functions with a default param

.github/actions/setup-nix/action.yaml, .github/workflows/ci.yaml, nix/tools/style.nix
I wanted to get used to GitHub Actions a bit more and played with our workflow. To reduce some of the repetition we currently have, I added a `setup-nix` action and used a matrix strategy to build with stack on different OS. This doesn't really reduce the amount of code, but I feel it's a bit quicker to see which parts are the same between different jobs and which parts are varied.
I also tried two more things, but failed so far:
- Reorganizing the big workflow into multiple files with the "reusable workflows" feature, doesn't really work, yet, because this does not support calling workflow files in the same repository, yet. This might be possible in the future.
- Running the spec tests on Windows requires to have `with_tmp_db` run on Windows. I can see that as a possibility and also made …
=> ci: Refactor workflows

.github/workflows/ci.yaml
Follow up to #2032: The stack build matrix had the default of `fail-fast` enabled, which would have stopped other stack builds when one of them failed. Disabled that and simplified the matrix a tiny bit, too.
=> ci: disable fail-fast in stack build matrix

CHANGELOG.md, src/PostgREST/Error.hs, test/Feature/EmbedDisambiguationSpec.hs
The example given when an Ambiguous Embedding error is thrown shows a generic example `/origin?select=relationship(*)` or `/origin?select=target!relationship(*)`.
This PR adds examples with the real  `target!relationship` names relevant to the query, omitting the `origin` and the `select` clause. 
Edit: Also adds changes to other parts of the error to make it clearer to the user.
=> Include valid examples in the hint for ambiguous embedding

nix/tools/withTools.nix, test/with_tmp_db
Three changes here:
- For one, `pg_ctl` has a `-w` option, that will make it wait until startup is completed. This option is enabled by default from PG 10 onwards - but can be enabled with this flag for older versions. No need for the loop anymore.
- the nix-checked `withTmpDb` and `test/with_tmp_db` have deviated a bit by now. We can do the same simplifications regarding error handling we did for the nix version in the standalone version, too. If we only trap `EXIT`, we will only have `stop()` called once automatically, but still clean up all the time properly.
- Finally, running the actual command in a subshell in `with_tmp_db`, too, makes it a bit more robust in case somebody runs it with a shell script that sets up other traps - we'd want to make sure we're not losing our exit trap in …
=> nix: Simplify with_tmp_db

.github/dependabot.yml
Now, that we have switched to GitHub Actions and are using actions from other sources, it would make life easier if dependabot gave us automatic PRs for updates to those actions.
This is the config for that - but dependabot needs to be enabled at the same time in the repo settings, for which I don't have access. @steve-chavez
=> ci: Add dependabot config for auto updates of github actions

.github/workflows/ci.yaml, CHANGELOG.md, README.md, default.nix, nix/README.md, nix/overlays/postgresql-legacy.nix, src/PostgREST/App.hs, src/PostgREST/Config/PgVersion.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Query/Statements.hs, test/Feature/JsonOperatorSpec.hs, test/Feature/MultipleSchemaSpec.hs, test/Feature/QuerySpec.hs, test/Feature/RpcSpec.hs, test/Main.hs
Now that [PG 9.6 is past EOL](https://www.postgresql.org/support/versioning/), it's time to drop support for PG 9.5.
We should still support PG 9.6 for the next release, but maybe we can drop that soon after that, too.
=> Drop support for PostgreSQL 9.5

.github/workflows/report.yaml, nix/tools/release/default.nix
This takes two tiny nix fixes out of #1812 and adds the report workflow from there, too. The workflow needs to be merged ahead of #1812 to be able to upload coverage reports to the Actions/Checks page. This is because the workflow to do that must be trusted and as such must be from this repo and not from my fork through the PR.
I tested it in my own fork and it should work like that.
=> ci: Add report workflow ahead of #1812

.github/workflows/ci.yaml
As mentioned in https://github.com/PostgREST/postgrest/pull/2045#issuecomment-980532787:
This is not allowed via personal access token right now and could be re-enabled in the future, once solved by docker hub.
=> ci: Disable update of dockerhub description on release

.github/workflows/ci.yaml
Now, that we dropped support for PG 9.5, we can run the IO tests on all postgres versions in CI as mentioned in #1820.
(Closes #1820)
=> ci: Run IO tests against all postgres versions

nix/tools/devTools.nix, nix/tools/tests.nix, postgrest.cabal, test/SpecHelper.hs, test/weeder.dhall
Found [weeder](https://hackage.haskell.org/package/weeder) and gave it a try. It found some dead code in `SpecHelper.hs`. Removed that and added it to `postgrest-coverage`. `postgrest-coverage` instead of `postgrest-lint`, because it needs to have the whole project built to operate.
=> nix: Add weeder to postgrest-coverage

nix/tools/devTools.nix, nix/tools/style.nix
As promised in https://github.com/PostgREST/postgrest/pull/1822#discussion_r616165264 here's `postgrest-git-hooks`. Run `postgrest-git-hooks enable` in nix-shell to enable basic pre-commit and pre-push hooks.
Careful: When testing this, make sure to run `postgrest-git-hooks disable` before starting to work on another branch again. When the other branch doesn't have `postgrest-git-hooks`, this will prevent any commit or push going through. Just in case somebody is getting stuck somewhere: This can be overriden with `--no-verify` all the time.
Related: #1804
=> nix: Add postgrest-git-hooks to enable pre-commit and pre-push hooks

postgrest.cabal, src/PostgREST/Error.hs, src/PostgREST/Request/DbRequestBuilder.hs, test/Feature/EmbedDisambiguationSpec.hs, test/Feature/QuerySpec.hs
This PR adds an extra hint that recommends the user to verify the existence of the tables and the relationship between them in the database before restarting the schema cache.
=> Add hint to verify table and foreign key existence on a relationship error

CHANGELOG.md, src/PostgREST/DbStructure.hs, test/fixtures/schema.sql, test/io-tests/test_io.py
Resolves #2024.
Using `XMLTABLE` in a view with a column that has a `DEFAULT` when the first column does not have a default, currently breaks our recursive view parsing query `pfkSourceColumns`.
This is because in this case the node tree has an expression of the form `:coldefexprs (<> {CONST ... })` for the default values. The column does not have a default value, so it's set as `<>`, which means null in the node tree. One step of parsing is "protecting node lists from the greedy regex", which is run later. This protection assumes that node lists always start with either `((` or `({` - only that in this case, the list starts with `(<`.
By moving the replacement of `<>` with an empty array, that was happening as the last step before, to the beginning, this case will now look like a `((` …
=> fix: Make recursive view parsing work with XMLTABLE + DEFAULT

CHANGELOG.md, postgrest.cabal, src/PostgREST/Admin.hs, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, test/io-tests/test_io.py
As discussed on https://github.com/PostgREST/postgrest/pull/2092#issuecomment-1003260934
---
Will finish https://github.com/PostgREST/postgrest/pull/2107 after this one.
=> Connect to main app socket on health check

CHANGELOG.md, src/PostgREST/Admin.hs, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/Error.hs, src/PostgREST/Workers.hs, test/Main.hs, test/io-tests/db_config.sql, test/io-tests/test_io.py
As suggested in https://github.com/PostgREST/postgrest/pull/2092#issuecomment-1000776098
> However, what we can and should do is: Keep track of the status of the last schema cache refresh - and if that fails, e.g. because of something like #2024, we should return 503. Currently we are still returning 200, when the schema cache fails.
This change does prevent a healthy response in case something like #2024 happens, but only at startup. If the schema cache fails to load after startup, the main app will continue working and the health check will respond accordingly.
The main app failure happens at startup because of:
https://github.com/PostgREST/postgrest/blob/4f7ee6f36aae6ed36ecfec4ac3c1aa0b656bdddb/src/PostgREST/App.hs#L203-L208
Should we turn the schema cache to Nothing if it fails …
=> Consider schema cache state on the health check

test/io-tests/test_io.py
=> Make io tests use admin/ready to wait for startup

postgrest.cabal
Resolves #387.
Related:
- https://neilmitchell.blogspot.com/2015/09/detecting-space-leaks.html?m=1
- https://downloads.haskell.org/~ghc/9.0.1/docs/html/users_guide/runtime_control.html#rts-flag--K%20%E2%9F%A8size%E2%9F%A9
`-K1K` will make the spec tests fail - the OpenAPI output causing the stack overflow here. I raised it up to `-K33K` to make it pass. This is just added to prevent things from using more stack than right now. Maybe we can lower it to `-K1K` at some point in the future.
=> Detecting space leaks (stack size) in CI

src/PostgREST/CLI.hs, test/memory/memory-tests.sh
I mentioned `postgrest --example` in https://github.com/PostgREST/postgrest-docs/pull/493 - and then realized that I forgot to update the example config file in #2112. This PR does that - and improves the example file a bit more.
=> Fix `--example` configuration file

CHANGELOG.md, src/PostgREST/DbStructure.hs
Trigger functions can't be called directly from SQL and can't be called
via the /rpc prefix either - it makes no sense to expose them in the
OpenAPI output. And we don't need to cache them in the schema cache
either.
Best practice would be to keep the trigger functions in a non-exposed
schema anyway.
=> fix: Remove trigger functions from schema cache and OpenAPI output

.github/workflows/ci.yaml, nix/tools/tests.nix, test/spec/SpecHelper.hs
This updates the keyring on windows builds to remove the key failure when installing dependencies. This will have to rebuild everything, so this might take a while.
While at it, I also fixed `weeder` to find dead code. The non-zero exit code was swallowed, leading to no failures when there should have been some.
=> Fix windows build in CI

CHANGELOG.md, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Request/QueryParams.hs, test/spec/Feature/Query/JsonOperatorSpec.hs, test/spec/fixtures/data.sql, test/spec/fixtures/privileges.sql, test/spec/fixtures/schema.sql
As discussed in https://github.com/PostgREST/postgrest/issues/1543#issuecomment-1028162880.
Works fine... almost.
---
The array part is failing two tests. Filtering works, but select and order do not - and I don't understand why.
The following request (the combination of both failing tests):
```http
GET /arrays?select=a:numbers->0,b:numbers->1,c:numbers_mult->1->1,d:numbers_mult->2->3&order=numbers->0.desc
```
results in the following query:
```sql
WITH pgrst_source AS (
SELECT
to_jsonb("test"."arrays"."numbers")->$1 AS "a",
to_jsonb("test"."arrays"."numbers")->$2 AS "b",
to_jsonb("test"."arrays"."numbers_mult")->$3::int->$4 AS "c",
to_jsonb("test"."arrays"."numbers_mult")->$5::int->$6::int AS "d"
FROM "test"."arrays"
ORDER BY to_jsonb("test"."arrays"."numbers")->$7 DESC
)
-- [...]
``` …
=> feat: Support accessing array items and fields of composite types through json operators

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Proc.hs, test/io/test_io.py, test/spec/Feature/Query/InsertSpec.hs, test/spec/Feature/Query/RpcSpec.hs
While trying to fix #2001, I started with making our expectance for a absent or present `Content-Type` header more explicit in the spec tests. While doing that, I noticed that a `PUT` was inconsistently returning a `Content-Type` when returning with `204 No Content`.
The first commit improves those tests and fixes PUT.
The second commit solves a TODO in a related part of the code - it should be self-explanatory.
The third commit then implements the breaking change to return `204 No Content` without body for `VOID` RPCs.
I consider only the part about RPCs a breaking change and am thinking about merging the other fix ahead of time. I'd like us to be able to get a bugfix release out, once we fix a couple of the open, non-breaking bugs, so I'd like to hold back on merging the breaking change …
=> Fix: Returning 204 No Content where appropriate

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/CLI.hs, src/PostgREST/Config/Database.hs, src/PostgREST/DbStructure.hs, src/PostgREST/Workers.hs, test/spec/Main.hs, test/spec/fixtures/schema.sql
Aggregates and Window functions can't be called as RPCs in a useful way.
Until procedures are implemented in #1976 it makes no sense to list them in the OpenAPI output.
Resolves #2101
=> Remove aggregates, procedures and window functions from schema cache and OpenAPI

CHANGELOG.md, src/PostgREST/DbStructure.hs
This allows to create virtual columns in the exposed schema, as suggested in our docs, without "polluting" the OpenAPI output with some fake RPCs. To do this the virtual columns need a single **unnamed** argument.
Example:
```sql
CREATE TABLE people (lastname TEXT, firstname TEXT);
-- This virtual column will have an RPC listed in the OpenAPI output
CREATE FUNCTION fullname (p people) RETURNS TEXT
RETURN p.firstname || p.lastname;
-- Before this PR: This virtual column would have had a fake RPC listed, but couldn't be called directly.
-- After this PR: This virtual column will have no fake RPC listed
CREATE FUNCTION initials (people) RETURNS TEXT
RETURN left($1.firstname, 1) || left($1.lastname, 1);
```
Tested locally by observing changes to the `--dump-schema` output. We had a few fake …
=> Remove non-callable functions from schema cache and OpenAPI output

src/PostgREST/Config.hs, test/io/db_config.sql
Fixed as discussed here https://github.com/PostgREST/postgrest-docs/pull/508#discussion_r812359107
=> fix: Remove admin-server-port from in-db configuration

CHANGELOG.md, src/PostgREST/Request/ApiRequest.hs, test/spec/Feature/Query/RpcSpec.hs
=> fix: Using GET with certain Content-Type headers now correctly calls the no parameter function if it exists

src/PostgREST/Admin.hs, src/PostgREST/App.hs, test/io/fixtures.yaml, test/io/test_io.py
Fixes https://github.com/PostgREST/postgrest/issues/2174.
Took a different route from the one suggested in https://github.com/PostgREST/postgrest/issues/2174#issuecomment-1045978929. I avoided including the [streaming-commons](https://hackage.haskell.org/package/streaming-commons) dependency and instead just handled the special host values in the admin server logic by stealing some of the code from [bindPortGenEx](https://hackage.haskell.org/package/streaming-commons-0.2.2.4/docs/src/Data.Streaming.Network.html#bindPortGenEx). That seemed like a simpler change.
=> Correct live/ready checks to consider special host values

CHANGELOG.md, src/PostgREST/OpenAPI.hs, test/io/test_io.py, test/spec/Feature/OpenApi/OpenApiSpec.hs, test/spec/fixtures/schema.sql
Fixes #2165
I couldn't find a way to type `toSwaggerType` that didn't involve `DataKinds` and importing from `Data.Swagger.Internal` ... 🤔 but glad to change that if someone knows how.
=> fix: json/jsonb columns should have type "object" in OpenAPI spec

.github/workflows/ci.yaml
There were long timeouts in the previous v9.9.0.20220326 prerelease with FreeBSD builds in Cirrus, bypassing for now. The binaries will be uploaded manually.
=> Bypass FreeBSD builds due to timeouts

CHANGELOG.md, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Request/QueryParams.hs, src/PostgREST/Request/Types.hs, test/spec/Feature/Query/QuerySpec.hs
refs #2236
[x] added CHANGELOG entry
[x] updated the docs: https://github.com/PostgREST/postgrest-docs/pull/524
Implements support for `~` and `~*` operators according:
* https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP
=> feat(query): add basic regular expression operator support

CHANGELOG.md, src/PostgREST/Error.hs, test/spec/Feature/Query/EmbedDisambiguationSpec.hs, test/spec/fixtures/privileges.sql, test/spec/fixtures/schema.sql
Clarifies the content of the `relationship` key error. The content in square brackets `[]` are not part of the disambiguation syntax and may be mistakenly added to the request when trying to fix this error as seen here: https://github.com/supabase/supabase/discussions/6274#discussioncomment-2504906
> `select('id,from(id,username),to(id,username),series!adaptation_notifications_series_fkey[series](id,title,novel),status,when')`
This suggestion changes, for instance:
```
"relationship": "people_country_fk[country_id][id]"
```
to:
```
"relationship": "people_country_fk using people(country_id) and country(id)"
```
=> Clarify the relationship in the embedding disambiguation error

test/io/big_schema.sql, test/io/fixtures.sql, test/io/test_io.py
The big_schema(`apflora`) we use internally for perf tests is OSS https://github.com/barbalex/apf2/tree/master/sql/apflora so we can include it in our CI tests.
I've also asked barbalex to be sure - alles gut.
---
apflora stats:
```
select count(*)  from information_schema.routines where specific_schema = 'apflora';
count
-------
12
select count(*)  from information_schema.tables where table_schema = 'apflora' and table_type = 'BASE TABLE';
count
-------
45
(1 row)
select count(*)  from information_schema.views where table_schema = 'apflora';
count
-------
281
```
It doesn't have that many tables, the views are likely what makes our internal cache so big; probably the relationships generated between them(strict m2m junctions should help a bit here).
=> test: add big schema openapi test

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Relationship.hs, src/PostgREST/DbStructure/Table.hs, src/PostgREST/Error.hs, src/PostgREST/OpenAPI.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Request/DbRequestBuilder.hs, test/spec/Feature/OpenApi/RootSpec.hs, test/spec/Feature/Query/InsertSpec.hs
* Get PKcols inside tables - done with SQL for tables and with an additional step in Haskell for views.
This fixes an fk column being considered as a pk column on views and corrects the test added on https://github.com/PostgREST/postgrest/pull/1875/files/1d549768580310e18aac4ffa6dbd01c5b77934a7#r853674126
* classify view key dependencies in SQL
* remove Column from Relationship
* Merge cols/fcols in Relationship and ensure allM2ORels and allViewsKeyDependencies fk columns are ordered - done by attnum in SQL
* Cardinality now contains relColumns instead of Relationship - this simplifies getJoinConditions.
=> refactor: reduce OpenAPI(PKcols in table, ViewKeyDependency type)

src/PostgREST/DbStructure.hs, test/spec/Feature/OpenApi/OpenApiSpec.hs
Making sure I don't miss anything when merging this query with the `allTables` query.
* Add OpenAPI test to ensure enum labels are present
* Remove unnecessary fk/pk columns cte
* Remove unnecessary step for parsing enum labels
=> refactor: clean allColumns query

src/PostgREST/App.hs, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Table.hs, src/PostgREST/OpenAPI.hs, test/memory/memory-tests.sh, test/spec/Feature/OpenApi/OpenApiSpec.hs
Merges the SQL query of `allColumns` into `allTables`.
I thought with this we'd get a considerable reduction of the apflora `dump-schema` output but:
```
du -sh old.json new.json
68M    old.json
67M     new.json
```
Just 1M reduction. Which goes on to show the big reduction [before](https://github.com/PostgREST/postgrest/pull/2254#issuecomment-1104163025) was because the bulk of the size comes from the Relationship list.
=> refactor: merge Column list into Table

.github/scripts/arm/build.sh, .github/scripts/arm/docker-env/Dockerfile, .github/scripts/arm/docker-publish.sh, .github/workflows/ci.yaml
There's a problem with the cache image for ARM builds using Docker added in #2127 (cannot pull or push to the registry). This change makes use of the remote server to build natively (without Docker) for `aarch64` architectures and removes `armv7` builds from the CI until a better alternative to build for that architecture is found.
=> Remove armv7 architectures from CI for ARM builds

CHANGELOG.md, src/PostgREST/DbStructure.hs, test/io/big_schema.sql, test/spec/Feature/Query/QuerySpec.hs, test/spec/fixtures/privileges.sql, test/spec/fixtures/schema.sql
Fixes https://github.com/PostgREST/postgrest/issues/2070.
Now we only add m2m relationship based on [strict junctions](https://en.wikipedia.org/wiki/Associative_entity):
- A table has FKs to two other tables
- **These FK columns are part of the table's PK columns.**
=> fix: restrict generated m2m relationships

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/ContentType.hs, src/PostgREST/Error.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Query/Statements.hs, src/PostgREST/Request/ApiRequest.hs, test/spec/Feature/Query/RpcSpec.hs, test/spec/fixtures/schema.sql
This PR would allow RPCs to return xml.
Part of #2188.
- Request must contain header 'Accept: text/xml'
- Will work for scalar RPC return type xml
- Will work for RPC table return type - everything gets concatenated (assuming every column is kind of xml)
- Will fail if request header 'Accept: text/xml' is ~~not~~ set and  RPC return type is scalar but is not xml.
=> Allow returning XML from RPCs

CHANGELOG.md, src/PostgREST/RangeQuery.hs, src/PostgREST/Request/ApiRequest.hs, test/spec/Feature/Query/RangeSpec.hs
Closes #1121.
Continues what was discussed in PR #1929
=> Allow limit=0 in query params to return an empty array

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Table.hs, src/PostgREST/Error.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Request/ApiRequest.hs, src/PostgREST/Request/DbRequestBuilder.hs, src/PostgREST/Request/Types.hs, test/memory/memory-tests.sh, test/spec/Feature/Query/DeleteSpec.hs, test/spec/Feature/Query/UpdateSpec.hs, test/spec/fixtures/privileges.sql, test/spec/fixtures/schema.sql
Continuing the work on https://github.com/PostgREST/postgrest/pull/2195.
As agreed on https://github.com/PostgREST/postgrest/pull/2195#discussion_r835779754, `limit` now works on views if they do include an explicit `order`.
=> Limited update/delete part 2

src/PostgREST/Error.hs, test/spec/Feature/Query/ErrorSpec.hs, test/spec/Feature/Query/QuerySpec.hs, test/spec/Feature/Query/RpcSpec.hs, test/spec/Feature/Query/SingularSpec.hs, test/spec/Feature/Query/UpsertSpec.hs
Followed the example of [PostgreSQL internal errors](https://www.postgresql.org/docs/current/errcodes-appendix.html) and separated the Hasql errors from the group sequence (now starts with X instead of 4) and changed the name to Internal errors.
Also moved some General errors that should be in the Api Request group.
=> Reorganize error groups

CHANGELOG.md, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Relationship.hs, src/PostgREST/Request/DbRequestBuilder.hs, test/spec/Feature/Query/EmbedDisambiguationSpec.hs, test/spec/fixtures/data.sql, test/spec/fixtures/privileges.sql, test/spec/fixtures/schema.sql
Closes https://github.com/PostgREST/postgrest/issues/2277, closes https://github.com/PostgREST/postgrest/issues/2238, closes https://github.com/PostgREST/postgrest/issues/1643.
=> No column or hint as target for embedding views

.github/workflows/ci.yaml
ARM builds are no longer skipped for releases (on version tag push).
=> ci: Run ARM builds on releases

.github/workflows/ci.yaml
Branches starting with `rel-*` will support small fixes. This allows that PRs (and pushes) done to that branch run the CI, e.g. #2296
=> Add CI runs for PR to branches starting with rel-

CHANGELOG.md, src/PostgREST/DbStructure.hs, src/PostgREST/Error.hs, src/PostgREST/Request/ApiRequest.hs, test/spec/Feature/Query/RpcSpec.hs, test/spec/fixtures/schema.sql
RPC POST for function w/single unnamed XML param
- extends #1927 for data type xml
- part of #2188
=> RPC POST for function w/single unnamed XML param

default.nix, nix/hsie/default.nix, nix/tools/tests.nix
This collects some changes to the nix scripts that came out of #2292, but that should be good independently.
- fix running test script when there's no glibc
- fix possible weeder GHC version mismatch
- pass through arguments for postgrest-test-spec
- fix hsie build (#2304)
=> nix: assorted improvements

CHANGELOG.md
Includes the CHANGELOG from the [v9.0.1 release](https://github.com/PostgREST/postgrest/releases/tag/v9.0.1) and updates the Unreleased section.
=> Fix CHANGELOG to include release v9.0.1

nix/tools/cabalTools.nix
Got this error when running `postgrest-coverage` even after running `postgrest-clean`: 
```log
incompatible hie file: /home/laurence/Projects/postgrest/test/spec/QueryCost.hie
this version of weeder was compiled with GHC version 9022
the hie files in this project were generated with GHC version 8107
weeder must be built with the same GHC version as the project it is used on
```
Removing the `*.hie` files worked, so I added this command to `postgrest-clean` in case anyone gets this problem in the future.
=> nix: Add command to remove old hie files in postgrest-clean

CHANGELOG.md, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Config.hs, src/PostgREST/Error.hs, src/PostgREST/Request/ApiRequest.hs, src/PostgREST/Request/Types.hs, test/spec/Feature/OpenApi/DisabledOpenApiSpec.hs, test/spec/Feature/OptionsSpec.hs, test/spec/Feature/Query/ErrorSpec.hs, test/spec/Feature/Query/RpcSpec.hs, test/spec/SpecHelper.hs
Closes https://github.com/PostgREST/postgrest/issues/2364.
Removes the `ActionUnknown` and `TargetUnknown` types and ensures an error is raised at the ApiRequest level(no db connection from the pool here).
Also untangles the `ApiRequest` code a bit, making it more linear.
Not using connections cannot be tested for now but once metrics(https://github.com/PostgREST/postgrest/pull/2129) is merged it could be done by checking the pool `takes`.
=> fix: no empty transaction on bad URL/method

default.nix, nix/nixpkgs-version.nix, nix/overlays/haskell-packages.nix, nix/patches/nixpkgs-openssl-split-runtime-dependencies-of-static-builds.patch, nix/static-haskell-package.nix
This updates nixpkgs to a current version, where we no longer need to override Haskell dependencies.
=> nix: bump nixpkgs version

nix/tools/tests.nix, test/io/fixtures.sql, test/io/test_io.py
Missing tests for https://github.com/PostgREST/postgrest/pull/2365.
=> test: no empty tx started for invalid path/method

src/PostgREST/Query/QueryBuilder.hs, test/spec/Feature/Query/RpcSpec.hs
Closes https://github.com/PostgREST/postgrest/issues/2369, correct https://github.com/PostgREST/postgrest/commit/e4006da9bccaba85dc141779f48692448eb16fca.
Adds missing tests for `count=exact` on rpc.
=> correct query on rpc count=exact

test/io/db_config.sql, test/io/test_io.py
Compare the discussion in #2391.
The new tests verify that:
- statement_timeout on the authenticator role works to cancel slow statements
- changes to statement_timeout take effect on SIGUSR1
This reuses the old "limited_authenticator" role and adds some plumbing to
allow reliably changing the statement timeout even if the current role is
not functional due to a low statement timeout, and to make tests that modify
the role independent from each other.
- introduce module-wide metapostgrest fixture to have an out-of-band way to
manipulate the database, without having to spin up extra postgrest instances
per test
- reset statement_timeout at the start of the respective tests
=> tests: add tests for statement_timeout

CHANGELOG.md, src/PostgREST/Request/QueryParams.hs, test/spec/Feature/Query/QuerySpec.hs, test/spec/fixtures/data.sql, test/spec/fixtures/privileges.sql, test/spec/fixtures/schema.sql
PostgreSQL identifiers can have the dollar sign($) inside them without the need for double quoting.
>SQL identifiers and key words must begin with a letter (a-z, but also letters with diacritical marks and non-Latin letters) or an underscore (_). Subsequent characters in an identifier or key word can be letters, underscores, digits (0-9), or dollar signs ($).
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
=> fix: columns w/ dollar sign($) don't need quoting

nix/tools/style.nix, src/PostgREST/Admin.hs, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/Config/Database.hs, src/PostgREST/Unix.hs, src/PostgREST/Workers.hs, test/io/test_io.py
Largely, this collects all interaction with the connection pool in AppState helpers `usePool` and `releasePool`. (It's not obviously better to use `AppState.usePool` in place of `SQL.use . AppState.getPool`, but for now this approach is more consistent than what we had before, and will allow easily doing things like putting the pool in an IORef in the context of #2391.)
=> refactor code interacting with pool for consistency, and misc fixes

CHANGELOG.md, src/PostgREST/AppState.hs, src/PostgREST/Workers.hs
Previously, it was quite possible to have two connection workers
running, or to get into a state where a failed connection worker
is still considered running preventing new connection workers
from starting.
=> fix: fix some race conditions running connection worker

src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/Unix.hs, test/spec/Main.hs
This changes behaviour somewhat in that:
- We now consistently release the pool on shutdown, even on non-Unix
platforms, and including for CmdDumpConfig.
- We release the pool *after* interrupting `App.run`, which will
rather cause more than fewer connection to be closed properly.
(Previously any in-use connections would not have been caught by
`releasePool`, though *maybe* the `UserInterrupt` handling in
the web handler ends up closing the connections properly already
anyway).
(The main aim of the change is to make it clearer when and why the
pool is released.)
=> refactor: move pool release on shutdown out of signal handler

src/PostgREST/Query/QueryBuilder.hs, test/spec/Feature/Query/PlanSpec.hs
Improves the query plan costs(compare tests on 48003e7235219ac843c95554cfe8afbeab523447 to 23b9b74155056f337cd493f5162248f61a1e453d) by changing the query from using a subquery:
```sql
SELECT
"test"."clients".*,
COALESCE (
(SELECT json_agg("clients".*)
FROM (
SELECT "test"."projects".*
FROM "test"."projects"
WHERE "test"."clients"."id" = "test"."projects"."client_id"  ) "clients" )
, '[]') AS "projects"
FROM "test"."clients"
```
To a correlated subquery using LATERAL:
```sql
SELECT
"test"."clients".*,
COALESCE( "clients_projects"."_clients_projects", '[]') AS "projects"
FROM "test"."clients"
LEFT JOIN LATERAL (
SELECT json_agg("_clients_projects") AS "_clients_projects"
FROM (
SELECT "test"."projects".*
FROM "test"."projects"
WHERE "test"."clients"."id" = "test"."projects"."client_id"   ) …
```
=> refactor: correlated subquery for o2m query

postgrest.cabal, test/spec/Feature/OptionsSpec.hs, test/spec/Feature/Query/DeleteSpec.hs, test/spec/Feature/Query/PgSafeUpdateSpec.hs, test/spec/Feature/Query/UpdateSpec.hs, test/spec/SpecHelper.hs, test/spec/fixtures/schema.sql
Some mutations tests (updates/deletes) need to verify if the change did happen in the databas, which makes them bulky and difficult to read. 
This PR moves that logic to `SpecHelper.hs` and uses it as a global function for the tests that need it.
=> Simplified tests where mutations need to be verified in the db

default.nix, nix/overlays/gitignore.nix, nix/static-haskell-package.nix, shell.nix
I am using PostgREST in a flake, which uses Nix pure evaluation mode by default, which cannot use builtins.currentSystem.
Also updated nix-gitignore to include this fix to stop attempting to read ~/.gitignore https://github.com/hercules-ci/gitignore.nix/pull/58
The type of default.nix is changed from an attrset to a function. nix-build still works (nix-build . -A postgrestStatic), but if other people import default.nix in their own expression maybe default.nix should be renamed to pure.nix, and default.nix change to
```nix
import ./pure.nix { }
```
??
https://github.com/hercules-ci/gitignore.nix/pull/58
=> Nix: allow building from pure-eval mode

CHANGELOG.md, src/PostgREST/DbStructure.hs
The query in:
https://github.com/PostgREST/postgrest/blob/bac63f339daa4a9292870b0674b41cde2bcfee74/src/PostgREST/DbStructure.hs#L655-L809
Doesn't properly consider the type of the column contype (char) of the table pg_constraint. So when it tries to make a union with the concat function (text), fails with a missmatch type error. This fixes the issue. 
Related issue here:
[Reported issue](https://github.com/PostgREST/postgrest/issues/2410)
#2410
=> Fix bug "UNION types \"char\" and text cannot be matched" with v9.0.1.+++ versions

CHANGELOG.md, postgrest.cabal, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Relationship.hs, src/PostgREST/Error.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Request/DbRequestBuilder.hs, src/PostgREST/Request/ReadQuery.hs, test/spec/Feature/Query/ComputedRelsSpec.hs, test/spec/Main.hs, test/spec/fixtures/data.sql, test/spec/fixtures/privileges.sql, test/spec/fixtures/schema.sql
Closes https://github.com/PostgREST/postgrest/issues/2144
=> Add computed relationships

CHANGELOG.md, src/PostgREST/DbStructure.hs, src/PostgREST/DbStructure/Relationship.hs, src/PostgREST/Error.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Request/DbRequestBuilder.hs, test/spec/Feature/Query/ComputedRelsSpec.hs, test/spec/Feature/Query/DeleteSpec.hs, test/spec/Feature/Query/EmbedDisambiguationSpec.hs, test/spec/Feature/Query/QuerySpec.hs, test/spec/Feature/Query/RpcSpec.hs, test/spec/Feature/Query/UpdateSpec.hs, test/spec/fixtures/data.sql, test/spec/fixtures/privileges.sql, test/spec/fixtures/schema.sql
Closes https://github.com/PostgREST/postgrest/issues/1984. One to one relationships are detected when:
- There's a foreign key which is also a primary key:
```sql
-- one-to-one rel between students and students_info
CREATE TABLE test.students(
id int
, code text
, name text
, primary key(id, code)
);
CREATE TABLE test.students_info(
id int
, code text
, address text
, primary key(id, code)
, foreign key (id, code) references test.students(id, code)
);
```
- There's a foreign key with an unique constraint
```sql
-- one-to-one rel between country and capital
CREATE TABLE test.country(
id int primary key
, name text
);
CREATE TABLE test.capital(
id int primary key
, name text
, country_id int unique
, foreign key (country_id) references test.country(id)
);
```
([There's a blog post by …
=> feat: add one to one relationship for resource embedding

.github/workflows/ci.yaml
The idea is that this ensures
1. that it's easy for contributors to hack on PostgREST without
getting nix set up
2. we see things break more easily outside the very controlled nix
environment (e.g. it would be easy to add a GHC 9.4.2 build here,
or to see some problems with the version bounds)
I wanted to have a check like this around while working on https://github.com/PostgREST/postgrest/pull/2444, to ensure that that forked dependency doesn't cause cabal builds to fail.
=>  Add a CI check for building with Cabal

CHANGELOG.md, src/PostgREST/Request/Preferences.hs
Deprecate bulk-call in favor of functions with JSON params, which are more efficient. Related to #1385.
=> Deprectate bulk-call

stack.yaml.lock
It turns out an updated base image had libpq in a different location, which means the stack-cached artifacts of e.g. postgresql-libpq were no longer valid.
This is a one-off fix to invalidate the cache.
I'm not sure there's a good way to fix future instances of this -- we might try to determine some kind of hash of the runner and put that into the cache key, but that seems a bit too involved.
=> ci: fix macos build by invalidating cache (fixes #2465)

.github/workflows/ci.yaml, cabal.project.non-nix, nix/overlays/haskell-packages.nix, stack.yaml, stack.yaml.lock
This pulls in the change from https://github.com/PostgREST/postgresql-libpq/pull/1.
This is the postgresql-libpq part of #2349. See #2422 for discussion around forked dependencies.
=> postgresql-libpq: use PostgREST fork with reduced copies

CHANGELOG.md, nix/overlays/haskell-packages.nix, postgrest.cabal, shell.nix, src/PostgREST/Query/SqlFragment.hs, stack.yaml, stack.yaml.lock
(Updated after the merge of #2467)
This update hasql and switches to the new lazy json byte encoder, saving one copy of the request body.
After the merge of the libpq change in #2467, this is now essentially what #2333 was.
=> avoid copy when encoding request body

postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Query/Statements.hs, src/PostgREST/Request/Preferences.hs, src/PostgREST/Response.hs
Adds a `Response.hs` module picking up the work on https://github.com/PostgREST/postgrest/pull/1831.
=> refactor: add Response.hs module

postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Plan.hs, src/PostgREST/Plan/CallPlan.hs, src/PostgREST/Plan/MutatePlan.hs, src/PostgREST/Plan/ReadPlan.hs, src/PostgREST/Query.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Request/Types.hs, test/spec/QueryCost.hs
Scaffolds the plan module. Idea taken from https://github.com/PostgREST/postgrest/issues/1804
> Plan: Use db structure to validate and plan the request, including embeds. plan :: DbStructure -> Request -> Either PlanError QueryPlan
(Mostly renaming/moving files)
=> refactor: add plan module

CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest/QueryParams.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/SchemaCache/Relationship.hs, test/spec/Feature/Query/QuerySpec.hs, test/spec/Feature/Query/RelatedQueriesSpec.hs, test/spec/Main.hs, test/spec/fixtures/data.sql, test/spec/fixtures/schema.sql
Closes https://github.com/PostgREST/postgrest/issues/1414
Allows ordering a table by a related table
```http
GET /projects?select=id,clients(name)&order=clients(name).nullsfirst
[
{"id":5,"clients":null},
{"id":3,"clients":{"name":"Apple"}},
{"id":4,"clients":{"name":"Apple"}},
{"id":1,"clients":{"name":"Microsoft"}},
{"id":2,"clients":{"name":"Microsoft"}} 
]        
```
On many-to-one and one-to-one relationships
=> feat: add related orders

CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest/QueryParams.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/Plan/ReadPlan.hs, src/PostgREST/Query/QueryBuilder.hs, test/spec/Feature/Query/RelatedQueriesSpec.hs, test/spec/Feature/Query/SpreadQueriesSpec.hs, test/spec/Main.hs
Allows unnesting json objects. Closes https://github.com/PostgREST/postgrest/issues/1233.
Instead of getting
```http
GET /grandchild_entities?select=name,child_entities(parent_name:name,entities(grandparent_name:name))&limit=3'
[
{"name":"grandchild entity 1","child_entities":{"parent_name":"child entity 1","entities":{"grandparent_name":"entity 1"}}},
{"name":"grandchild entity 2","child_entities":{"parent_name":"child entity 1","entities":{"grandparent_name":"entity 1"}}},
{"name":"grandchild entity 3","child_entities":{"parent_name":"child entity 2","entities":{"grandparent_name":"entity 1"}}}
]
```
You can get
```http
GET /grandchild_entities?select=name,..child_entities(parent_name:name,..entities(grandparent_name:name))&limit=3
[
{"name":"grandchild entity 1","parent_name":"child …
```
=> feat: add spread embeds

CHANGELOG.md, src/PostgREST/ApiRequest/QueryParams.hs, src/PostgREST/Query.hs, src/PostgREST/Query/QueryBuilder.hs, test/spec/Feature/Query/QuerySpec.hs
Closes https://github.com/PostgREST/postgrest/issues/2340
Allows doing
```http
GET /clients?select=id,name,projects!inner()&projects.name=eq.IOS
[{"id":2,"name":"Apple"}]
```
i.e. filtering on a related table without it showing on the result.
=> feat: Allow embedding without selecting any column

postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, test/doc/Main.hs, test/spec/Feature/Query/RpcSpec.hs
=> Add hint for similar function parameter names when they don't match

src/PostgREST/Error.hs, test/spec/Feature/Query/RpcSpec.hs
Moves the explanations about "single unnamed parameters" to the details instead of the message part of the error. It also removes any mention to resetting the schema cache from other error hints.
=> Clarify error messages for functions

CHANGELOG.md, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/Query.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/PlanSpec.hs, test/spec/Feature/Query/RelatedQueriesSpec.hs
Closes https://github.com/PostgREST/postgrest/issues/2563.
- Offers a more flexible replacement for `!inner`(https://github.com/PostgREST/postgrest/pull/1949):
```bash
curl 'localhost:3000/projects?select=name,clients(*)&clients.id=eq.1&clients=not.is.null'
[{"name":"Windows 7","clients":{"id":1,"name":"Microsoft"}},
{"name":"Windows 10","clients":{"id":1,"name":"Microsoft"}},
{"name":"IOS","clients":{"id":2,"name":"Apple"}},
{"name":"OSX","clients":{"id":2,"name":"Apple"}}]
curl 'localhost:3000/projects?select=name,clients!inner(*)&clients.id=eq.1'
```
-  Allows doing ANTI JOIN(only a LEFT one):
```
curl 'localhost:3000/projects?select=name,clients()&clients=is.null'
[{"name":"Orphan"}]
```
- Allows using `or` across related tables …
=> feat: null filters on embedded resources

CHANGELOG.md, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, test/spec/Feature/Query/EmbedDisambiguationSpec.hs, test/spec/Feature/Query/QuerySpec.hs
Closes #2569 
Contemplating two options:
- Suggest either the `parent` or `child` one at a time. If no parent is found, then suggest the closest match and stop there, otherwise, continue  looking for the child and suggest its closest match.
- ~Suggest both `parent` and `child`, if neither is found then suggest the closest relationship between them.~
Done so far:
=> Add suggestions with fuzzy text search when no relationship is found

cabal.project.non-nix, nix/overlays/haskell-packages.nix, stack.yaml, stack.yaml.lock
This pulls in updated postgreql-libpq from https://github.com/PostgREST/postgresql-libpq/pull/2, compare that PR for details.
~~Once https://github.com/PostgREST/postgresql-libpq/pull/2 is merged, I'll update this PR to reference the updated PostgREST/postgresql-libpq master branch.~~ Done
=> bump postgresql-libpq

CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/Plan/MutatePlan.hs, src/PostgREST/Plan/Types.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Response/OpenAPI.hs, src/PostgREST/SchemaCache.hs, src/PostgREST/SchemaCache/Table.hs, test/spec/Feature/Query/InsertSpec.hs, test/spec/Feature/Query/UpdateSpec.hs
Switches from `json_populate_recordset` to `json_to_recordset`, which we will need for data representations. See #2523 for details.
The impossible panic we discussed in #2523 has been eliminated by creating a `TypedField` type which doesn't allow that situation.
=> Json to recordset

.github/get_cirrusci_freebsd, .github/workflows/ci.yaml
It turns out this is (hopefully) easier than I thought, because we already have an API token available. Let's see...
=> ci: authenticate GitHub API request (fixes #2607)

.github/workflows/ci.yaml, default.nix
Clone of #2604 within the PostgREST project, to hopefully allow access to the cachix token.
The primary point is to cache the nix environment for macos development, too. Running some tests might be a good idea, too.
=> build with nix on macos in CI (and push to cachix)

.github/workflows/cachix.yaml, .github/workflows/ci.yaml, default.nix, nix/static-haskell-package.nix, nix/tools/devTools.nix
This is broken out of #2612; subsumes #2611.
The idea is to have a dedicated workflow to incrementally seed cachix, which can be manually triggered on appropriate pull requests. E.g., when a nixpkgs update or dependency update PR is "ready" but stuck due to CI timing out, we'd manually trigger this workflow to push build results to cachix incrementally.
For the moment, the workflow is run automatically on PR, but that's just for this PR, to be removed before merging.
(There's the same outstanding issue as with #2611, in that building `postgrest-push-cachix` also causes a build of `cabal2nix-postgrest` for no good reason. But currently that justs causes a bit of unnecessary extra work, so maybe we can leave that for later.)
=> ci: Add workflow to seed cachix

src/PostgREST/ApiRequest.hs, src/PostgREST/ApiRequest/QueryParams.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/QuerySpec.hs
Some refactoring that makes https://github.com/PostgREST/postgrest/pull/1582 easier to implement.
=> refactor: dry RPC param parsing

CHANGELOG.md, nix/tools/withTools.nix, src/PostgREST/Error.hs, test/io/postgrest.py, test/io/test_io.py
Fixes #2622
To detect whether PostgreSQL authentication has failed or not, the `FATAL: password authentication failed"` is looked throughout the whole message details. It was only tested at the beginning of the message beforehand and the format of the message has changed at some point.
=> fix: consider authentication failure as a fatal error

nix/tools/loadtest.nix
Before this, `postgrest-loadtest` was failing for me locally on macOS with
```
error opening ./loadtest/result.bin: open ./loadtest/result.bin: no such file or directory
```
which makes sense with the relative path `./loadtest/result.bin` while `vegeta` is run in `./test/load`. Not sure why that wasn't caught in CI.
=> test: fix result path for load test

src/PostgREST/App.hs, src/PostgREST/Plan.hs, src/PostgREST/Query.hs, src/PostgREST/Response.hs, test/spec/fixtures/schema.sql
A step towards removing the `SchemaCache` dependency from `ApiRequest`(https://github.com/PostgREST/postgrest/issues/1804#issuecomment-1267591660).
Paves the way for removing `ProcDescription` from `Target`.
(Needed for implementing https://github.com/PostgREST/postgrest/pull/1582)
=> refactor: move txMode to Plan

nix/tools/release/default.nix
As mentioned on https://github.com/PostgREST/postgrest/pull/2642#issuecomment-1410935106
It just adds another option for a tag:
```
[nix-shell:~/Projects/postgrest]$ postgrest-release
Current version is 10.1.1.20221215
1) 10.1.1.20230131  3) 10.1.2           5) 11.0.0
2) 10.2.1.20230131  4) 10.2.0
```
=> nix: postgrest-release bumps pre-release minor number

CHANGELOG.md, nix/tools/withTools.nix, postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/Plan/ReadPlan.hs, src/PostgREST/Response/OpenAPI.hs, src/PostgREST/SchemaCache.hs, src/PostgREST/SchemaCache/Relationship.hs, src/PostgREST/Workers.hs, test/doc/Main.hs, test/io/fixtures.sql, test/io/postgrest.py, test/io/test_io.py, test/spec/Feature/OpenApi/OpenApiSpec.hs, test/spec/Feature/Query/EmbedDisambiguationSpec.hs, test/spec/Feature/Query/QuerySpec.hs, test/spec/Feature/Query/RpcSpec.hs, test/spec/fixtures/schema.sql
v10.1.1 is currently not stable for production as mentioned on https://github.com/PostgREST/postgrest/issues/2638#issuecomment-1410864086.
We'll need to make a v10.1.2 that includes some fixes.
Included fixes:
The only critical fix is really 7874bee87927ed73ef8d32c9377c53ea97f44101, so if some fixes turn out to be hard to merge(due to refactors and dependency to other commits) we can leave them for v11.
=> v10.1.2 PATCH release

CHANGELOG.md, src/PostgREST/Error.hs, test/spec/Feature/Query/InsertSpec.hs, test/spec/Feature/Query/UpdateSpec.hs
Changes inaccurate error codes to new ones for the following errors:
- Column is not found  when using `columns`
- Time out when acquiring connection from db pool.
=> Change inaccurate error codes to new ones

nix/tools/withTools.nix
Fixes unreliable output on tests, see https://github.com/PostgREST/postgrest/pull/2523#discussion_r1104252813
=> nix: UTC by default for postgrest-with-postgresql

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/Error.hs, src/PostgREST/Workers.hs, test/io/test_io.py
When reaching the timeout on `db-pool-acquisition-timeout`, we don't log an error to stderr. This is useful for admins since they will know that the pool size has to be increased or that queries are taking too long.
=> fix: log to stderr on AcquisitionTimeoutUsageError

.github/workflows/ci.yaml
As discussed on https://github.com/PostgREST/postgrest/pull/2671#issuecomment-1435691023.
=> ci: remove GHC 8.10.7

CHANGELOG.md, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, test/pgbench/1652/new.sql, test/pgbench/1652/old.sql, test/pgbench/2677/new.sql, test/pgbench/2677/old.sql, test/pgbench/README.md, test/pgbench/fixtures.sql, test/spec/Feature/Query/PlanSpec.hs, test/spec/Feature/Query/RpcSpec.hs
Increases transactions per second for RPC on 16% and for INSERTs on 6%.
It uses the fact that [inlining](https://wiki.postgresql.org/wiki/Inlining_of_SQL_functions) can be done on function calls when:
> none of the actual arguments contain volatile expressions or subselects
So basically it goes from:
```sql
WITH
pgrst_payload AS (SELECT '[{"id": 4, "name": "Vier"}, {"id": 5, "name": "Funf", "arr_data": null}, {"id": 6, "name": "Sechs", "arr_data": [1, 2, 3], "field-with_sep": 6}]'::json AS json_data),
pgrst_body AS ( SELECT CASE WHEN json_typeof(json_data) = 'array' THEN json_data ELSE json_build_array(json_data) END AS val FROM pgrst_payload)
INSERT INTO "test"."complex_items"("arr_data", "field-with_sep", "id", "name")
SELECT "arr_data", "field-with_sep", "id", "name"
FROM …
```
=> perf: use LATERAL instead of CTE for json body

src/PostgREST/App.hs, src/PostgREST/Query.hs
This makes what's happening a bit clearer -- there's no apparent reason why these should be within that one big function.
Any better naming ideas than `runPreReq`?
=> refactor: split pre-request function out of setPgLocals

nix/tools/withTools.nix
For knowing where to connect and how to get logs. Example:
```
$PGRST_DB_ANON_ROLE='postgrest_test_anonymous' postgrest-with-postgresql-15 postgrest-run
postgrest-with-postgresql-15: You can connect with: psql 'postgres:///postgres?host=/run/user/1000/postgrest/postgrest-with-postgresql-15-W6B/socket' -U postgrest_test_authenticator
postgrest-with-postgresql-15: You can tail the logs with: tail -f /run/user/1000/postgrest/postgrest-with-postgresql-15-W6B/db.log
07/Mar/2023:12:11:47 -0500: Attempting to connect to the database...
07/Mar/2023:12:11:47 -0500: Connection successful
07/Mar/2023:12:11:47 -0500: Listening on port 3000
07/Mar/2023:12:11:47 -0500: Config reloaded
07/Mar/2023:12:11:47 -0500: Listening for notifications on the pgrst channel
07/Mar/2023:12:11:47 -0500: Schema cache …
```
=> nix: add notices for postgrest-with-* commands

src/PostgREST/ApiRequest.hs, src/PostgREST/ApiRequest/Preferences.hs, src/PostgREST/Plan.hs, src/PostgREST/Query.hs, src/PostgREST/Response.hs
It avoids adding a new iPrefer.. to the ApiRequest every time a preference is added.
=> refactor: add iPreferences to ApiRequest

CHANGELOG.md, src/PostgREST/ApiRequest/Preferences.hs, src/PostgREST/Plan.hs, src/PostgREST/Plan/MutatePlan.hs, src/PostgREST/Plan/Types.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Response.hs, test/pgbench/1567/new.sql, test/pgbench/1567/old.sql, test/pgbench/README.md, test/spec/Feature/Query/InsertSpec.hs, test/spec/Feature/Query/QuerySpec.hs, test/spec/Feature/Query/UpdateSpec.hs, test/spec/fixtures/data.sql, test/spec/fixtures/schema.sql
Closes #1567.
(`field-with_sep` has default 1 on the following)
- Allows bulk insert with defaults
```bash
http POST "localhost:3000/complex_items?columns=id,name,field-with_sep,arr_data" "Prefer: return=representation" <<JSON
[
{"id": 4, "name": "Vier"},
{"id": 5, "name": "Funf", "arr_data": null},
{"id": 6, "name": "Sechs", "field-with_sep": 6, "arr_data": [1,2,3]}
]
JSON
[
{ "arr_data": null, "field-with_sep": 1, "id": 4, "name": "Vier", "settings": null },
{ "arr_data": null, "field-with_sep": 1, "id": 5, "name": "Funf", "settings": null },
{ "arr_data": [ 1, 2, 3 ], "field-with_sep": 6, "id": 6, "name": "Sechs", "settings": null }
]
```
- Allows updating with defaults
```bash
http PATCH "/complex_items?id=eq.3&columns=name,field-with_sep" "Prefer: return=representation" <<JSON …
```
=> feat: undefined json keys as defaults when using `?columns` and a `Prefer` header

src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/PlanSpec.hs
Following discussion on https://github.com/PostgREST/postgrest/pull/1582#issuecomment-1488954603.
So our `ResultSet` type(used for all results of our generated queries) has a body which is a ByteString:
https://github.com/PostgREST/postgrest/blob/7629eff51d7df69bfa7dedfabd5beea18cb7a8cc/src/PostgREST/Query/Statements.hs#L38-L55
This is decoded as a `bytea` with Hasql:
https://github.com/PostgREST/postgrest/blob/7629eff51d7df69bfa7dedfabd5beea18cb7a8cc/src/PostgREST/Query/Statements.hs#L177-L187
At some point I assume it was decoded as `text`, but this is no longer the case. I assume that's why it was needed to cast the result body.
=> refactor: remove character varying and text casting

CHANGELOG.md, src/PostgREST/ApiRequest.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, test/spec/Feature/Query/DeleteSpec.hs, test/spec/Feature/Query/PgSafeUpdateSpec.hs, test/spec/Feature/Query/RangeSpec.hs, test/spec/Feature/Query/RpcSpec.hs, test/spec/Feature/Query/UpdateSpec.hs, test/spec/Feature/Query/UpsertSpec.hs, test/spec/SpecHelper.hs
=> Ignore Range header when the method is different than GET

src/PostgREST/App.hs, src/PostgREST/Plan.hs, src/PostgREST/Plan/CallPlan.hs, src/PostgREST/Query.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/SchemaCache.hs, src/PostgREST/SchemaCache/Proc.hs, test/spec/Feature/Query/RpcSpec.hs
The new LATERAL query used for calling the function, introduced on https://github.com/PostgREST/postgrest/pull/2677, failed on functions that returned a domain like `CREATE DOMAIN projects_domain AS projects`.
Work around that by changing the query conditionally, by obtaining a bool that represents the composite alias on the SchemaCache and only do this on pg 11 and 12.
=> RPC returning table alias now works for pg 11/12

CHANGELOG.md, src/PostgREST/ApiRequest/QueryParams.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/AndOrParamsSpec.hs, test/spec/Feature/Query/QuerySpec.hs, test/spec/fixtures/data.sql
Closes #2501.
As it was mentioned in https://github.com/PostgREST/postgrest/issues/2501#issuecomment-1496618749, the `BETWEEN` operator won't be implemented.
=> feat: Allow filtering by IS DISTINCT FROM

CHANGELOG.md, src/PostgREST/ApiRequest/QueryParams.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Plan.hs, src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/QuerySpec.hs
Closes #1569.
**Edit**: This only works for the `eq,like,ilike,gt,gte,lt,lte,match,imatch` operators.
The `cs/cd` operators don't work for an array type:
```sql
select '{3,4}'::int[] @> ANY('{{3,4,5},{2,3}}');
ERROR:  could not find array type for data type integer[]
LINE 1: select '{3,4}'::int[] @> ANY('{{3,4,5},{2,3}}');
select '{3,4}'::int[] @> ANY('{3,4,5}');
ERROR:  could not find array type for data type integer[]
LINE 1: select '{3,4}'::int[] @> ANY('{3,4,5}');
```
Same for the `ov, sl, sr, nxl, nxr, adj` operators, which operate against range types. For the `fts` operators, it's not a direct translation because `to_tsquery` would have to be done for every element on the array.
=> feat: any/all modifiers for operators

.github/workflows/ci.yaml
On a version release, if the `Release-Github` action fails or is cancelled for any reason then the ARM server will erase the build files regardless. This will make a job rerun to fail when doing the ARM Docker releases. It's not common but it [already happened once](https://github.com/PostgREST/postgrest/actions/runs/4681247197).
This also separates the ARM Docker release action from the x64 one, to make it more manageable to rerun in case of any error.
=> ci: clean files from arm server only on build failure/cancel for a version release

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/Auth.hs, src/PostgREST/Config.hs, src/PostgREST/Config/Database.hs, src/PostgREST/Logger.hs, src/PostgREST/Query.hs, src/PostgREST/SchemaCache.hs, src/PostgREST/SchemaCache/Routine.hs, test/io/fixtures.sql, test/io/test_io.py
Closes https://github.com/PostgREST/postgrest/issues/2468.
Allows changing the isolation level per role
```sql
alter role my_role set default_transaction_isolation = 'serializable';
```
Or per function
```sql
create function serializable_isolation_level()
returns text as $$
-- ....
$$ language sql
set default_transaction_isolation = 'serializable';
```
Both will result in
```sql
BEGIN ISOLATION LEVEL SERIALIZABLE ..
-- SELECT ..
COMMIT
```
Setting the isolation level on a role will affect every operation, while setting it on the function will only affect that particular one.
If the isolation level is set both on role and function the latter isolation level will prevail.
=> feat: set isolation level on roles/functions

CHANGELOG.md, src/PostgREST/Auth.hs
Closes https://github.com/PostgREST/postgrest/issues/1139.
Use a 30 seconds skew by default as per google recommendations [here](https://cloud.google.com/iap/docs/signed-headers-howto#verifying_the_jwt_payload). Previous 1 second skew was too strict. 
Hard to test for now. We'll just monitor if #1139 gets more reports.
=> fix: skew of 30 seconds for JWT validation

nix/tools/withTools.nix
It gets repetitive to set the search_path every time you go in the test db with psql.
=> nix: withTmpDb set search_path to test

nix/tools/cabalTools.nix, test/io/fixtures.sql, test/io/test_io.py
Otherwise manual tests can be deceiving. As commented on https://github.com/PostgREST/postgrest/pull/2810#discussion_r1213841669.
=> nix: use similar config to tests on postgrest-run 

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/Config.hs, src/PostgREST/Config/Database.hs, src/PostgREST/Error.hs, src/PostgREST/SchemaCache.hs, src/PostgREST/SchemaCache/Routine.hs, test/spec/SpecHelper.hs
Close https://github.com/PostgREST/postgrest/issues/2781 and close https://github.com/PostgREST/postgrest/issues/2801.
=> Improved connection recovery on read replicas

src/PostgREST/ApiRequest.hs, src/PostgREST/Config.hs, src/PostgREST/Error.hs, src/PostgREST/MediaType.hs, src/PostgREST/Plan.hs, src/PostgREST/Query.hs, src/PostgREST/Query/Statements.hs, src/PostgREST/Response.hs, src/PostgREST/Response/OpenAPI.hs, test/doc/Main.hs, test/spec/SpecHelper.hs
Previously it was impossible to have doctests for the MediaType module due to recursion:
https://github.com/PostgREST/postgrest/blob/78821a8fe7990022bb9036c24321ab411c55a3b1/src/PostgREST/MediaType.hs#L23-L38
Basically a `MediaType` was able to contain another `MediaType`. See the `MTPlan` constructor.
This caused the `deriving instance Show ...`  setup to fail.
Eliminate recursion by having non-plan media types as a separate type(`NormalMedia`).
Some doctests are now added for `MediaType`.
=> refactor: plan media type

src/PostgREST/ApiRequest.hs, src/PostgREST/Config.hs, src/PostgREST/Error.hs, src/PostgREST/MediaType.hs, src/PostgREST/Plan.hs, src/PostgREST/Query.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Query/Statements.hs, src/PostgREST/Response.hs, src/PostgREST/Response/OpenAPI.hs, test/doc/Main.hs, test/spec/Feature/Query/PlanSpec.hs, test/spec/SpecHelper.hs
Reverts https://github.com/PostgREST/postgrest/pull/2828, that change made https://github.com/PostgREST/postgrest/pull/2825 more difficult to implement.
doctests remain by removing `MTPlanAttrs`.
=> refactor: remove MTPlanAttrs to doctest

.github/workflows/ci.yaml, CHANGELOG.md, src/PostgREST/Plan.hs, test/spec/Feature/Query/PlanSpec.hs
Our custom build for ARM [postgrest-v11.1.0-ubuntu-aarch64.tar.xz](https://github.com/PostgREST/postgrest/releases/download/v11.1.0/postgrest-v11.1.0-ubuntu-aarch64.tar.xz) is not working on Ubuntu 18.04. This because it requires a GLIBC > 2.27. 
[OverloadedRecordDot](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/overloaded_record_dot.html) requires GHC 9.2.0, hence a GLIBC > 2.27.
Stick to supporting GHC 9.0.2, which is the latest supported version on Ubuntu: https://packages.ubuntu.com/search?keywords=ghc. This by adding a check on CI and removing `OverloadedRecordDot` usage.
- An alternative would be providing a static binary for ARM: https://github.com/PostgREST/postgrest/issues/2408, https://github.com/PostgREST/postgrest/pull/2332.
- Though sticking to the latest supported …
=> ci: check against GHC 9.0.2

.github/scripts/arm/build.sh, .github/workflows/ci.yaml
Related to #2834
Makes it similar to the Linux build with cabal:
- Remove the hard coded GHC version from the arm build script and puts it in the yaml file instead.
- Uses the [default cabal version by ghcup](https://www.haskell.org/ghcup/install/#which-versions-get-installed).
[Working in test repo](https://github.com/laurenceisla/github-actions-test/actions/runs/5338068914).
=> ci: tweak arm builds using cabal

CHANGELOG.md, src/PostgREST/SchemaCache.hs, test/spec/Feature/Query/InsertSpec.hs, test/spec/fixtures/schema.sql
Closes https://github.com/PostgREST/postgrest/issues/2840.
=> fix: Prefer: missing=default with DOMAIN defaults

CHANGELOG.md, src/PostgREST/AppState.hs, src/PostgREST/Config.hs, test/doc/Main.hs, test/io/fixtures.sql, test/io/test_io.py
=> Add access to the PostgREST version through SQL

src/PostgREST/ApiRequest/QueryParams.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/MediaType.hs, src/PostgREST/Plan/ReadPlan.hs, src/PostgREST/Plan/Types.hs, src/PostgREST/SchemaCache/Identifiers.hs, src/PostgREST/SchemaCache/Relationship.hs
Closes https://github.com/PostgREST/postgrest/issues/2627.
Now we can take the repro on https://github.com/PostgREST/postgrest/issues/2846, do a couple of `traceShowId` and quickly pinpoint the problem:
```
$ postgrest-with-postgresql-15 postgrest-run
[CoercibleStmnt (CoercibleFilterNullEmbed True "clients_projects_1")]
[Node {rootLabel = ReadPlan {select = [(CoercibleField {cfName = "*", cfJsonPath = [], cfIRType = "", cfTransform = Nothing, cfDefault = Nothing},Nothing,Nothing)], from = QualifiedIdentifier
{qiSchema = "test", qiName = "projects"}, fromAlias = Just "projects_1", where_ = [], order = [], range_ = 0 <= x, relName = "projects", relToParent = Just (Relationship {relTable = QualifiedI
dentifier {qiSchema = "test", qiName = "clients"}, relForeignTable = QualifiedIdentifier …
```
=> chore: show on ReadPlan and MediaType

CHANGELOG.md, src/PostgREST/CLI.hs, test/io/fixtures.yaml
Now that we can check the version from many sources, it makes sense to also allow it from the command line. This PR adds the `-v` / `--version` option and changes the following:
```bash
$ postgrest --version
Invalid option `--version'
...
```
To:
```bash
$ postgrest --version
PostgREST 11.1.0 (e752224)
```
=> Add the -v/--version option to show the version information

CHANGELOG.md, src/PostgREST/MediaType.hs, src/PostgREST/Plan.hs, src/PostgREST/Query.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Query/Statements.hs, src/PostgREST/SchemaCache/Routine.hs
Previously:
```sql
curl -I localhost:3000/projects -H "Prefer: count=exact"
tail -f /run/user/1000/postgrest/postgrest-with-postgresql-15-vGF/db.log
WITH pgrst_source AS ( SELECT "test"."projects".* FROM "test"."projects"     )  SELECT null::bigint AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total,
coalesce(json_agg(_postgrest_t), '[]') AS body, -- note here
nullif(current_setting('response.headers', true), '') AS response_headers, nullif(current_setting('response.status', true), '') AS response_status FROM ( SELECT * FROM pgrst_source ) _postgrest_t
```
Now:
```sql
curl -I localhost:3000/projects -H "Prefer: count=exact"
tail -f /run/user/1000/postgrest/postgrest-with-postgresql-15-N94/db.log
WITH pgrst_source AS ( SELECT "test"."projects".* FROM "test"."projects"     ) , …
```
=> fix: HEAD unnecessarily executing aggregates

CHANGELOG.md, src/PostgREST/Plan.hs, src/PostgREST/Plan/MutatePlan.hs, src/PostgREST/Plan/ReadPlan.hs, src/PostgREST/Plan/Types.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/JsonOperatorSpec.hs, test/spec/Feature/Query/PlanSpec.hs, test/spec/fixtures/schema.sql
Closes https://github.com/PostgREST/postgrest/issues/2594
Before:
```
curl "localhost:3000/bets?data_jsonb->>contractId=eq.1" -H "Accept: application/vnd.pgrst.plan"
Aggregate  (cost=32.26..32.28 rows=1 width=112)
->  Seq Scan on bets  (cost=0.00..32.23 rows=6 width=36)
Filter: ((to_jsonb(data_jsonb) ->> 'contractId'::text) = '1'::text)
```
Now:
```
curl "localhost:3000/bets?data_jsonb->>contractId=eq.1" -H "Accept: application/vnd.pgrst.plan"
Aggregate  (cost=12.67..12.69 rows=1 width=112)
->  Bitmap Heap Scan on bets  (cost=4.18..12.65 rows=4 width=68)
Recheck Cond: ((data_jsonb ->> 'contractId'::text) = '1'::text)
->  Bitmap Index Scan on bets_data_jsonb  (cost=0.00..4.18 rows=4 width=0)
Index Cond: ((data_jsonb ->> 'contractId'::text) = '1'::text)
```
=> fix: unused index on jsonb/jsonb arrow filter

CHANGELOG.md, src/PostgREST/Plan.hs, test/spec/Feature/Query/RelatedQueriesSpec.hs, test/spec/fixtures/schema.sql
Fixes https://github.com/PostgREST/postgrest/issues/2862
Basically makes the implementation for https://postgrest.org/en/stable/references/api/resource_embedding.html#null-filtering-on-embedded-resources less strict.
Before it used to enforce only null filters where applied, which caused the errors in #2862. Now it removes he null filter restriction.
=> fix: null filtering on embed when column=relation

CHANGELOG.md, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Response/OpenAPI.hs, src/PostgREST/SchemaCache.hs, src/PostgREST/SchemaCache/Routine.hs, test/spec/Feature/Query/RpcSpec.hs, test/spec/Feature/Query/UpdateSpec.hs, test/spec/fixtures/schema.sql
=> fix: paramaters of type character and bit not ignoring length

CHANGELOG.md, src/PostgREST/ApiRequest/Preferences.hs, src/PostgREST/Plan.hs, src/PostgREST/Query/Statements.hs, src/PostgREST/Response.hs, test/doc/Main.hs, test/spec/Feature/Query/DeleteSpec.hs, test/spec/Feature/Query/InsertSpec.hs, test/spec/Feature/Query/SingularSpec.hs, test/spec/Feature/Query/UpdateSpec.hs, test/spec/Feature/Query/UpsertSpec.hs
=> Add Preference-Applied header in response for Prefer: return=representation/headers-only/minimal

CHANGELOG.md, src/PostgREST/Plan.hs
=> deprecate: target embedding disambiguation

CHANGELOG.md, nix/overlays/haskell-packages.nix, postgrest.cabal, stack.yaml, stack.yaml.lock
This pushes the solution proposed in #2906 upstream (https://github.com/diogob/hasql-notifications/pull/18)
=> Attempt to fix #2524 by upgrading hasql-notifications.

src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Plan.hs, src/PostgREST/Query.hs, src/PostgREST/Response.hs, test/spec/Feature/OpenApi/OpenApiSpec.hs
Part of https://github.com/PostgREST/postgrest/pull/2825.
=> refactor: move media type logic to Plan module

.github/workflows/loadtest.yaml
Introduces loadtest job for main branch that runs loadtest against latest release instead of itself
fixes #2945
=> ci: loadtest commits to main against latest release

src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/RelatedQueriesSpec.hs, test/spec/fixtures/data.sql, test/spec/fixtures/schema.sql
=> fix: Bug when Null Filtering on embedded resources

CHANGELOG.md, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Auth.hs, src/PostgREST/Response.hs, test/spec/Feature/Query/NullsStripSpec.hs, test/spec/Feature/Query/ServerTimingSpec.hs, test/spec/Main.hs, test/spec/SpecHelper.hs
=> feat: add Server-Timing header with JWT duration

.github/workflows/loadtest.yaml
Prevents the loadtest on merge to main being skipped since whole workflow is already triggered by pushes to `main` only
related to #2946
=> ci: less strict conditions for loadtest in main

src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/RelatedQueriesSpec.hs
=> fix: Error when requesting `count` with Null embed filters

.github/workflows/loadtest.yaml, nix/tools/loadtest.nix
Lets `postgrest-loadtest-against` accept multiple refs performing loadtests against all of them; and 
introduces loadtesting PRS against latest release as well.
The downside is we're now unable to pass addtional parameters to vegeta (due to limitation of argbash's support of infinite parameters), please let me know if this is a problem (/cc um… @wolfgangwalther?)
=> ci: loadtest PRs against latest releases

.github/workflows/ci.yaml, default.nix, nix/overlays/postgresql-future.nix
Since it's already added to `nixpkgs`, we can test on PostgreSQL 16 now: https://github.com/PostgREST/postgrest/issues/2865#issuecomment-1724071705
Locally, tests run without issues, added options to test on CI too.
Closes #2865
=> Test on PostgreSQL 16

src/PostgREST/App.hs, src/PostgREST/Query.hs, src/PostgREST/Response.hs
Part of #2771
created per the suggestion at https://github.com/PostgREST/postgrest/pull/2964#issuecomment-1737441167
=> refactor: make Response module pure

CHANGELOG.md, postgrest.cabal, src/PostgREST/ApiRequest/Preferences.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/Response.hs, test/io/test_io.py, test/spec/Feature/Query/PreferencesSpec.hs, test/spec/Main.hs
=> feat: add handling=strict/lenient for Prefer header

CHANGELOG.md, src/PostgREST/Plan.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/SchemaCache.hs, src/PostgREST/SchemaCache/Relationship.hs, test/spec/Feature/Query/ComputedRelsSpec.hs, test/spec/fixtures/schema.sql
=> fix: RPC returning tables not embedding correctly when using overloaded functions for computed relationships

CHANGELOG.md, src/PostgREST/Config.hs
Closes #2970. Continues what's specified in https://github.com/PostgREST/postgrest/pull/2977#issuecomment-1743836200
=> Fix regression that rejects URI connection strings with certain unescaped characters in the password

CHANGELOG.md, postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/Response.hs, src/PostgREST/Response/Performance.hs, test/io/test_io.py, test/io/util.py, test/spec/Feature/Query/ServerTimingSpec.hs, test/spec/SpecHelper.hs
Introduces the performance metrics' collection and rendering in `Server-Timing` header 
fixes #2771 
* `query`
* `jwt`
* `plan`
* `render`
=> Add more data to `Server-Timing` header

cabal.project.freeze
Introduces `cabal.project.freeze` to fix build errors caused by `deferred-folds` upgrade, "GHC on Linux" jobs in particular
fixes #3000
=> build: add cabal.project.freeze

test/io/postgrest.py, test/io/test_io.py
Also increase schema cache sleep to 0.2 as 0.1 tends to fail in CI.
=> test: DRY scache/config sleep in io tests

CHANGELOG.md, src/PostgREST/RangeQuery.hs, test/spec/Feature/Query/RangeSpec.hs
Related to: https://github.com/PostgREST/postgrest/issues/2824#issuecomment-1760490793
=> fix: regression by reverting fix that returned 206 when first-pos=length in Range header

CHANGELOG.md, src/PostgREST/ApiRequest/Preferences.hs, src/PostgREST/Query.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, src/PostgREST/Query/Statements.hs, src/PostgREST/Response.hs, test/spec/Feature/Query/MultipleSchemaSpec.hs, test/spec/Feature/Query/PlanSpec.hs, test/spec/Feature/Query/ServerTimingSpec.hs, test/spec/Feature/Query/UpsertSpec.hs, test/spec/Feature/RollbackSpec.hs
This might fix #1070.
- `PUT` returns `201` instead of `200` when rows are inserted
- `POST` with `Prefer: resolution=merge-duplicates` returns `200` instead of `201` when no rows are inserted
=> fix: HTTP status responses for upserts

src/PostgREST/Config.hs, test/io/test_io.py
Implements https://github.com/PostgREST/postgrest-docs/pull/688#discussion_r1373476525
=> allow all origins when server-cors-allowed-origins is an empty string

.github/PULL_REQUEST_TEMPLATE.md
Adds explanation of the prefixes used for commit messages.
=> chore: add prefix info to the PR template

nix/README.md, nix/UPGRADE.md, nix/tools/release/docker-hub-full-description.md
=> fix: typos

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/Query.hs, src/PostgREST/SchemaCache.hs, src/PostgREST/SchemaCache/Routine.hs, test/io/fixtures.sql, test/io/test_io.py
=> feat: add statement_timeout set on functions

CHANGELOG.md, src/PostgREST/AppState.hs, src/PostgREST/Config/Database.hs, src/PostgREST/Config/PgVersion.hs, src/PostgREST/Query.hs, test/io/fixtures.sql, test/io/test_io.py
If they have `GRANT SET ON PARAMETER <setting> TO <authenticator>`.
Closes https://github.com/PostgREST/postgrest/issues/3045.
=> feat: apply super settings on impersonated roles

.github/actions/setup-nix/action.yaml, .github/workflows/ci.yaml, .github/workflows/loadtest.yaml
This PR introduces caching of the Nix store for nix-based CI jobs, improving "nix setup" build step 2x to 3x, depending on the job
Closes #2990
Changes introduced:
* Reworked the `setup-nix` action:
- upgraded Nix to 2.13.6 for CI jobs
- added [cache-nix-action](https://github.com/nix-community/cache-nix-action) to cache nix store
- added `cache-id` parameter to be able to fine-tune caches
* unifying cache keys' naming scheme across the workflows, making them easier identifiable
* Introduced the `merge-nix-caches` job, which supposed to merge mostly similar nix-based jobs' caches. Had to uncomment it because it couldn't purge per-job caches (to save space) being run under my account, but the work could be continued right where it stopped
TODO: enable Nix garbage collecting
=> ci: cache Nix store with cache-nix-action

CHANGELOG.md, main/Main.hs, postgrest.cabal, src/PostgREST/Admin.hs, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/Unix.hs, test/io/test_io.py, test/spec/Main.hs
Documents and properly handles the special value of `0` for `server-port` config. Before this PR, the value was passed through and handled by the platform's `getaddrinfo` implementation, seemingly resulting in binding to a random port. This PR makes it official and binds to random port explicitly.
Other changes it introduces:
* Simplifies app starting logic, moving platform-dependent POSIX-specific code to `PostgREST.Unix`, making it the only file with the `LANGUAGE CPP` pragma and reducing the amount of indirection. Pretty sure the indirection in question was here on purpose, let me know if that's still the case — tests do pass, things work fine, so I've decided to give it a shot.
* Recent releases of `network` and all Windows released since 5 years ago actually do support Unix domain …
=> Display an actual TCP port app is bound to

src/PostgREST/App.hs, src/PostgREST/Response/Performance.hs, test/spec/Feature/Query/ServerTimingSpec.hs
=> Change timing name from 'query' to 'transaction' and add ApiRequest timing

src/PostgREST/CLI.hs
As mentioned in https://github.com/PostgREST/postgrest/pull/3064#issuecomment-1825803785
=> chore: add missing --example for server-timing-enabled

CHANGELOG.md, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/App.hs, src/PostgREST/Error.hs, src/PostgREST/Response/Performance.hs, test/spec/Feature/Query/ServerTimingSpec.hs
`render` is a loaded term than might be thought as the generation of a full HTML page. While for this phase we only process the status and the headers.
Changing it to `response` so is not misleading at least. Users can check the docs for clarification.
=> chore: change server timing render to response

.github/workflows/ci.yaml
Recent and, more importantly, recommended by `ghcup` cabal adopted XDG guidelines and stores data [across multiple directories under `$HOME`](https://cabal.readthedocs.io/en/stable/config.html#directories). 
Creating `~/.cabal` manually returns old behavior and allows caching single directory again.
UPD: the cache entry is in at https://github.com/PostgREST/postgrest/actions/caches#cache-entry-cache-cabal-Linux-9.2.4-d8460256acb9e907b2ffa2affd3a649ad1c6b6bd6aa4fdaa0cc471f49233e884-5dced405a4da11e069fe31a9ae431e31bacfd4cb6458672788062d7a6a9b8a6e
UPD: caching works again, the "Install dependencies" job takes 23 sec again
=> ci: fixes job caches not producing after recent cabal upgrade

src/PostgREST/Response/Performance.hs, test/doc/Main.hs
Sends the `response` metric to the end of the `Server-Timing` header and makes the doctest work.
=> chore: fix server-timing metric order and doctest

.github/workflows/ci.yaml
Makes it to cache only relevant directories, adds `dist-newstyle` to prevent needless rebuilding even harder and shortens cache key name by supplying `hashFiles`multiple arguments. Reference: https://github.com/actions/cache/blob/main/examples.md#haskell---cabal
=> ci: cabal+GHC: tweak caching

src/PostgREST/App.hs, src/PostgREST/Response/Performance.hs
Refactor the `Performance.hs` module.
=> refactor: use a data type instead of Map for Server Timing

src/PostgREST/Plan.hs, src/PostgREST/SchemaCache.hs, test/spec/Feature/Query/CustomMediaSpec.hs, test/spec/fixtures/schema.sql
With the SQL handlers for custom media types (https://github.com/PostgREST/postgrest/pull/2825), it's not possible to implement the `file` function on [Providing images for img](https://postgrest.org/en/stable/how-tos/providing-images-for-img.html#improved-version). i.e a generic function that serves different media types.
Allow using `*/*` as a return type for SQL handlers.
```sql
create domain "*/*" as bytea;
create or replace function ret_some_mt ()
returns "*/*" as $$
declare
req_accept text := current_setting('request.headers', true)::json->>'accept';
resp bytea;
begin
case req_accept
when 'app/chico'   then resp := 'chico';
when 'app/harpo'   then resp := 'harpo';
when '*/*'         then
perform set_config('response.headers', '[{"Content-Type": "app/groucho"}]', true);
resp := …
```
=> feat: custom SQL handler for the "*/*" media type

.github/actions/setup-nix/action.yaml, .github/workflows/ci.yaml, .github/workflows/loadtest.yaml
Introduces a nix cache warm-up job, which prefetches all the derivations we ever need to the Nix store, which is cached right away. Such cache is reused then in further actions, reducing in-job downloads to zero.
Before this PR every nix-involving job (13 of them on Linux) took 3 to 4 minutes to do "nix setup" due to downloading 121 to 1409 paths, 300 to 1360 MB big. While these jobs cache Nix store here and there, there's a handful of them, multiplied by 2.3-ish GB in size, and thus they exceed the upper cache limit for GH Actions of 10 GB. 
After merging this PR, a cold run takes ~6 minutes to warm up the cache, then every nix-involving job takes 1:30 mins to unpack the cache and have all the derivations installed. A warm run takes 1 minute of a no-op cache warm up step and the same …
=> ci: merge cached Nix stores

CHANGELOG.md, src/PostgREST/ApiRequest/QueryParams.hs, test/memory/memory-tests.sh, test/spec/Feature/Query/JsonOperatorSpec.hs, test/spec/fixtures/data.sql
=> fix: allow using special characters in json keys

.github/workflows/ci.yaml, .github/workflows/loadtest.yaml
This PR enables cancelling in-progress jobs when new commits to the branch arrive. This prevents the case of waiting for previous test run against outdated code, thus shortening the feedback loop and improving developer experience overall. And, by increasing Github Actions runners' throughput, it improves peers' developer experience as well.
After this PR updating a non-release branch would cancel currently running CI jobs against such branch. Case in point: https://github.com/PostgREST/postgrest/actions/runs/7132944815?pr=3095
=> ci: test only head of branch

CHANGELOG.md, src/PostgREST/ApiRequest.hs, test/spec/Feature/Query/InsertSpec.hs, test/spec/Feature/Query/UpdateSpec.hs
Drops Aeson's parser error from the output in favor of a generic message, per the suggestion in #2344.
Fixes #2344
=> fix: replace json parser error with generic msg

CHANGELOG.md, src/PostgREST/Plan.hs, src/PostgREST/SchemaCache.hs, src/PostgREST/SchemaCache/Routine.hs, test/spec/Feature/Query/CustomMediaSpec.hs, test/spec/fixtures/schema.sql
Now it sets application/octet-stream as the generic type.
Closes #3089.
=> fix: any handler sets a default application/json

CHANGELOG.md, src/PostgREST/ApiRequest/Preferences.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Query.hs, src/PostgREST/Response.hs, test/spec/Feature/Query/PreferencesSpec.hs
=> feat: add max-affected preference to prefer header

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/AppState.hs
=> fix: misleading "Starting.." logs on scache reload

.github/actions/setup-nix/action.yaml
Reverts PostgREST/postgrest#3135. It completely broke the CI.
=> Revert "build(deps): bump nix-community/cache-nix-action from 4.0.3 to 5.0.1 in /.github/actions/setup-nix"

CHANGELOG.md, src/PostgREST/Error.hs, test/spec/Feature/Query/ErrorSpec.hs, test/spec/Main.hs, test/spec/fixtures/schema.sql
Closes #3205.
Also considers that pg-safeupdate uses the `cardinality_violation`([ref](https://github.com/eradman/pg-safeupdate/blob/master/safeupdate.c#L38-L46)) code for reporting an error and in this case we want to keep `400 Bad Request`. This is done by checking the pg-safeupdate error message.
=> fix: wrong subquery error returning as 400 status

CHANGELOG.md, src/PostgREST/Admin.hs, test/io/test_io.py
This is a work-in-progress implementation of https://github.com/PostgREST/postgrest/issues/3171.
=> Dump config through Admin API implementation

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/Query.hs, src/PostgREST/SchemaCache.hs, src/PostgREST/SchemaCache/Routine.hs, test/io/fixtures.sql, test/io/test_io.py
=> feat: apply all function settings as transaction-scoped settings

CHANGELOG.md, src/PostgREST/AppState.hs, src/PostgREST/SchemaCache.hs, test/memory/memory-tests.sh
Closes https://github.com/PostgREST/postgrest/issues/3212.
Also related to https://github.com/PostgREST/postgrest/issues/2450.
=> feat: log schema cache stats to stderr

src/PostgREST/AppState.hs, src/PostgREST/Config/Database.hs, src/PostgREST/Config/PgVersion.hs
Closes #3184
Logs now show:
```
09/Feb/2024:16:54:47 -0500: Starting PostgREST 11.2.0 (eaa1d81)...
09/Feb/2024:16:54:47 -0500: Admin server listening on port 3001
09/Feb/2024:16:54:47 -0500: Attempting to connect to the database...
09/Feb/2024:16:54:47 -0500: Listening on port 3000
09/Feb/2024:16:54:47 -0500: Successfully connected to PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 12.3.0, 64-bit
```
=> feat: log full pg version to stderr on connection

src/PostgREST/Response/Performance.hs, test/io/test_io.py
Make `Server-Timing` durations match the documentation (see #3219) and document measurement units in source.
=> fix: fixes server timings' precision

postgrest.cabal, src/PostgREST/Admin.hs, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/Logger.hs, src/PostgREST/Observation.hs, test/spec/Main.hs
- Centralizes log traces into a single module. Which improves maintainability and removes some complexity from `AppState`.
- Will enable handling verbosity on log traces (required for https://github.com/PostgREST/postgrest/pull/3229)
- Might also help with opentelemetry (https://github.com/PostgREST/postgrest/pull/3140)
- Got the structure from https://github.com/nikita-volkov/hasql-pool/pull/40.
- Move the messages from the Logger to Observation (`showObservation`).
- There are more improvements to make but it will involve changing the messages. Wanted to keep the behavior as is for now.
=> refactor: add observation module

docs/references/api/resource_embedding.rst
Adds an example on using `or` across multiple resources to the Null Embedding section.
=> docs: add using `or` across embedded resources

src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/Logger.hs, src/PostgREST/Observation.hs
Removes the observation messages from the Logger.
Also, this makes it possible to test the error messages without IO (using a different `observer` in the tests).
=> refactor: make observation messages pure

CHANGELOG.md, src/PostgREST/AppState.hs, src/PostgREST/Observation.hs
Helps with https://github.com/PostgREST/postgrest/issues/3046. Logs now show:
```
21/Feb/2024:15:48:37 -0500: Starting PostgREST 12.1 (160caaf)...
...
21/Feb/2024:15:48:37 -0500: Schema cache queried in 18.3 milliseconds
21/Feb/2024:15:48:37 -0500: Schema cache loaded 264 Relations, 221 Relationships, 141 Functions, 15 Domain Representations, 45 Media Type Handlers
21/Feb/2024:15:48:37 -0500: Schema cache loaded in 12.2 milliseconds
```
=> feat: log schema cache load time

default.nix, nix/tools/cabalTools.nix, nix/tools/memory.nix
Runs a profiled build of postgREST that can be used for optimization.
=> nix: add `postgrest-profiled-run`

docs/references/api/functions.rst, docs/references/api/tables_views.rst
Clears doubts about if indexes will be used by PostgREST filters.
Also did some reordering and mentioned why casting is not allowed on horizontal filtering.
=> docs: add index usage section

CHANGELOG.md
=> changelog: add how to detect o2o rels on v10.0.0

test/spec/Feature/Query/InsertSpec.hs, test/spec/Feature/Query/UpdateSpec.hs
insignificant whitespace according to https://datatracker.ietf.org/doc/html/rfc8259#section-2
=> test: insignificant JSON whitespace on writes

CHANGELOG.md, src/PostgREST/Query/SqlFragment.hs, test/pgbench/2676/new.sql, test/pgbench/2676/old.sql, test/pgbench/README.md, test/spec/Feature/Query/PlanSpec.hs
Closes #2676. Removes `json_typeof/jsonb_typeof` by using some light validation on the json body using lazy bytestring functions.
- grants ~10% perf increase. 
+ can be confirmed with the PlanSpec change.
+ can be confirmed manually with pgbench like:
```
$ postgrest-with-postgresql-16 -f test/pgbench/fixtures.sql pgbench -U postgres -n -T 10 -f test/pgbench/2676/old.sql 
tps = 3480.654744 (without initial connection time)
$ postgrest-with-postgresql-16 -f test/pgbench/fixtures.sql pgbench -U postgres -n -T 10 -f test/pgbench/2676/new.sql 
tps = 3973.138881 (without initial connection time)
```
- memory usage is kept the same
- no need for a new `content-type` as per a previous idea on https://github.com/PostgREST/postgrest/issues/2676. This is an improvement for every write case.
=> perf: remove json_typeof

CHANGELOG.md, src/PostgREST/AppState.hs, src/PostgREST/Observation.hs
Related to https://github.com/PostgREST/postgrest/discussions/3313.
Now when the LISTEN channel dies we log:
```
11/Mar/2024:14:11:11 -0500: FatalError {fatalErrorMessage = "Error checking for PostgreSQL notifications"}. Retrying listening for notifications on the pgrst channel..
```
It used to be:
```
11/Mar/2024:12:50:17 -0500: Retrying listening for notifications on the pgrst channel..
```
The lib error is still uninformative but that's another issue https://github.com/PostgREST/postgrest/issues/3320#issuecomment-1989198685
=> fix: don't hide error on LISTEN channel failure

CHANGELOG.md, nix/overlays/haskell-packages.nix, src/PostgREST/AppState.hs, src/PostgREST/Observation.hs
Based on https://github.com/diogob/hasql-notifications/pull/21
The logs now show:
```
13/Mar/2024:10:52:54 -0500: Could not listen for notifications on the pgrst channel. server closed the connection unexpectedly This probably means the server terminated abnormally before or while processing the request. Retrying listening for notifications..
```
=> fix: upgrade hasql-notifications to show error

cabal.project.freeze, nix/overlays/haskell-packages.nix, postgrest.cabal, stack.yaml, stack.yaml.lock
Feedback from https://github.com/PostgREST/postgrest/pull/3324
=> chore: update cabal/stack new hasql-notifications

.github/workflows/test.yaml, nix/tools/devTools.nix, nix/tools/tests.nix, test/io/test_big_schema.py, test/io/test_io.py, test/io/util.py
Proves https://github.com/PostgREST/postgrest/issues/3327
=> test: requests wait for schema cache load 

CHANGELOG.md, src/PostgREST/AppState.hs, src/PostgREST/Observation.hs, test/io/__snapshots__/test_cli/test_schema_cache_snapshot[dbRoutines].yaml, test/io/fixtures.sql, test/io/test_cli.py, test/io/test_io.py
Now shows:
```
19/Mar/2024:00:21:18 -0500: The "pgrst" channel got a schema cache reload message
19/Mar/2024:00:21:18 -0500: Attempting to connect to the database...
19/Mar/2024:00:21:18 -0500: Successfully connected to PostgreSQL 16.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 12.3.0, 64-bit
19/Mar/2024:00:21:18 -0500: Config reloaded
19/Mar/2024:00:21:18 -0500: Schema cache queried in 10.1 milliseconds
19/Mar/2024:00:21:18 -0500: Schema cache loaded 264 Relations, 221 Relationships, 141 Functions, 15 Domain Representations, 45 Media Type Handlers
19/Mar/2024:00:21:18 -0500: Schema cache loaded in 9.1 milliseconds
19/Mar/2024:00:21:22 -0500: The "pgrst" channel got a config reload message
19/Mar/2024:00:21:22 -0500: Config reloaded
```
=> fix: log on LISTEN notification

nix/README.md, nix/overlays/haskell-packages.nix
Added an example on how to use a local library for development purposes. Useful to debug said library in the context of PostgREST development.
=> nix: add example on how to use a library locally

CHANGELOG.md, docs/references/errors.rst, docs/references/schema_cache.rst, src/PostgREST/Error.hs, test/spec/Feature/Query/InsertSpec.hs, test/spec/Feature/Query/UpdateSpec.hs
Closes https://github.com/PostgREST/postgrest/issues/3361
=> fix: clarify PGRST204 error message

CHANGELOG.md, docs/references/schema_cache.rst, src/PostgREST/AppState.hs, test/io/test_big_schema.py
This reverts commit 727ef465c10cea4797422afbd784ccfd3f5293aa https://github.com/PostgREST/postgrest/pull/3335. Discussed on https://github.com/PostgREST/postgrest/issues/3327#issuecomment-2027747867.
Also documents requests waiting for the schema cache.
=> Revert "fix: slow responses on schema cache reload"

src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs, src/PostgREST/Plan.hs, src/PostgREST/Query.hs, src/PostgREST/Response.hs
- deduplicates timing calculation for the different steps
- enabling query logging later on will be simpler
Previously discussed on https://github.com/PostgREST/postgrest/issues/1804
=> refactor: one entrypoint for Plan/Response/Query

ARCHITECTURE.md
Feedback from https://github.com/PostgREST/postgrest/pull/3384#discussion_r1556186344
=> docs: add architecture description

nix/overlays/haskell-packages.nix, postgrest.cabal, src/PostgREST/Error.hs, stack.yaml, stack.yaml.lock, test/io/test_big_schema.py
=> perf: fix space leaks by downgrading fuzzyset to v0.2.4

src/PostgREST/Admin.hs, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/Config.hs, src/PostgREST/Logger.hs, src/PostgREST/Observation.hs, src/PostgREST/Query.hs, test/spec/Main.hs, test/spec/SpecHelper.hs, test/spec/fixtures/schema.sql
With this:
- Is no longer necessary to pass observer as an argument to every function that needs observations.
- We can invoke the observer on every function that uses AppConfig. However it'd be better to just call the observer in the upper modules (like on App.hs).
=> refactor: observation handler to AppConfig

test/io/test_io.py
It's easier to maintain this way in case there are new log lines.
Related to https://github.com/PostgREST/postgrest/pull/3229#issuecomment-2054760951
=> test: use postgrest.read_stdout in io tests

CHANGELOG.md, cabal.project.freeze, nix/overlays/haskell-packages.nix, postgrest.cabal, src/PostgREST/AppState.hs, src/PostgREST/Logger.hs, src/PostgREST/Observation.hs, stack.yaml, stack.yaml.lock, test/io/test_io.py, test/spec/Main.hs
For https://github.com/PostgREST/postgrest/issues/3214.
The logs look like this (only for `log-level=info`):
```
14/Apr/2024:22:03:37 -0500: Starting PostgREST 12.1 (36ba330)...
14/Apr/2024:22:03:37 -0500: Attempting to connect to the database...
14/Apr/2024:22:03:37 -0500: Connection b63f8c6d-1423-4f7e-bd81-73ff25244033 is being established
14/Apr/2024:22:03:37 -0500: Connection b63f8c6d-1423-4f7e-bd81-73ff25244033 is available
...
14/Apr/2024:22:05:43 -0500: Connection b63f8c6d-1423-4f7e-bd81-73ff25244033 is terminated due to max idletime
...
14/Apr/2024:22:05:43 -0500: Connection f0813512-f4e6-4795-b156-ba140d2bc602 is being established
14/Apr/2024:22:05:43 -0500: Connection f0813512-f4e6-4795-b156-ba140d2bc602 is terminated due to network error
...
14/Apr/2024:21:47:44 -0500: …
```
=> feat: log connection pool events on log-level=info

CHANGELOG.md, docs/references/configuration.rst, src/PostgREST/CLI.hs, src/PostgREST/Config.hs, src/PostgREST/Logger.hs, test/io/test_io.py
On https://github.com/PostgREST/postgrest/pull/3213, the following log lines were added:
```
22/Apr/2024:16:16:20 -0500: Schema cache queried in 16.3 milliseconds
22/Apr/2024:16:16:20 -0500: Schema cache loaded 264 Relations, 221 Relationships, 142 Functions, 15 Domain Representations, 45 Media Type Handlers
22/Apr/2024:16:16:20 -0500: Schema cache loaded in 16.7 milliseconds
```
But the `Schema cache loaded in 16.7 milliseconds` line is really for debugging, the user cannot take any action for reducing that time.
Only log the above line when `log-level=debug`.
=> feat: add log-level=debug

.github/workflows/ci.yaml
Should solve #3439.
Basically, it removes the generated `postgrest-build-*` directories from the server even when any of the `arm` or `docker-arm` jobs fail or are canceled.
=> ci: clean ARM server even when previous steps or jobs fail

CHANGELOG.md, docs/references/admin_server.rst, docs/references/observability.rst, nix/overlays/haskell-packages.nix, postgrest.cabal, src/PostgREST/Admin.hs, src/PostgREST/AppState.hs, src/PostgREST/Logger.hs, src/PostgREST/Metrics.hs, src/PostgREST/Observation.hs, src/PostgREST/Query.hs, test/io/test_io.py, test/spec/Main.hs
Closes https://github.com/PostgREST/postgrest/issues/1526
```
curl localhost:3001/metrics
pgrst_schema_cache_query_time_seconds 1.3591601e-2
pgrst_schema_cache_loads_total 1.0
pgrst_db_pool_max 20.0
pgrst_db_pool_waiting 0.0
pgrst_db_pool_available 1.0
pgrst_db_pool_timeouts_total 0.0
```
Added a couple of schema cache load metrics plus 4 pool metrics.
- Hikari Pool metrics ([ref1](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/metrics/prometheus/HikariCPCollector.java#L40-L54), [ref2](https://github.com/brettwooldridge/HikariCP/blob/dev/src/main/java/com/zaxxer/hikari/metrics/prometheus/PrometheusMetricsTracker.java#L33-L46)).
- [WebSphere Application Server pool metrics](https://www.ibm.com/docs/en/was/9.0.5?topic=app-prometheus-metrics#rprf_promethe …
=> feat: connection pool metrics in admin server

.github/workflows/ci.yaml
DRYed the job according to the [GitHub Actions docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds):
> If a job fails or is skipped, all jobs that need it are skipped unless the jobs use a conditional expression that causes the job to continue. [...] If you would like a job to run even if a job it is dependent on did not succeed, use the always() conditional expression in jobs.<job_id>.if.
=> ci: DRY the cleanup job for ARM servers

docs/index.rst, docs/postgrest.dict, docs/references/cli.rst
@steve-chavez Once this is merged, I would then create another PR for the changes in `CLI`. Related #3248.
=> docs: add docs page for CLI

nix/tools/devTools.nix, nix/tools/tests.nix, nix/tools/withTools.nix, test/io/config.py, test/io/replica.sql, test/io/test_replica.py
* new --replica option to `postgrest-with-postgresql-*`
+ replica process is properly logged to usual temporary log files
* new command `postgrest-test-replica`
+ runs sanity tests on `test_replica.py`
* add `postgrest-test-replica` to `postgrest-check` and `postgrest-coverage`
=> test: sanity tests for primary and replica

CHANGELOG.md, src/PostgREST/Error.hs, test/spec/Feature/Query/RpcSpec.hs, test/spec/fixtures/roles.sql, test/spec/fixtures/schema.sql
=> fix: fix wrong 503 Service Unavailable on pg error 53400

src/PostgREST/Admin.hs, src/PostgREST/App.hs, src/PostgREST/AppState.hs
Extracted from https://github.com/PostgREST/postgrest/pull/3490
=> refactor: is ready Admin logic to AppState

nix/tools/devTools.nix
Generates ctags for Haskell and Python code.
=> nix: add postgrest-ctags command

CHANGELOG.md, docs/references/admin_server.rst, docs/references/configuration.rst, src/PostgREST/Admin.hs, src/PostgREST/AppState.hs, test/io/postgrest.py, test/io/test_big_schema.py, test/io/test_io.py
Related to https://github.com/PostgREST/postgrest/issues/3424#issuecomment-2094807500
=> feat: /ready pending state as 503 and 500 as fail 

docs/references/observability.rst, src/PostgREST/Metrics.hs, test/io/test_io.py
localhost:3001/metrics now includes:
```
pgrst_schema_cache_loads_total{status="FAIL"} 352.0 
pgrst_schema_cache_loads_total{status="SUCCESS"} 3.0
```
This allows testing the failure case on https://github.com/PostgREST/postgrest/issues/3424#issuecomment-2104904910
=> feat: add metric label for scache load

src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/Metrics.hs, src/PostgREST/Observation.hs, src/PostgREST/Query.hs
Towards solving https://github.com/PostgREST/postgrest/issues/3523
The fatal logic is now inside `usePool`. It centralizes the logic which is better for Locality of Behavior.
Removes:
- The need to do checkIsFatal on other parts of the code
- SCFatalFail/ConnFatalFail states which are no longer needed.
=> refactor: move checkIsFatal logic to usePool

CHANGELOG.md, cabal.project.freeze, nix/overlays/haskell-packages.nix, nix/tools/withTools.nix, postgrest.cabal, src/PostgREST/AppState.hs, src/PostgREST/Observation.hs, stack.yaml, stack.yaml.lock
Update hasql-notifications to include the fix on https://github.com/diogob/hasql-notifications/issues/24.
Which now reveals the following error:
```
$ postgrest-with-postgresql-16 --replica -f test/spec/fixtures/load.sql postgrest-run
17/May/2024:18:35:38 -0500: Successfully connected to PostgreSQL 16.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 13.2.0, 64-bit
17/May/2024:18:35:38 -0500: Failed listening for notifications on the "pgrst" channel. ERROR:  cannot execute LISTEN during recovery
17/May/2024:18:35:38 -0500: Retrying listening for notifications...
```
This is still not good because the LISTEN channel will be retried forever (with an unnecessary schema cache reload too) without a backoff.
=> fix: listener silent fail on replica

src/PostgREST/Error.hs, test/io/__snapshots__/test_cli/test_schema_cache_snapshot[dbRoutines].yaml, test/io/fixtures.sql, test/io/test_io.py
The pg_terminate_backend done in the io test:
`test_fail_with_automatic_recovery_disabled_and_terminated_using_query`
Can affect other connections.
Related https://github.com/PostgREST/postgrest/pull/3536.
=> test: isolate pg_terminate_backend to appname

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/Observation.hs, test/io/test_io.py, test/io/test_replica.py
Closes https://github.com/PostgREST/postgrest/issues/3523.
Now it works like:
```
$ postgrest-with-postgresql-16 --replica -f test/spec/fixtures/load.sql postgrest-run
19/May/2024:20:24:28 -0500: Retrying listening for notifications in 1 seconds...
19/May/2024:20:24:28 -0500: Failed listening for notifications on the "pgrst" channel. ERROR:  cannot execute LISTEN during recovery
19/May/2024:20:24:30 -0500: Retrying listening for notifications in 2 seconds...
19/May/2024:20:24:30 -0500: Failed listening for notifications on the "pgrst" channel. ERROR:  cannot execute LISTEN during recovery
19/May/2024:20:24:34 -0500: Retrying listening for notifications in 4 seconds...
19/May/2024:20:24:34 -0500: Failed listening for notifications on the "pgrst" channel. ERROR:  cannot execute LISTEN …
```
=> fix: listener retries with exponential backoff

CHANGELOG.md, src/PostgREST/AppState.hs, src/PostgREST/Config.hs, test/io/config.py, test/io/test_replica.py
=> feat: force listener to work on primary cluster 

CHANGELOG.md, src/PostgREST/CLI.hs, src/PostgREST/Observation.hs
Error logs starting with "An error occured..." are replaced with "Failed to..."
=> fix: remove verbosity from some error logs

docs/conf.py
Temporary solution to avoid the link check error mentioned here: https://github.com/PostgREST/postgrest/pull/3534#issuecomment-2121075773
It could be permanently fixed by addressing #3544
=> docs: ignore linkcheck for blog.frankel.ch

CHANGELOG.md, docs/references/admin_server.rst
Closes #3501
Adds missing documentation.
=> docs: add "config" and "schema_cache" endpoints to the admin server

CHANGELOG.md, src/PostgREST/Logger.hs, test/io/test_io.py
... since `log-level=debug` didn't exist when #3229 was added.
=> fix: log connection pool events on log-level="debug" instead of "info"

docs/references/api/resource_embedding.rst
=> docs: add example for double embedding when doing OR filtering across embeds

src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/Listener.hs
Clears the limitation mentioned on https://github.com/PostgREST/postgrest/pull/3536
The Listener no longer uses the https://hackage.haskell.org/package/retry package and instead uses a much simpler IORef in AppState for the delays.
Additionally it no longer uses exception throwing/catching, which is rather messy and brings some
concerns (https://github.com/PostgREST/postgrest/issues/3569#issuecomment-2146013327).
=> correct exponential backoff on Listener

CHANGELOG.md, docs/explanations/install.rst
As agreed on https://github.com/PostgREST/postgrest/issues/3501#issuecomment-2134016429
=> docs: deprecate EOL pg versions

docs/explanations/architecture.rst, docs/references/configuration.rst, docs/references/listener.rst, docs/references/observability.rst, docs/references/schema_cache.rst
Adds missing docs for new logging features.
=> Add missing docs for release 12.2.0

CHANGELOG.md, docs/references/listener.rst, src/PostgREST/AppState.hs, src/PostgREST/Listener.hs
As mentioned on https://github.com/PostgREST/postgrest/issues/3147#issuecomment-2181596749.
Revert "prevent GSSAPI error between Listener and pool"
This reverts commit 4beac10d3d0116e0fa79324782b1baba62bb1368.
=> fix: don't reload cache on every listener fail

CHANGELOG.md, docs/references/configuration.rst, src/PostgREST/Config.hs, test/io/test_cli.py
Forbids `server-port` and `admin-server-port` from being equal altogether, despite they might not conflict at all in case admin and app are bound to different addresses. Implemented as per the discussion at
https://github.com/PostgREST/postgrest/issues/3508#issuecomment-2125123633
Fixes #3508
=> config forbid same server-port and admin-server-port

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/CLI.hs, src/PostgREST/Listener.hs, src/PostgREST/Observation.hs, test/io/test_io.py
Fixes https://github.com/PostgREST/postgrest/issues/3523.
Now if there's a failure when obtaining the pg version OR schema cache, we do the same retrying process. This way we don't add two retries.
Refactors and renames the "connectionWorker" to "schemaCacheLoader". This makes more sense since what we really want is the schema cache, the version is the pre-requisite for ensuring our schema cache queries work.
Additionally, we no longer log ` Attempting to connect to the database...` at startup unnecessarily. This is only logged whenever there's a retry attempt.
=> fix: schema cache retrying without backoff

CHANGELOG.md, src/PostgREST/Response/OpenAPI.hs
See #3504 for more details.
When using OpenAPI docs with some code generators, rowFilter parameters will be incorrectly typed. Because Row Filter parameters are always a string (e.g. `eq.1001`), the `format` field should not be included.
Note: I could not see any tests to update for this case. Please let me know if I should add a test (presumably to `test/spec/Feature/OpenApi/OpenApiSpec.hs`).
=> fix: Remove OpenAPI format for rowFilter params

CHANGELOG.md, postgrest.cabal, src/PostgREST/Admin.hs, src/PostgREST/App.hs, src/PostgREST/Network.hs, src/PostgREST/Observation.hs, test/io/test_io.py
This adds resolved host IPs to "listening..." messages emitted when app and admin server start
=> log: add resolved host to "Listening..." messages

CHANGELOG.md, src/PostgREST/Plan.hs, src/PostgREST/Plan/Types.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/AggregateFunctionsSpec.hs, test/spec/fixtures/data.sql, test/spec/fixtures/schema.sql
Missing:
These fixes are also needed for https://github.com/PostgREST/postgrest/pull/3640
=> Fixes when using aggregates inside Spread Embedded Resources

CHANGELOG.md, docs/references/observability.rst, docs/tutorials/tut0.rst, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/Observation.hs, test/io/test_io.py
It's important for observability to have an historic trace of the pool size. Currently we expose it on the metrics endpoint, but not all deployments use it.
This logs the pool size after the successful connection log to make it more visible:
```
<timestamp>: Connection Pool initialized with a maximum size of 4 connections
```
=> feat: log pool maximum size

docs/references/errors.rst
#2925 added support for aggregate functions. This commit adds the PGRST123 error code description to the docs.
=> docs: add PGRST123 to error table

CHANGELOG.md, docs/references/api/functions.rst, docs/references/api/preferences.rst, src/PostgREST/ApiRequest/Preferences.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/Response.hs, src/PostgREST/Response/OpenAPI.hs, test/spec/Feature/Query/RpcSpec.hs
Using this preference was deprecated in 6c3d7a9, in favor of Functions with an array of JSON objects.
This change removes support for this feature, planned for the next major version.
=> remove support for Prefer: params=single-object

CHANGELOG.md, src/PostgREST/Logger.hs, src/PostgREST/Metrics.hs, src/PostgREST/Observation.hs
It used to be that this was only enabled with log-level=debug but doing it this way is misleading for the default log-level. For example:
```
$ PGRST_DB_SCHEMAS="apflora" postgrest-with-postgresql-16  -f test/io/big_schema.sql postgrest-run
...
13/Nov/2024:22:08:20 -0500: Config reloaded
13/Nov/2024:22:08:20 -0500: Schema cache queried in 36.3 milliseconds
13/Nov/2024:22:08:20 -0500: Schema cache loaded 326 Relations, 305 Relationships, 7 Functions, 0 Domain Representations, 4 Media Type Handlers, 1194 Timezones
```
The "Schema cache loaded" can take a while to appear, yet the 22:08:20 time is the same. If we reveal the load time this is clarified:
```
13/Nov/2024:22:08:37 -0500: Schema cache loaded in 16770.1 milliseconds
```
=> fix: always show schema cache load time

CHANGELOG.md, docs/references/api/resource_representation.rst, src/PostgREST/Error.hs, test/spec/Feature/Query/NullsStripSpec.hs, test/spec/Feature/Query/SingularSpec.hs
Currently it's redundant.
```JSON
{"message":"JSON object requested, multiple (or no) rows returned",
"details":"The result contains 0 rows"}
```
Now:
```json
{"message":"Cannot coerce the result to a single JSON object",
"details":"The result contains 0 rows"}
```
Also correct docs which had a wrong error code.
=> fix: clarify PGRST116 error message

docs/references/configuration.rst
I had to figure stuff out and I thought it would be useful for everyone if I provided some more information
=> docs: Add an example for PGRST_APP_SETTINGS_*

CHANGELOG.md, docs/references/api/tables_views.rst, src/PostgREST/ApiRequest/QueryParams.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Plan.hs, src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/QuerySpec.hs
=> feat: allow not_null value for the is operator

CHANGELOG.md, src/PostgREST/SchemaCache.hs, test/spec/Feature/Query/InsertSpec.hs, test/spec/fixtures/schema.sql
=> fix: insert with missing=default uses column default before using domain default

CHANGELOG.md, docs/references/api/tables_views.rst, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Plan.hs, src/PostgREST/Plan/Types.hs, src/PostgREST/Query/QueryBuilder.hs, src/PostgREST/Query/SqlFragment.hs, test/spec/Feature/Query/AndOrParamsSpec.hs, test/spec/Feature/Query/QuerySpec.hs, test/spec/Feature/Query/RpcSpec.hs, test/spec/fixtures/data.sql, test/spec/fixtures/schema.sql
Closes #2255 
When an `fts` operator is used, then it applies `to_tsvector` to the filtered column. For example:
```
/table?column=fts(simple).test
```
is equivalent to this in SQL:
```sql
SELECT *
FROM table
WHERE to_tsvector('simple', column) = to_tsquery('simple', 'test')
```
<s>
If the `totsv` modifier (short for `to_tsvector`) is used for `fts` operators then it applies `to_tsvector` to the filtered column. For example:
```
/table?column=totsv.fts(simple).test
```
Is equivalent to this in SQL:
```sql
SELECT *
FROM table
WHERE to_tsvector('simple', column) = to_tsquery('simple', 'test')
```
</s>
=> feat: apply `to_tsvector` to the filtered columns when a `fts` operator is used

CHANGELOG.md, src/PostgREST/Auth.hs, test/io/test_io.py
Fixes #3788.
Fixed the JWT cache not purging expired tokens in cache. This is tested by adding a new metric `pgrst_jwt_cache_size`.
@steve-chavez I can also divide this into two commits, one for adding the new metric and the other for bug fix. Please review and let me know.
Edit: I'll continue development once #3802 gets merged.
=> fix: jwt cache is not purged

postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/AppState.hs, src/PostgREST/Auth.hs, src/PostgREST/Auth/Types.hs, src/PostgREST/Query.hs
The `AuthResult` type does not belong to AppState module. This commit refactors this by moving it to a new module `Auth/Types.hs`.
The dependency graph now looks something like
```haskell
-- App.hs <-- Auth.hs <-- AppState.hs <-- Auth/Types.hs
```
=> refactor: move AuthResult to Auth/Types.hs module

CHANGELOG.md, src/PostgREST/AppState.hs, test/io/test_io.py
Closes #3841.
Should this go under feat? Maybe we should introduce new commit prefix for logging like maybe `log: ...`?
=> fix: log 503 client error to stderr

src/PostgREST/ApiRequest.hs, src/PostgREST/ApiRequest/QueryParams.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/Query.hs, src/PostgREST/Response.hs
This is first steps to improving our error infrastructure.
- All error types should originate from `Error` module
- Removes re-exporting types
- No need to depend on an extra module (namely `ApiRequest/Types`).
- Would help in representing errors internally to something similar to how we group them in [docs](https://docs.postgrest.org/en/v12/references/errors.html#postgrest-error-codes)
- Would eventually help in adding new error types for error related issues (eg. #3600)
=> refactor: move `ApiRequestError` to Error module

docs/postgrest.dict, docs/references/api/aggregate_functions.rst
Simplifies the aggregate functions docs, as mentioned here https://github.com/PostgREST/postgrest/pull/3640#discussion_r1953627575, this will help integrate the docs in #3640.
=> docs: make the aggregate functions docs less verbose

CHANGELOG.md, docs/references/errors.rst, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/SchemaCache/Identifiers.hs, test/io/test_big_schema.py, test/io/test_io.py, test/spec/Feature/ConcurrentSpec.hs, test/spec/Feature/Query/DeleteSpec.hs, test/spec/Feature/Query/InsertSpec.hs, test/spec/Feature/Query/MultipleSchemaSpec.hs, test/spec/Feature/Query/QuerySpec.hs, test/spec/Feature/Query/UpdateSpec.hs
Add new `TableNotFound` error and add json error
message for this error. Closes #3697, closes #3602.
(Couldn't think of a better changelog/commit message. Feel free to suggest a new/better message).
=> fix: handle queries on non-existing table gracefully

CHANGELOG.md, docs/references/auth.rst, docs/references/errors.rst, src/PostgREST/Auth.hs, src/PostgREST/Error.hs, test/io/test_io.py, test/spec/Feature/Auth/AuthSpec.hs
BREAKING CHANGE
We were exposing internal errors via `Show`. This commit improves error messages for better user experience.
Closes #3600, closes #3926.
I'll add docs once this design/change is approved.
=> fix: improve jwt errors

CHANGELOG.md, src/PostgREST/Plan.hs, test/spec/Feature/Query/DeleteSpec.hs, test/spec/Feature/Query/UpdateSpec.hs, test/spec/Feature/Query/UpsertSpec.hs, test/spec/fixtures/data.sql, test/spec/fixtures/privileges.sql, test/spec/fixtures/schema.sql
Closes #3013. Do we need more tests? Not sure if ordering is used for `POST` requests.
=> fix: Fix ordering with mutation queries

CHANGELOG.md, docs/references/errors.rst, src/PostgREST/ApiRequest.hs, src/PostgREST/Error.hs, src/PostgREST/Plan.hs, src/PostgREST/Response.hs, test/spec/Feature/OpenApi/DisabledOpenApiSpec.hs, test/spec/Feature/Query/QuerySpec.hs
Removes the empty `NotFound` error.
Closes #3906.
=> fix: Add errors OpenAPIDisabled and InvalidResourcePath

CHANGELOG.md, docs/references/errors.rst, docs/references/observability.rst, src/PostgREST/Error.hs, test/io/test_io.py, test/spec/Feature/Query/ErrorSpec.hs
With this feature, PostgREST responds with error code in the `Proxy-Status` header.
Closes #2967.
=> feat: add Proxy-Status header for better error response

CHANGELOG.md, src/PostgREST/MediaType.hs
The media type parser had some bugs. It didn't allow space separated parameters and the handling of quoted text was clunky. This commit improves the media type parser to fix these bugs.
Closes #3498 without too many changes. More refactoring is needed but that's a task for the future.
=> fix: Fix parsing of the `for` parameter of plan media type

.github/workflows/test.yaml, .gitignore, nix/tools/generate_targets.py, nix/tools/loadtest.nix, test/load/fixtures.sql, test/memory/memory-tests.sh
Closes https://github.com/PostgREST/postgrest/issues/4001.
This loadtests the jwt decoding logic. For this it adds an optional `-k`(kind) parameter to `postgrest-loadtest` and
`postgrest-loadtest-against`.
Old kind (default):
```
postgrest-loadtest -k mixed
postgrest-loadtest-against -k mixed
```
New kind:
```
postgrest-loadtest -k jwt
postgrest-loadtest-against -k jwt
```
Internally it uses a dynamically generated targets file using python which looks like:
```
GET http://postgrest/authors_only
Authorization: Bearer <jwt>
GET http://postgrest/authors_only
Authorization: Bearer <another-jwt>
...
```
Then this is used to run vegeta with the `-lazy` option.
=> nix: add loadtest with unique JWTs

.github/workflows/test.yaml, .gitignore, nix/tools/generate_targets.py, nix/tools/loadtest.nix, test/load/fixtures.sql
Closes #4001.
This proves the fix on https://github.com/PostgREST/postgrest/pull/3889, while running on v12.2.9 the loadtest doesn't even finish all the generated targets (50000) and has poor throughput, while HEAD will finish and show better throughput.
This has to be proved locally now since we already merged #3889 and released it, but it's very clear:
```
[nix-shell:~/Projects/postgrest]$ postgrest-loadtest-against -k jwt v12.2.9
Running loadtest on "v12.2.9"...
Preparing worktree (detached HEAD b454f29b)
Created 50000 targets in /home/stevechavez/Projects/postgrest/test/load/gen_targets.http (0.80s)
postgrest-with-postgresql-17: You can connect with: psql 'postgres:///postgres?host=/run/user/1000/postgrest/postgrest-with-postgresql-17-l0c/socket' -U postgres …
```
=> test: add loadtest for async purge of JWT cache

src/PostgREST/Plan.hs, src/PostgREST/Plan/CallPlan.hs, src/PostgREST/Plan/ReadPlan.hs, src/PostgREST/Query/QueryBuilder.hs
Refactor for #4033.
I have added a comment to later enforce this uniqueness by using a `Set` whereever applicable instead of a `List`.
=> refactor: change CallPlan returnings to a Set instead of a List

src/PostgREST/ApiRequest.hs, src/PostgREST/App.hs
This allows obtaining the preferences header before doing the full parse on userApiRequest. Which is needed by #3507.
=> refactor: split preference parsing from userApiRequest

CHANGELOG.md, docs/references/admin_server.rst, src/PostgREST/Admin.hs, test/io/test_io.py
BREAKING CHANGE
The endpoint was at risk of being left unprotected when exposing it.
The accompanying `admin-server-config-enabled` config was also dropped.
Closes https://github.com/PostgREST/postgrest/issues/3956
=> drop: Admin server `/config` endpoint

docs/references/auth.rst
Add a note describing that the used JSPath DSL does not strictly follow the JSONPath as described in RFC 9535.
Closes #4092.
=> docs: add note in JWT Role Extraction section

CHANGELOG.md, docs/references/configuration.rst, src/PostgREST/Config.hs, test/io/test_io.py
These two settings throw parse error when set to "". This commit allows them to explicitly be set to empty.
Partially addresses #4074.
=> fix: allow db-extra-search-path to accept empty value

docs/explanations/external_auth.rst, docs/integrations/jwt_gen.rst, docs/postgrest.dict, docs/references/auth.rst, docs/tutorials/tut1.rst
Partially addresses https://github.com/PostgREST/postgrest/issues/4110
Also [docs: external authentication page in explanations](https://github.com/PostgREST/postgrest/commit/f2002437f02acc3c78aa8d5cf5747d4819f6b0b6)
=> docs: move jwt using SSL to tutorial 1 

src/PostgREST/Metrics.hs
As requested in https://github.com/PostgREST/postgrest/pull/4084#discussion_r2115866081
This is a simple refactoring that changes MetricsState to be a proper record.
It also changes MetricsState initialization code to use Applicative syntax.
=> refactor: Define MetricsState as record and use Applicative to initialize one

nix/tools/generate_targets.py, nix/tools/style.nix, test/io/test_cli.py
Now `postgrest-lint` shows:
```
Linting workflows...
Scanning nix files for unused code...
Scanning python files for unused code...
nix/tools/generate_targets.py:13: unused variable 'JWT_DURATION' (60% confidence)
test/io/test_cli.py:6: unused import 'repeat' (90% confidence)
```
Also corrected the above detected files
=> nix: detect unused python code

.github/workflows/test.yaml, .gitignore, nix/tools/generate_targets_rsa.py, nix/tools/loadtest.nix
As requested in https://github.com/PostgREST/postgrest/pull/4084#issuecomment-2920351221
Note that after this PR `gen_targets` no longer generates JWTs with short expiration to test current implementation cache cleanup.
That's because generating JWTs takes considerable more time right now and generating 50k JWTs takes more than 2 minutes on my beefy MacBook Pro.
Not sure if it makes sense to merge it without changing the JWT cache to the bounded one (either LRU or Sieve).
=> test: Use RSA 4096 algorithm for JWT load test

.github/workflows/test.yaml, nix/tools/generate_targets.py, nix/tools/loadtest.nix, nix/tools/merge_monitor_result.py, nix/tools/monitor_pid.py, nix/tools/withTools.nix
Closes https://github.com/PostgREST/postgrest/issues/4107.
Adds a table for each loadtest that looks like this:
|   Elapsed seconds |   main CPU (%) |   main MEM (%) |   main Real (MB) |   head CPU (%) |   head MEM (%) |   head Real (MB) |
|-------------------|----------------|----------------|------------------|----------------|----------------|------------------|
|                 1 |              8 |          0.272 |           43.109 |              6 |          0.282 |           44.723 |
|                 2 |             19 |          0.462 |           73.332 |             21 |          0.453 |           71.895 |
|                 3 |             19 |          0.503 |           79.777 |             21 |          0.515 |           81.691 |
|                 4 |             21 | …
=> nix: add process monitoring for loadtests

.github/workflows/check.yaml, default.nix, nix/tools/gitTools.nix, shell.nix
Adds a new script `postgrest-commitlint` to validate the commit messages.
Closes #4122.
=> nix: add commitlint to lint commit messages

.github/workflows/check.yaml, nix/tools/gitTools.nix
Fixes CI failure of `commitlint` as occurred in [#4128 (comment)](https://github.com/PostgREST/postgrest/pull/4128#issuecomment-2981862857).
=> ci: fix commitlint CI failure

CHANGELOG.md, src/PostgREST/Version.hs
Prevents future broken links. Related to #4080.
=> fix: fix OpenAPI broken docs link

nix/tools/style.nix
I have noticed `postgrest-lint` to be quite slow, primarily because of `hlint`. It turns out that `hlint` can be run on multiple threads. This reduces `postgrest-lint` runtime depending on number of cores and threads.
I think `4` threads is good default. The github action runners also have 4 cores according to [github docs](https://docs.github.com/en/actions/how-tos/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories).
=> nix: run hlint on multiple threads

docs/postgrest.dict, docs/references/api/functions.rst
I forgot to add the docs for #4033 as mentioned in [#4033 (comment)](https://github.com/PostgREST/postgrest/pull/4033#issuecomment-2825420176). This adds a horizontal filtering sub-section with example in table-valued functions section.
=> docs: horizontal filtering on table-valued functions

test/load/targets.http
We now have dedicated JWT loadtests, so it's no longer necessary to mix this here.
First step towards solving https://github.com/PostgREST/postgrest/issues/4123
=> test: remove jwt decoding from mixed loadtest

postgrest.cabal, src/PostgREST/Query.hs, src/PostgREST/Query/PreQuery.hs
Small step towards solving #3934.
Adds a module that builds pure SQL snippets for the transaction variables and the pre-request function.
=> refactor: add PreQuery module

postgrest.cabal, src/PostgREST/ApiRequest.hs, src/PostgREST/ApiRequest/Payload.hs, src/PostgREST/ApiRequest/Types.hs, src/PostgREST/Plan.hs, src/PostgREST/Query.hs, src/PostgREST/Response.hs
For #3166, I need to parse the request body. Just like we have a module for parsing `QueryParams`, request body can be separated into a `Payload` module easier implementation of #3166. It would also help not polluting the `ApiRequest` module with too much paring logic.
=> refactor: move request body to a Payload.hs module

CHANGELOG.md, src/PostgREST/Network.hs, test/io/postgrest.py, test/io/test_io.py
The IPv6 address logged at the startup like `::1:80` was wrong because the port isn't clearly separated. This commit corrects it, now logging as `[::1]:80` as discussed in [#4288 (comment)](https://github.com/PostgREST/postgrest/pull/4288#discussion_r2308273098).
This also allows the refactor on #4288 to go smoothly without changing any behavior.
=> fix: format of IPv6 address logged at PostgREST startup

test/io/test_io.py
The "listening on unix" observation was not covered by our tests, hence added here. Also discussed in [#4288 (comment)](https://github.com/PostgREST/postgrest/pull/4288#discussion_r2308219704).
=> test(log): postgrest listening on unix socket observation

src/PostgREST/Admin.hs, src/PostgREST/App.hs, src/PostgREST/Network.hs, src/PostgREST/Observation.hs, test/doc/Main.hs, test/io/test_io.py
While working on #4269, I noticed some redundant code in `Network` and `Observation` modules. This commit deduplicates the code in those modules.
=> refactor: deduplicate host resolution logic and observations

CHANGELOG.md, src/PostgREST/App.hs, src/PostgREST/Logger.hs, src/PostgREST/Observation.hs, src/PostgREST/Query.hs, src/PostgREST/Query/PreQuery.hs, test/io/test_io.py
Closes https://github.com/PostgREST/postgrest/issues/4226.
This requires moving query generation to the top App.hs module.
At this point is also simple to log the transaction variables + the pre-request function call but this is not done here to reduce scope.
=> fix: not logging OpenAPI queries

postgrest.cabal, src/PostgREST/App.hs, src/PostgREST/MainTx.hs, src/PostgREST/Query.hs, src/PostgREST/Response.hs
This splits off the transaction concerns into a MainTx module.
It's just moving some functions inside the Query module to the MainTx module. Some types names were also changed so they don't have the "Query" prefix, to avoid confusion.
=> refactor: make Query module pure

test/io/config.py, test/io/test_cli.py, test/io/test_io.py, test/io/test_replica.py, test/io/test_sanity.py, test/io/util.py
Towards #4342. Doing some cleanup, so when we actually integrate `pylint`, it applies cleanly.
=> test(io): remove unused module imports

docs/references/cli.rst
The CLI page had the config file parameter missing. This commit adds that. Also adds the CLI usage output which shows all available options. Closes #4300.
=> docs: document config file parameter on CLI page

CHANGELOG.md, docs/explanations/install.rst, docs/references/cli.rst, postgrest.cabal, src/PostgREST/CLI.hs, src/PostgREST/Client.hs, src/PostgREST/Network.hs, test/io/config.py, test/io/postgrest.py, test/io/test_cli.py
The `--ready` flag is a wrapper around the admin server `/ready` request. This is done through using an http client library in postgrest.
Closes #4239.
=> add: `--ready` flag for postgrest healthcheck

docker-hub-readme.md
Fixes a broken sponsor's logo.
=> Fix broken logo URL in Docker Hub README
